### ISSUE TITLE
docz的menu属性无效

### ISSUE THREAD

**Issue by long-zhuge** [umijs/father#105]
从 umi-library@1.6.0 改为 father@2.18.3 后，在 .fatherrc.js 中配置 docz 的属性未达到官方文档呈现的效果。

- 官方文档

```
Use this option to specify the order of your documents in the menu. You can pass a simple string or if you want to order a nested menu you can pass an object with the name of your document and the menu order of it.

// config
export default {
  menu: [
    'Getting Started',
    { name: 'Components', menu: ['Alert', 'Button'] }
  ]
}
```

- 项目中配置

```
export default {
  doc: {
    menu: [
      '首页',
      '更新日志',
      {
        name: '组件',
        menu: [
          'LinkBtn',
        ]
      }
    ]
  },
}
```

- 实际呈现效果
![image](https://user-images.githubusercontent.com/14194437/65223912-ba100c00-daf4-11e9-9b19-99d4f9f00a33.png)

**Comment by fodurrr** [comment]
Same issue here

**Comment by shengbeiniao** [comment]
mark

**Comment by shengbeiniao** [comment]
查了下源码
[docz-them-umi](https://github.com/umijs/docz-theme-umi/blob/c461509da380c3d94c5c05a072f968515c5eaf06/src/components/shared/Sidebar/CustomMenu.tsx#L59)

**Comment by johanazhu** [comment]
同问

**Comment by PeachScript** [comment]
推荐使用 dumi 进行组件库研发：https://d.umijs.org

**Comment by long-zhuge** [comment]
> 推荐使用 dumi + father-build 进行组件库研发：https://d.umijs.org/guide/getting-started

已经使用 dumi 了
