### ISSUE TITLE
没有配置 tsconfig 就会报错

### ISSUE THREAD

**Issue by DiamondYuan** [umijs/father#11]
![image](https://user-images.githubusercontent.com/9692408/58773848-43a4d800-85f1-11e9-9a27-ad36a7c9609e.png)

**Comment by DiamondYuan** [comment]
![image](https://user-images.githubusercontent.com/9692408/58773857-561f1180-85f1-11e9-848b-9dac89ac607f.png)


![image](https://user-images.githubusercontent.com/9692408/58773862-5b7c5c00-85f1-11e9-9432-d43213734a84.png)

**Comment by sorrycc** [comment]
Closed via #14
