### ISSUE TITLE
father-build@1.11.0、father@2.21.0  build --watch失效

### ISSUE THREAD

**Issue by NexxLuo** [umijs/father#115]
father build --watch
father-build build --watch

更改文件后，控制台无文件rebuild的输出，未重新对文件进行build？

windows 10 powershell

**Comment by sorrycc** [comment]
2.20 是好的？

**Comment by NexxLuo** [comment]
> 2.20 是好的？

试了2.20、2.19都不行 。之前用的2.13是可以的

**Comment by NexxLuo** [comment]
从2.19开始不行，2.18可以

**Comment by sorrycc** [comment]
2.19 没做相关的改动，我们一直在用最新版开发（加 --watch），没发现问题。你先排查下自己的项目，搞不定给复现步骤。

**Comment by NexxLuo** [comment]
node_modules、lock文件全删掉，重装就可以了
