### ISSUE TITLE
father 的 userconfig 什么时候可以支持透传 docz 的函数型配置

### ISSUE THREAD

**Issue by ACERY1** [umijs/father#119]
![image](https://user-images.githubusercontent.com/19555547/66557118-f084f800-eb83-11e9-9546-06bf346270a5.png)

从 bigfish 过来的，在 bigfish 的 library.doc 里配置了 docz的 plugins 和 hooks ，但是看到 father 并不支持透传 docz 的函数型配置，请问这个TODO什么时候能够完成

**Comment by PeachScript** [comment]
推荐使用 dumi + father-build 进行组件库研发：https://d.umijs.org/guide/getting-started
