### ISSUE TITLE
.fatherrc.ts 配置为  esm: 'rollup',cjs: 'rollup'时报错

### ISSUE THREAD

**Issue by fengyun2** [umijs/father#125]
运行 `father build` 时，.fatherrc.ts 配置为  `esm: 'rollup',cjs: 'rollup' ` 时报错，改为  `esm: 'babel',cjs: 'babel' ` 可以正常打包

```ts
const options: IBundleOptions = {
  entry: 'src/index.ts',
  esm: 'rollup',
  cjs: 'rollup'
```

报错信息：

![image](https://user-images.githubusercontent.com/8147202/66986952-5debd800-f0f2-11e9-9f27-a40494507414.png)

**Comment by sorrycc** [comment]
仔细阅读下这一部分，https://github.com/umijs/father#%E5%85%B3%E4%BA%8E-dependenciespeerdependencies-%E5%92%8C-external ，react 这类依赖包应该放 dependencies 或 peerDependencies。
