### ISSUE TITLE
怎么解决组件库中antd是最新版本，使用组件库的项目antd是2.7.0，导致的编译错误

### ISSUE THREAD

**Issue by tancyan** [umijs/father#126]
组件库中的antd是最新的，在packages.json中配置peerDependencies：{antd:"^3.24.0","react": "^16.8.6"}，发布组件库，antd不会被打进包里面，组件库中封装了一个IconFont的组件

项目中引入组件库，编译报错，项目中antd:2.7.0,"react": "15.4.2"

![1571628098(1)](https://user-images.githubusercontent.com/8563044/67174604-36985200-f3f5-11e9-811c-0e9df281c5d8.jpg)

**Comment by sorrycc** [comment]
要求 antd@3，项目就不能用 antd@2 吧。

**Comment by tancyan** [comment]
你好，怎么能做到项目仍然用antd@2，组件库是antd@3吗？

**Comment by AimLuo** [comment]
==

**Comment by PeachScript** [comment]
现在 antd@4 了，issue 过期，closed...
