### ISSUE TITLE
如何配置extraBabelIncludes参数

### ISSUE THREAD

**Issue by guozhaolong** [umijs/father#128]
我要扩展g6的源码，如何能让babel编译通过？我看解决办法是配置babel include g6的目录，但是目前father没有这个参数啊

**Comment by sorrycc** [comment]
打 umd 包？非 umd 包不需要配，因为不会打包依赖；umd 包走的 rollup，好像也不会有 es6 语法的问题。

**Comment by guozhaolong** [comment]
打esm包，做成一个react component发布的，我看了打包完的文件:
![image](https://user-images.githubusercontent.com/1046601/67306441-8b3ce980-f529-11e9-8be4-fb813fedae51.png)
我在外部调用的时候是没法找到g6/src/item目录下的文件的

**Comment by sorrycc** [comment]
`@antv/g6` 放 dependencies 里。

**Comment by guozhaolong** [comment]
我的场景是想继承g6中的一个Item类，运行时提示Class constructor Item cannot be invoked without 'new'，我也搜了一下相关问题，锁定到babel需支持对外部引入的对象实现继承这里，我看babel7是支持的，有人说的解决方案是需要将Item类也经过babel编译，配置后报了Item找不到default export

**Comment by guozhaolong** [comment]
目前的配置是这样
![image](https://user-images.githubusercontent.com/1046601/67535404-060e2c00-f705-11e9-8c91-99399f98cfe1.png)

代码是这样
![image](https://user-images.githubusercontent.com/1046601/67535441-3655ca80-f705-11e9-8aa2-0616864c8cd1.png)

生成的代码是这样
![image](https://user-images.githubusercontent.com/1046601/67535421-1f16dd00-f705-11e9-85ce-0c3db1072438.png)

访问页面的时候报
![image](https://user-images.githubusercontent.com/1046601/67535465-4ec5e500-f705-11e9-952d-8d446b5d8413.png)
