### ISSUE TITLE
:question 打包时单独生成css/less文件

### ISSUE THREAD

**Issue by Francecil** [umijs/father#13]
## What happens?
项目是基于 antd 的二次开发，一个业务组件库，tsx 和样式（less）分离

配置文件
```
  entry: 'src/index.ts',
  cjs: 'babel',
  esm: 'babel',
  umd: {
    name: "xxx",
    globals: {
      react: 'React',
      antd: 'antd'
    },
    file:"index"
  },
  extractCSS: true,
```
打包后生成 `dist lib es` 三个目录

dist 目录下只有 js 和 .d.ts ，没有 less或者css文件，比如像andt的 `antd.css` `antd.less`

导致项目中想全局引入样式时，没有途径

已配置了
```
extractCSS: true,
```
但我猜测是不是还缺少了什么配置？

## 相关环境信息
father 版本：2.2.1
Node 版本：10.15.1
操作系统：win10

**Comment by leftstick** [comment]
没法复现，最好提供一个可复现的repo

**Comment by Francecil** [comment]
```bash
git clone https://github.com/Francecil/antd-virtualized.git
cd antd-virtualized
npm install
npm run build
```
然后看 dist 目录里面 没有css

**Comment by leftstick** [comment]
我看你这个项目的结构是在模仿ant-design？那打包工具得参考[antd-tools](https://github.com/ant-design/antd-tools)

**Comment by Francecil** [comment]
@leftstick 
项目结构参考而已，只要是方便使用  babel-plugin-import  来按需加载

主要是不知道如何配置才能单独打包一个css出来

**Comment by leftstick** [comment]
他那个结构需要配合`antd-tools`才能打包出你想要的结果，用“爸爸”做怎样的改造才能达成相同的效果我还真没想过，需要 @sorrycc 大佬解答了

**Comment by Francecil** [comment]
我另写了一个最简化的项目，src下只含 `index.tsx` 和 `index.less`
在 index.tsx 里面没有手动引用的情况下 --- `import './index.less'`
如上同样的配置 还是不能生成单独的 css

是不是还得借助`mini-css-extract-plugin`这类的插件才能实现？

**Comment by sorrycc** [comment]
简单的例子给个复现？配 `extractCSS` 了吗？可以和 https://github.com/umijs/father/tree/master/src/fixtures/build/rollup-css-extract 比较下有啥区别。

**Comment by Francecil** [comment]
@sorrycc 
不一样的地方在于，我的 index.js 里面没有
```
import './foo.css';
```
这句引用css的代码

看了下`extractCSS`的效果应该是将文件中引用的css打包在一起，没有被引用的会被忽略

**Comment by DiamondYuan** [comment]
想要用 father 来替代 ant-tool .我也遇到了同样的问题。

**Comment by DiamondYuan** [comment]
https://github.com/DiamondYuan/switch

想单独的把 index.less 转化为 index.css

**Comment by sorrycc** [comment]
@Francecil rollup 模式不支持，你可能需要用 babel 模式。

**Comment by sorrycc** [comment]
@DiamondYuan assets 下的 less? 这个目录是干嘛用的？

**Comment by DiamondYuan** [comment]
> @DiamondYuan assets 下的 less? 这个目录是干嘛用的？

rc 系列的组件样式和组件是完全分离的。需要单独引入。

**Comment by sorrycc** [comment]
@zombieJ assets 目录的用途是啥？用户要用到的吗？

**Comment by Francecil** [comment]
@sorrycc 
嗯，当前就是用的babel 可以实现按需加载(样式分离 以及less变量覆盖)

看了下 rollup 的文档 及 rollup-plugin-postcss 代码，不支持打包未引用css到单独一个css上面

后面的想法是：
1. 顶层目录新建一个 style.js 手动引用项目所有的css，然后 rollup 入口指定为style.js 并通过 rollup-plugin-postcss 插件打包出单独的css出来。
2. 编写 rollup 插件，自动扫描 src 文件夹下的所有css文件，并打包

**Comment by chenty** [comment]
@Francecil 考虑到cssModule，我倾向于在js里面引用css

**Comment by zombieJ** [comment]
> @zombieJ assets 目录的用途是啥？用户要用到的吗？

组件提供的默认样式，是否使用用户可以自行选择。

**Comment by minwe** [comment]
使用 babel 编译的时候，`es` 和 `lib` 目录的 less 可以支持转成 css 吗？

**Comment by Francecil** [comment]
问题已解决。单独生成 css,less 是通过另外编写脚本实现，参考了 [antd-tools](https://github.com/ant-design/ant-design/blob/master/.antd-tools.config.js) 思路。
1. 先用father打出 dist,lib,es 包。
2. 生成`lib/style/components.less`: 将文件引用所有组件的less
3. 生成`dist/index.less`: 其内容为 `lib/style/components.less` 和 `/lib/style/index.less`
4. 利用 rollup-plugin-postcss 将 `dist/index.less` 转 `dist/index.css`

**Comment by Francecil** [comment]
js 代码中引入css，好像也能够做到 按需加载 和 样式覆盖。
像`ant-design`等组件库为何 jsx 和 css 是分离的，求教下

**Comment by zpr1g** [comment]
现在还是没解决啊 :ear:

**Comment by Mr-jiangzhiguo** [comment]
demo：<https://github.com/jsany/lean>

**Comment by zpr1g** [comment]
所以配了 `extractCSS: true`，还得配置 `lessInRollupMode` 或者 `lessInBabelMode` 才行？

**Comment by zsjun** [comment]
import postcss from "rollup-plugin-postcss";
postcss({
      extensions: [".scss", ".css"],
      extract: true,
      plugins: [postcssImport()],
    }),
这么配置就可以了

**Comment by krmao** [comment]
> 

什么是 postcssImport

**Comment by arleyGuoLei** [comment]
> postcssImport

请问这是个啥插件?
