### ISSUE TITLE
SyntaxError Unexpected token, expected "{" 

### ISSUE THREAD

**Issue by cassiewang01** [umijs/father#139]
你好，我使用typescript，想用father打包，结果一直报错：
报错如下：
![image](https://user-images.githubusercontent.com/22312427/67679880-13f1d480-f9c5-11e9-961e-8b0c872b9cd0.png)

版本："father": "^2.24.0",
.fatherrc.js配置如下
```
export default {
  entry: 'src/index.js',
  esm: 'rollup',
  cjs: 'rollup',
};
```

tsconfig.json配置：
```
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "importHelpers": true,
    "jsx": "react",
    "esModuleInterop": true,
    "sourceMap": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["src/*"]
    },
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true
  }
}

```

**Comment by sorrycc** [comment]
入口文件是 ts? 给可复现的步骤。

**Comment by cassiewang01** [comment]
入口文件用js，因为我是已有项目迁移过来的
入口文件index.js内容：
`
export { default as Document } from './document';
`

document文件夹中的index.tsx，内容（具体全部代码不方便贴）
`
import React from 'react';
import PropTypes from 'prop-types';

export default class Document extends React.PureComponent<DocumentProps> {
...
}
`

**Comment by sorrycc** [comment]
没有复现步骤帮不上你。

**Comment by cassiewang01** [comment]
就是想问father 可以打包同一个项目中 即有js文件又又ts文件的情况么？
我现在的问题是，入口文件是index.js index.js引入的是doucument/index.tsx文件，所以打包的时候出现这个问题。如果只有js文件是没有问题的。。

**Comment by dkvirus** [comment]
@sorrycc  我这边也遇到这个问题， [复现工程](https://github.com/dkvirus/umi-ts-demo)

复现步骤：
1. 安装依赖： `yarn add`；
2. 运行 `npm run start` 是可以正常启动项目的，就一个简单的页面；
3. 运行 `npm run build:cjs`，实际运行的命令是 `father-build --cjs babel`，就会报错：

``` bash
Clean dist directory
Build cjs with babel
Clean lib directory
✖  error     SyntaxError: Unexpected token } in JSON at position 335 
```

**Comment by dkvirus** [comment]
感谢 🌹，逗号去掉，确实可以打包出文件，但又发现两个问题：

- 相比用 js 生成的 umi 工程，打包速度巨慢无比，这还只是写了一个页面........；
- father 会检查 node_modules 中包类型，终端会报错，不知道这个可不可以规避掉，报错让人很虚，即便打包是成功的。

报错 node_modules/@types/vfile 变量类型问题，在 yarn.lock 中定位依赖关系为：
`@umijs/fabric > eslint-plugin-markdown > unified > vfile`。

```
// <======== 会自动检查 node_modules 中的类型检查
/temp/umi-ts-demo/node_modules/@types/vfile/index.d.ts(11,31): 
error TS7016: Could not find a declaration file for module 'vfile-message'. 
'/Users/dkvirus/Documents/tmp/temp/umi-ts-demo/node_modules/vfile-message/index.js' 
implicitly has an 'any' type. Try `npm install @types/vfile-message`
if it exists or add a new declaration (.d.ts) file containing `declare module 'vfile-message';`
```

**Comment by dkvirus** [comment]
@sorrycc  逗号去掉，**打包只会生成目录，不会生成打包文件**，终端仍会报错：

``` bash
/temp/umi-ts-demo/node_modules/@types/vfile/index.d.ts(11,31): error TS7016: Could not find a declaration file for module 
'vfile-message'. '/temp/umi-ts-demo/node_modules/vfile-message/index.js' implicitly has an 'any' type.
  Try `npm install @types/vfile-message` if it exists or add a new declaration (.d.ts) file containing `declare module 'vfile-message';`
```

报错信息字面意思 `@types/vfile-message` 这个包有问题，我尝试了它建议的两种方式，打包仍旧失败。
- `yarn add @types/vfile-message`
- `declare module 'vfile-message';`

最终发现脚手架里的 `@types/vfile-message` 版本是 1.0.1，而 [淘宝镜像网](https://npm.taobao.org/package/%40types%2Fvfile-message) 查询 `@types/vfile-message` 该包已废弃，`vfile-message` 包自身提供类型声明，最终我手动安装 `vfile-message` 最新版本(2.0.2)，打包成功。

> Stub TypeScript definitions entry for vfile-message, which provides its own types definitions

在 yarn.lock 找到依赖关系，顶层是 @umijs/fabric > eslint-plugin-markdown > unified > vfile > vfile-message。希望能从源头（@umijs/fabric）升级依赖包版本以解决该问题。

**Comment by xileliu** [comment]
> @sorrycc 逗号去掉，**打包只会生成目录，不会生成打包文件**，终端仍会报错：
> 
> ```shell
> /temp/umi-ts-demo/node_modules/@types/vfile/index.d.ts(11,31): error TS7016: Could not find a declaration file for module 
> 'vfile-message'. '/temp/umi-ts-demo/node_modules/vfile-message/index.js' implicitly has an 'any' type.
>   Try `npm install @types/vfile-message` if it exists or add a new declaration (.d.ts) file containing `declare module 'vfile-message';`
> ```
> 
> 报错信息字面意思 `@types/vfile-message` 这个包有问题，我尝试了它建议的两种方式，打包仍旧失败。
> 
> * `yarn add @types/vfile-message`
> * `declare module 'vfile-message';`
> 
> 最终发现脚手架里的 `@types/vfile-message` 版本是 1.0.1，而 [淘宝镜像网](https://npm.taobao.org/package/%40types%2Fvfile-message) 查询 `@types/vfile-message` 该包已废弃，`vfile-message` 包自身提供类型声明，最终我手动安装 `vfile-message` 最新版本(2.0.2)，打包成功。
> 
> > Stub TypeScript definitions entry for vfile-message, which provides its own types definitions
> 
> 在 yarn.lock 找到依赖关系，顶层是 @umijs/fabric > eslint-plugin-markdown > unified > vfile > vfile-message。希望能从源头（@umijs/fabric）升级依赖包版本以解决该问题。

@dkvirus 最终解决了吗？

**Comment by dkvirus** [comment]
@xileliu  我这边现在可以正常打包了。

安装的 `@types/vfile-message` 还是 1.0.1 版本，但是包含了 index.d.ts 声明文件了。

之前报错我特地去 `node_modules/@types/vfile-message` 目录下找了下，当时没有找到 index.d.ts 声明文件导致报错。

这可能不是 @umijs/fabric 依赖问题，是安装包时网络等原因导致的吧，当然，如果 @umijs/fabric 能升级下依赖包版本最好了。

**Comment by xileliu** [comment]
@dkvirus 嗯是不报错了也可以正常build成功，
yarn add @types/vfile-message -D ，在gitlib ci 执行yarn 好像不会安装这个包

**Comment by PeachScript** [comment]
father 4 已发布，可尝试升级到最新版：https://github.com/umijs/father/blob/master/docs/guide/migrate.md

旧版本不再维护，感谢支持
