### ISSUE TITLE
less打包问题求教

### ISSUE THREAD

**Issue by zjdschnappi** [umijs/father#140]
我打算封装一个插件，插件的使用需要外链css,所以需要对css打包

**Comment by zjdschnappi** [comment]
此时我在tsx里`import "../styles/cropper.less";` 然后在.fatherrc里配置了extractCSS:true.  在umd版本的文件正确的打包出来 .css文件。但是在cjs版本 里的代码 还存在 
![image](https://user-images.githubusercontent.com/15072751/67826893-11989300-fb09-11e9-86a1-f7d98db95116.png)。怎么样让这句不存在。                                               
.fatherrc
`export default {
  cjs: { type: "babel", lazy: true },
  umd: {
    name: "cropper",
  },
  disableTypeCheck: true,
  extractCSS: true
};`

**Comment by zjdschnappi** [comment]
如果在cjs版本的文件里存在`require("../styles/cropper.less")`这个的话，业务使用该插件就会将该文件打包进去，但是业务使用的是cssModule，会导致样式名被加上hash唯一标识，所以用不了。

**Comment by zjdschnappi** [comment]
业务中引了插件，因为那句 `require("../styles/cropper.less")`，就会额外打包出css,但是因为有hash值是不能用的
![image](https://user-images.githubusercontent.com/15072751/67827821-19a60200-fb0c-11e9-9ee6-826b8f92e8fc.png)

 那么这些代码就冗余了

**Comment by PeachScript** [comment]
father 4 已发布，可尝试升级到最新版：https://github.com/umijs/father/blob/master/docs/guide/migrate.md

旧版本不再维护，感谢支持
