### ISSUE TITLE
目前使用的docz版本会自动给导出的对象添加__filemeta，导致表单验证, prop-types验证等失效。

### ISSUE THREAD

**Issue by Iixianjie** [umijs/father#144]
## 重现  

在某个文件中导出对象 
![image](https://user-images.githubusercontent.com/34636376/68543020-ef4a2380-03ec-11ea-8092-7d76ba2a7d1f.png)

打印该对象，发现被添加了__filemeta, 导致propTypes验证出错
![image](https://user-images.githubusercontent.com/34636376/68543016-e0637100-03ec-11ea-8c2a-7d1cf07e5029.png)

**Comment by silentcloud** [comment]
+1

**Comment by PeachScript** [comment]
内置 docz 版本老旧，使用最新版 docz + father-build 进行研发；另外，推荐使用 dumi + father-build 进行组件库研发：https://d.umijs.org/guide/getting-started
