### ISSUE TITLE
lerna每个 package 单独配.fatherrc.js，并不会继承根目录的.fatherrc.js配置

### ISSUE THREAD

**Issue by PhunsukhWangdu** [umijs/father#145]
如题，需要通过babel-plugin-import为antd组件做按需加载，根目录配置如下

![image](https://user-images.githubusercontent.com/12094597/68641764-c76ed300-0546-11ea-98a8-6b2e8c673e57.png)

package内不加.fatherrc.js配置build后
![image](https://user-images.githubusercontent.com/12094597/68641737-b32ad600-0546-11ea-9258-3bedc5cec53e.png)

单独加上.fatherrc.js配置后再build

![image](https://user-images.githubusercontent.com/12094597/68641757-c178f200-0546-11ea-978b-e74518af5c1a.png)

**Comment by PeachScript** [comment]
father 4 已发布，可尝试升级到最新版：https://github.com/umijs/father/blob/master/docs/guide/migrate.md

旧版本不再维护，感谢支持
