### ISSUE TITLE
esm cjs 配置babel，build出来的es lib 没有文件

### ISSUE THREAD

**Issue by xileliu** [umijs/father#146]
![image](https://user-images.githubusercontent.com/13429648/68749177-c1f1b580-0638-11ea-922f-1a68326a8e0f.png)
![image](https://user-images.githubusercontent.com/13429648/68750143-61637800-063a-11ea-973e-a9c37e7eddea.png)
![image](https://user-images.githubusercontent.com/13429648/68750200-750ede80-063a-11ea-8e1f-3f5c4935bd3a.png)
![image](https://user-images.githubusercontent.com/13429648/68750229-7f30dd00-063a-11ea-803d-53994053c69f.png)

**Comment by PeachScript** [comment]
father 4 已发布，可尝试升级到最新版：https://github.com/umijs/father/blob/master/docs/guide/migrate.md

旧版本不再维护，感谢支持
