### ISSUE TITLE
father-build的rollup

### ISSUE THREAD

**Issue by ywy94ywy** [umijs/father#147]
`export default {
    esm: 'rollup',
}`
只配置这一句话，在father中可以打包成功，在father--build中会报错
![QQ截图20191113215312](https://user-images.githubusercontent.com/22499767/68769858-017fc800-0660-11ea-85d4-96aebc418256.png)

不想用father的原因主要是体积太大了，下载将近10分钟，开发初期可能频繁更新，比较耗时间。

**Comment by PeachScript** [comment]
问题还存在的话请提供一个复现 demo 便于排查。

如果前期不需要写文档，直接安装 father-build 是完全推荐的做法，storybook 和 docz 太大了；如果后期需要写文档，建议使用基于 umi 的文档方案 father-doc：https://github.com/umijs/father-doc

**Comment by XylitolLin** [comment]
father build 等于 father-build，用 father-build 的时候，执行命令应该是 father-build 而不是 father-build build
