### ISSUE TITLE
docz引用的react和react-dom地址自定义

### ISSUE THREAD

**Issue by clverpanda** [umijs/father#15]
我的开发环境连不上外网，项目里的react和react-dom引用的地址是阿里cdn的地址，开发环境连不上，希望可以自定义地址。

**Comment by clverpanda** [comment]
我会在端午节过后解决这个问题并提交PR。

@sorrycc  有一个问题请教一下，为什么当初要把react和react-dom单独拿出来？

**Comment by sorrycc** [comment]
好像是为了快一点。

**Comment by Francecil** [comment]
这个是为了使用生产版本的 react和react-dom？

**Comment by xchunzhao** [comment]
@sorrycc 有个问题请教一下。
目前我能想到的是在config里面添加
```
react: xxxx,  //  172.16.11.30/react.js
reactDom: xxxx   //  172.16.11.30/react-dom.js
```
或者
```
react-url: // 172.16.11.30
```
然后在`setConfig`去覆盖。
我觉得后者好一点。或者大佬有没有什么更好的想法。

**Comment by sorrycc** [comment]
Closed via #58
