### ISSUE TITLE
如何设置别名@指向src路径？

### ISSUE THREAD

**Issue by WangJM001** [umijs/father#150]
tsconfig.json
![image](https://user-images.githubusercontent.com/20501316/69106591-d6570780-0aa9-11ea-8279-ed4a3cd9773a.png)
使用storybook，如何配置storybook中@别名，有没有father配置能传递给storybook的webpack.config.js

**Comment by qq645381995** [comment]
同

**Comment by gebin** [comment]
我是使用了ant design pro，webpack配置中设置了@的别名，现在会出现找不到组件

**Comment by xiexingen** [comment]
强烈建议支持别名，不然层级多了写的很累

**Comment by OwnGhy** [comment]
我也遇到这个问题，配置 extraRollupPlugins使用rollup-plugin-alias也不行

**Comment by milobluebell** [comment]
@sorrycc 麻烦看下这个问题，情况基本同上。 本来使用ttsc打包就可以了，强行想用father-build，结果ts-paths alias这些就是搞不定。

**Comment by lulusir** [comment]
我这边的解决方法是用，ttsc打包出d.ts,father-build只负责js产物

**Comment by nieyao** [comment]
加1 ，没有人解决吗

**Comment by PeachScript** [comment]
father 不是基于 webpack 的，没法沿用 webpack 的 alias 配置；rollup 打包模式可以挂载 [@rollup/plugin-alias](https://www.npmjs.com/package/@rollup/plugin-alias) 实现同样功能，babel 打包模式可以看下 [babel-plugin-module-resolver](https://www.npmjs.com/package/babel-plugin-module-resolver) 能不能满足

**Comment by lq48303847** [comment]
这个问题这么久了 还没有人解决吗？    
我是用的 babel打包模式， 使用  babel-plugin-module-resolver 插件支持别名，但是也有问题， ts生成的.d文件没有转换

**Comment by cwjTerrace** [comment]
我也碰到了 没人处理吗 都2年了

> 这个问题这么久了 还没有人解决吗？ 我是用的 babel打包模式， 使用 babel-plugin-module-resolver 插件支持别名，但是也有问题， ts生成的.d文件没有转换

**Comment by yaodong5063** [comment]
> 我这边的解决方法是用，ttsc打包出d.ts,father-build只负责js产物

你好，有具体实现的吗

**Comment by fantian007** [comment]
额，我来说吧
1. js 别名处理

**Comment by fantian007** [comment]
额， 我来说吧
1. js 别名处理
babel 使用  module-resolver
rollup 使用 @rollup/plugin-alias
配置一下就行，应该坑不多

2. 生成的 d.ts 类型文件中别名处理，看我的文章 [类型文件别名处理](https://note.youdao.com/s/LDO1g7g0)

**Comment by PeachScript** [comment]
father 4 RC 支持源码产物及类型产物的 alias 转换，近期会发正式版，可以考虑先升级到 RC：https://github.com/umijs/father-next

**Comment by wozien** [comment]
mark

**Comment by jangdelong** [comment]
> 我也碰到了 没人处理吗 都2年了
> 
> > 这个问题这么久了 还没有人解决吗？ 我是用的 babel打包模式， 使用 babel-plugin-module-resolver 插件支持别名，但是也有问题， ts生成的.d文件没有转换

升级版本吧😂

**Comment by 04756** [comment]
亲测有效。老版本可通过babel-plugin-root-import解决。
extraBabelPlugins: [
        [
            'babel-plugin-root-import',
            {
                rootPathSuffix: '',
                rootPathPrefix: '@/',
            },
        ],
    ],

**Comment by fhuy** [comment]
> tsconfig.json ![image](https://user-images.githubusercontent.com/20501316/69106591-d6570780-0aa9-11ea-8279-ed4a3cd9773a.png) 使用storybook，如何配置storybook中@别名，有没有father配置能传递给storybook的webpack.config.js

按照这上面的配置，Umi 4.x 已经解决@路径配置问题了
