### ISSUE TITLE
doc build后无样式

### ISSUE THREAD

**Issue by long-zhuge** [umijs/father#156]
#### father 版本
> 2.28.0

#### 描述
> doc dev启动的页面正常，能正常的引用到样式。npm publish也是正常的，项目中引用也正常。但是 doc build 后的css文件中不存在组件自定义的样式，导致使用 github page 时无样式。

#### 项目地址
[LinkBtn](https://github.com/long-zhuge/td-antd/tree/master/src/linkBtn)

#### 对比图
![image](https://user-images.githubusercontent.com/14194437/69692323-9b3d7f80-110c-11ea-8bc6-0a4e4bc1bf72.png)

#### .fatherrc.js

```
export default {
  esm: 'rollup',
  cjs: 'rollup',
  umd: false,
  doc: {
    // repository: false,
    themeConfig: {
      // mode: 'dark',
      // showPlaygroundEditor: false
    },
    base: '/td-antd/',
  },
}
```

**Comment by AimLuo** [comment]
话说默认主题的themeConfig文档在哪，我怎么没找到。在docz也没有。

**Comment by xgs925** [comment]
我也是doc dev后无样式

**Comment by AimLuo** [comment]
umijs/father 的docz还是1.2.0
![image](https://user-images.githubusercontent.com/21124342/70218690-6cfc1780-177e-11ea-8175-3bf6d4d9abfe.png)

**Comment by long-zhuge** [comment]
> umijs/father 的docz还是1.2.0
> ![image](https://user-images.githubusercontent.com/21124342/70219801-6bcbea00-1780-11ea-9b4a-267e79f51361.png)
> 手动升级也不行，看来是主题插件的原因
> 可以看下插件文档
> [docz-plugin-css](https://www.npmjs.com/package/docz-plugin-umi-css)
> 和
> [docz-theme-umi](https://www.npmjs.com/package/docz-theme-umi)

有解决方案吗？还是我配置的有问题？如果使用 module.less 的方式，doc build就没问题，但是发布的 npm 包会引不到样式。

**Comment by AimLuo** [comment]
> > umijs/father 的docz还是1.2.0
> > ![image](https://user-images.githubusercontent.com/21124342/70219801-6bcbea00-1780-11ea-9b4a-267e79f51361.png)
> > 手动升级也不行，看来是主题插件的原因
> > 可以看下插件文档
> > [docz-plugin-css](https://www.npmjs.com/package/docz-plugin-umi-css)
> > 和
> > [docz-theme-umi](https://www.npmjs.com/package/docz-theme-umi)
> 
> 有解决方案吗？还是我配置的有问题？如果使用 module.less 的方式，doc build就没问题，但是发布的 npm 包会引不到样式。

没有，还有菜单分组也用不了。。

**Comment by AimLuo** [comment]
我换了docz-theme-ztopia了。你试试这个主题。docz-them-umi再去修改得不偿失。
安装`docz-theme-ztopi`
```json
"docz-theme-ztopia": "^0.1.3",
```
.fatherrc
```javascript
{
doc:{
    theme: 'docz-theme-ztopia',
  }
}
```

看样子umi准备用[father-doc](https://github.com/umijs/father-doc)来做文档了，现在在维护。

**Comment by long-zhuge** [comment]
@AimLuo 把 package.json 的 "sideEffects": false 去掉，一切就正常了。

**Comment by TomJerryTheHandsome** [comment]
> 我也是doc dev后无样式

请问doc dev后无样式怎样解决的
