### ISSUE TITLE
father build --watch error

### ISSUE THREAD

**Issue by focus7eleven** [umijs/father#158]
复现 repo：https://github.com/focus7eleven/father-lerna-demo.git

复现步骤：
1. yarn run init
2. yarn build --watch

![image](https://user-images.githubusercontent.com/8576839/69859346-f0c18a00-12ce-11ea-8fb0-92639d79a951.png)

yarn build 是正常的，watch 会报错，看上去和 https://github.com/umijs/father/issues/97 这个很像，但加上 disableTypeCheck 之后依旧报错。

另外，yarn start 会报另外一个错：

![image](https://user-images.githubusercontent.com/8576839/69859515-4302ab00-12cf-11ea-8531-75a51834cc7f.png)

**Comment by sorrycc** [comment]
要做两件事才能解决这个问题，

1. https://github.com/ezolenko/rollup-plugin-typescript2/pull/197
1. rollup 的 babel 配置设置 typescript: true
