### ISSUE TITLE
Jest test: ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by shaodahong** [umijs/father#160]
Jest test use `async` throw error`ReferenceError: regeneratorRuntime is not defined`

```js
it('test', async () => {})
```

**Comment by AimLuo** [comment]
。。

**Comment by crazyair** [comment]
同

**Comment by PeachScript** [comment]
father 4 已发布，可尝试升级到最新版：https://github.com/umijs/father/blob/master/docs/guide/migrate.md

旧版本不再维护，感谢支持
