### ISSUE TITLE
lerna项目中tsconfig.json和typings.d.ts不能继承根目录的

### ISSUE THREAD

**Issue by AimLuo** [umijs/father#163]
### 报错：
无tsconfig.json,报错如下：
![image](https://user-images.githubusercontent.com/21124342/70030242-c1b75b00-15e3-11ea-818b-45c004bf51b9.png)
无typings.d.ts，报错提示css这些后缀问题，
### 解决
tsconfig.json只能复制一份，
typings.d.ts可以引用
```js
import '../../typings';

```

**Comment by PeachScript** [comment]
father 4 已发布，可尝试升级到最新版：https://github.com/umijs/father/blob/master/docs/guide/migrate.md

旧版本不再维护，感谢支持
