### ISSUE TITLE
打包的时候将require的svg图片全都转成base64编码打进去怎么配置？

### ISSUE THREAD

**Issue by guozhaolong** [umijs/father#164]
如果我用chainWebpack配置的话，可以写成
```
config.module.rule('svg')
      .use('url-loader')
      .loader('url-loader')
      .tap(options => {
        return merge(options, {
          limit: 10000 // default 10k
        })
      })
      .end();
```

**Comment by suptwo** [comment]
+1 我也有这个问题 1.x KB的图片没有打包成 base64

**Comment by PeachScript** [comment]
father 基于 babel 和 rollup，可以使用所属生态的 plugin 实现，比如：
- babel-plugin-file-loader：https://www.npmjs.com/package/babel-plugin-file-loader
- @rollup/plugin-url：https://github.com/rollup/plugins/tree/master/packages/url

**Comment by h476564406** [comment]
tnpm i --save-dev rollup-plugin-url
.fatherrc.js

import url from 'rollup-plugin-url';

 
extraRollupPlugins: [url({
    limit: 10 * 1024,
    emitFiles: true
  })]

**Comment by SmartWrh** [comment]
> tnpm i --save-dev rollup-plugin-url
> .fatherrc.js
> 
> import url from 'rollup-plugin-url';
> 
> extraRollupPlugins: [url({
> limit: 10 * 1024,
> emitFiles: true
> })]

```
const options: IBundleOptions = {
  cjs: 'rollup',
  esm: 'rollup',
  // @ts-ignore
  doc: { typescript: true },
  extraRollupPlugins: [url({ limit: 100000 * 3, emitFiles: true, })],
};
```
不起作用，可以帮忙指点下嘛

**Comment by NsNe** [comment]
动态导入的图片无法被 `babel-plugin-file-loader` 打包，有啥解决方法吗
![image](https://user-images.githubusercontent.com/25630824/99339796-c1ca6c80-28c1-11eb-8523-2a2a7d2671c5.png)

**Comment by dongcer** [comment]
> tnpm i --save-dev rollup-plugin-url .fatherrc.js
> 
> import url from 'rollup-plugin-url';
> 
> extraRollupPlugins: [url({ limit: 10 * 1024, emitFiles: true })]

兄弟这样不行啊

**Comment by dongcer** [comment]
> father 基于 babel 和 rollup，可以使用所属生态的 plugin 实现，比如：
> 
> * babel-plugin-file-loader：https://www.npmjs.com/package/babel-plugin-file-loader
> * @rollup/plugin-url：https://github.com/rollup/plugins/tree/master/packages/url

兄弟这块有例子适用于less里的url嘛

**Comment by jingkeke** [comment]
> > tnpm i --save-dev rollup-plugin-url .fatherrc.js
> > import url from 'rollup-plugin-url';
> > extraRollupPlugins: [url({ limit: 10 * 1024, emitFiles: true })]
> 
> 兄弟这样不行啊

@rollup/plugin-url  我改用这个可以

**Comment by Zoro916** [comment]
> 

我改用@rollup/plugin-url也依旧不行，可否贴一下版本号？

**Comment by Zoro916** [comment]
> > > tnpm i --save-dev rollup-plugin-url .fatherrc.js
> > > import url from 'rollup-plugin-url';
> > > extraRollupPlugins: [url({ limit: 10 * 1024, emitFiles: true })]
> > 
> > 
> > 兄弟这样不行啊
> 
> @rollup/plugin-url 我改用这个可以

我改用@rollup/plugin-url也依旧不行，可否贴一下版本号？

**Comment by h476564406** [comment]
已经收到。

**Comment by Zoro916** [comment]
![image](https://user-images.githubusercontent.com/22720359/149487308-b4d55fc5-bb47-4f70-93ad-0a9d9e20e577.png)

追溯了一下father-build源码，分析原因可能在于这里。

实际上getRollupConfig.ts已经引用了url()插件，而通过extraRollupPlugins追加的url({ limit: 10 * 1024, emitFiles: true })插件并不会对原本引入的url()插件进行覆盖，所以导致传入的配置参数不生效。

**Comment by iamwjj** [comment]
@Zoro916 最新版本我试了还是不行。。

**Comment by h476564406** [comment]
已经收到。

**Comment by LeiYao123** [comment]
@PeachScript 最新版的 father 已经没了 `extraRollupPlugins` 这个，并且 `babel-plugin-file-loader` 并不能将图片转换为 base64，请问我现在要怎么做才能使用 father 把引用到的 png图片转换成 base64 而不是直接文件引用

**Comment by h476564406** [comment]
已经收到。

**Comment by huarse** [comment]
> @PeachScript 最新版的 father 已经没了 `extraRollupPlugins` 这个，并且 `babel-plugin-file-loader` 并不能将图片转换为 base64，请问我现在要怎么做才能使用 father 把引用到的 png图片转换成 base64 而不是直接文件引用

同问

**Comment by PeachScript** [comment]
father 4 只有 bundle 模式（即 umd 打包）能打图片，chainWebpack 修改 url-loader 配置，把 limit 参数调大即可，具体参考 webpack 及 webpack-chain 文档

**Comment by Atw-Lee** [comment]
father4
less文件，相对路径引入的图片打包成base64
chainWebpack: (memo) => {
      memo.module
        .rule('file')
        .test(/\.(png|jpg|gif)$/i)
        .type('asset')
        .parser({
          dataUrlCondition: {
            maxSize: 40 * 1024,
          },
        })
        .end();
      return memo;
    },

**Comment by h476564406** [comment]
已经收到。
