### ISSUE TITLE
father build 怎么指定生成文件目录位置

### ISSUE THREAD

**Issue by guccihuiyuan** [umijs/father#165]
直接使用 father build 默认的文件路径是在根路径下的dist目录，我怎么指定生成在其他目录？

**Comment by guccihuiyuan** [comment]
或者怎么使用文档上说的使用 lerna 管理 多个包？没有详细的文档进行说明

**Comment by AimLuo** [comment]
lerna使用
https://github.com/AimLuo/monorepo-manage

**Comment by sorrycc** [comment]
> 文件路径是在根路径下的dist目录，我怎么指定生成在其他目录？

不能修改。

> 怎么使用文档上说的使用 lerna 管理 多个包？

有很多示例，比如 https://github.com/umijs/father-doc
