### ISSUE TITLE
extraRollupPlugins 中的 rollup-plugin-web-worker-loader问题

### ISSUE THREAD

**Issue by luchaoqun125** [umijs/father#170]
配置如下：
`import webWorkerLoader from 'rollup-plugin-web-worker-loader';

export default {
  cjs: 'rollup',
  esm: 'rollup',
  runtimeHelpers: true,
  extraRollupPlugins: [
    webWorkerLoader()
  ]
}`

web-worker链接地址：https://www.npmjs.com/package/rollup-plugin-web-worker-loader

![image](https://user-images.githubusercontent.com/19883840/70519545-13795b80-1b77-11ea-9ff3-79df221419df.png)

在rollup中配置没问题，在umi中有问题报错。

**Comment by PeachScript** [comment]
`father v2.29.2` 使用 `create-umi` 的 library 脚手架没能复现，此问题是否还存在？
