### ISSUE TITLE
打包发布后，less文件的样式丢失

### ISSUE THREAD

**Issue by guccihuiyuan** [umijs/father#171]
father build 打包发布后，less文件的样式丢失，请问下怎么解决呢？

**Comment by icodytan** [comment]
package.json 文件是否存在 sideEffects

**Comment by long-zhuge** [comment]
@guccihuiyuan 请问你解决这个问题了吗？怎么处理呀

**Comment by johnsmithsren** [comment]
我的情况是，开发时候添加的自定义组件样式都是正常的，但是一旦发布到npm之后，项目install之后，自定义样式会出现丢失，一开始看到大家说要加sideEffect，几番尝试无效，后来在package 中删除sideeffect ，发现可以了，如果后续有人实在解决不了，可以参考这个试试，

fatherrc.ts

export default {
  esm: 'babel',
  lessInBabelMode: true,
};

umirc.ts

import { defineConfig } from 'dumi';
export default defineConfig({
  title: '组件',
  favicon: '/images/logo-light.png',
  logo: '/images/logo-light.png',
  outputPath: 'docs-dist',
  mfsu: {},
  webpack5: {},
  dynamicImport: {},
  extraBabelPlugins: [
    [
      'babel-plugin-import',
      {
        libraryName: 'antd',
        libraryDirectory: 'es',
        style: true,
      },
    ],
  ],
});




组件内部引用

import './style.less';



tsconfig


{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "jsx": "react",
    "esModuleInterop": true,
    "strict": true,
    "skipLibCheck": true,
    "declaration": true,
    "sourceMap": true,
    "baseUrl": "./",
    "paths": {
      "@/*": [
        "src/*"
      ],
      "@@/*": [
        "src/.umi/*"
      ]
    },
    "allowSyntheticDefaultImports": true
  },
  "exclude": [
    "node_modules",
    "**/__test__",
    "test",
    "tests",
    "docs"
  ]
}
