### ISSUE TITLE
storybook 模式下，无法调试node_modules内的代码

### ISSUE THREAD

**Issue by gyh9457** [umijs/father#172]
现象：
1. 执行命令 `father doc dev --storybook` 启动调试
2. 修改 node_modules 内的某个包源码 ，没有热更新的效果。（已确定修改的是被引用的代码，重新启动服务后有生效）

期望：
1. 修改 node_modules 内的代码能实时更新，方便调试。

其他：
不知道是不是因为性能的原因不进行实时更新？

**Comment by sorrycc** [comment]
这是 storybook 的问题。

**Comment by gyh9457** [comment]
https://github.com/storybookjs/storybook/issues/9134
