### ISSUE TITLE
externalsExclude不生效

### ISSUE THREAD

**Issue by gebin** [umijs/father#173]
```
export default {
    esm: "rollup",
    externalsExclude:['css3transform'],
    doc: {
        title: '组件文档',
        files: ['src/**/*.mdx']
    }
}
```
因为cjs 和 esm 格式打包方式选 rollup 时有个约定，dependencies 和 peerDependencies 里的内容会被 external。

我希望打包的时候css3transform（是一个node包）可以被打包到dist中，找到了externalsExclude，结果打包结果还是不存在css3transform？

**Comment by sorrycc** [comment]
> 我希望打包的时候css3transform（是一个node包）可以被打包到dist中

css3transform 放 devDependencies。

**Comment by gebin** [comment]
> > 我希望打包的时候css3transform（是一个node包）可以被打包到dist中
> 
> css3transform 放 devDependencies。

还是不能讲css3transform打包到代码中。

为什么会考虑将css3transform 放 devDependencies，devDependencies不是应该是放辅助编译的包吗，我是希望把css3transform打包到代码中的。

**Comment by gebin** [comment]
一开始使用 `import Transform from 'css3transform';` 会出现下面的报错信息
`Error: 'default' is not exported by node_modules/css3transform/dist/css3transform.js `，所以改用了`let Transform = require("css3transform");`，不知道是否跟这里有关系？

**Comment by sorrycc** [comment]
> 我是希望把css3transform打包到代码中的

打包到代码里就不需要放 dependencies 里了。

**Comment by gebin** [comment]
> > 我是希望把css3transform打包到代码中的
> 
> 打包到代码里就不需要放 dependencies 里了。

esm打包尝试很多次，还是不行，先用umd打包了。
