### ISSUE TITLE
当组件开发到30个以上时，编译变长，热更新变慢

### ISSUE THREAD

**Issue by johanazhu** [umijs/father#179]
版本：
    "umi": "^2.6.0",
    "umi-library": "^1.0.1",
    "umi-plugin-library": "^1.1.9",
前期还好，后面开发到30个以上的组件时，热更新变慢不说，每次刷新页面就要编译很久（5分钟）才能呈现页面，影响开发效率

**Comment by AimLuo** [comment]
我会另外开页面来开发调试，一般我只用到`father build`，

**Comment by johanazhu** [comment]
对，等umi 的文档功能完善了，就用umi的，docz的体验不是很好

**Comment by PeachScript** [comment]
可以上车 dumi 了，快到怀疑人生，该 issue 关闭 :P
