### ISSUE TITLE
how to debug

### ISSUE THREAD

**Issue by KMBaby-zyl** [umijs/father#183]
father.rc
```
export default {
  esm: 'rollup',
  cjs: 'rollup',
  entry: '/index.tsx',
}
```

开发环境father doc dev后， 代码无法debug，缺少sourcemap

**Comment by sorrycc** [comment]
doc dev 现在走的是 docz，具体怎么调试得看下 docz 的实现。

**Comment by AimLuo** [comment]
docz仅仅用来快速生成文档而已，想要调试还得另开页面。个人用`umi dev`搞定。

**Comment by PeachScript** [comment]
@KMBaby-zyl @AimLuo 推荐两位使用 father-doc 进行文档编写和组件调试，内核就是 umi，目前尚在 alpha 阶段，未来会作为 father 组件开发的官方文档方案，欢迎一起建设：https://github.com/umijs/father-doc

**Comment by AimLuo** [comment]
> @KMBaby-zyl @AimLuo 推荐两位使用 father-doc 进行文档编写和组件调试，内核就是 umi，目前尚在 alpha 阶段，未来会作为 father 组件开发的官方文档方案，欢迎一起建设：https://github.com/umijs/father-doc

今天早上刚确定将文档迁移到father-doc👍
