### ISSUE TITLE
disableTypeCheck设置为false时build出错

### ISSUE THREAD

**Issue by lxfu** [umijs/father#185]
library: {
    esm: 'babel',
    cjs: 'babel',
    disableTypeCheck: false,
}
<img width="954" alt="231D0C1E-DBD2-40D4-9F7F-1055FC0872DF" src="https://user-images.githubusercontent.com/20291784/71638722-98512400-2ca2-11ea-9440-34f76338ac24.png">

**Comment by PeachScript** [comment]
@lxfu 这个问题是否有新进展？
