### ISSUE TITLE
node-pty编译失败

### ISSUE THREAD

**Issue by AimLuo** [umijs/father#188]
- 环境：window10 最新版
- 解决： npm install --global --production windows-build-tools [来源](https://github.com/microsoft/node-pty#windows)
- 疑问：使用windows-build-tools安装的python版本是2.8的，自己装的3.8的版本，node-pty根本获取不到，难道node-pty只能用2.8版？？文档也没看到啊。

**Comment by PeachScript** [comment]
father 4 已发布，可尝试升级到最新版：https://github.com/umijs/father/blob/master/docs/guide/migrate.md

旧版本不再维护，感谢支持
