### ISSUE TITLE
docz版本太低啦！

### ISSUE THREAD

**Issue by ywy94ywy** [umijs/father#191]
docz版本太低了
<Props of=<C>> 显示ts不知道为什么没法显示组件的接口属性了。
另外，我该怎么在father里集成father-doc，也就是文件后缀都是md格式的了

**Comment by ywy94ywy** [comment]
通过yarn create umi，
选择library后，
再安装father-doc，
运行 father-doc dev后会报错
`
Module build failed (from ./node_modules/umi-plugin-father-doc/lib/loader/index.js):
TypeError: unknown: Cannot read property 'replace' of undefined
`

**Comment by a992681784** [comment]
同样遇到<Props of=> 没法显示组件的接口属性了。

**Comment by jianfei** [comment]
这个问题现在有什么解决方案吗?

**Comment by caperso** [comment]
我也是, 体验了两天不想再填坑了, 不用了

**Comment by PeachScript** [comment]
强烈推荐使用 dumi 进行组件开发和文档编写，非常好用（注：目前还没有类似 PropsOf 的功能）： https://d.umijs.org

如果想保持使用 docz，建议使用自装 docz + father-build 的组合来使用最新的 docz 版本，father 本身也只是做了一层配置透传；且未来 3.x 的 father 会变成纯粹的打包工具不含任何文档套件，届时 dumi 会以插件形式变成官方推荐的方案，所以再次强烈推荐使用 dumi

此 issue 先关闭了
