### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by crazyair** [umijs/father#193]
具体问题在 
https://github.com/ant-design/ant-design/issues/21262

我也不清楚到底是哪里的问题。

**Comment by PeachScript** [comment]
@crazyair 启用 `runtimeHelpers` 了吗

**Comment by crazyair** [comment]
没有启用

**Comment by crazyair** [comment]
这个问题估计是 antdv4 form 的事情。

**Comment by PeachScript** [comment]
可以启用试试看，这个配置会把 helper 方法变成从 babel/runtime 中引入

**Comment by crazyair** [comment]
改用 father-doc 了，这个嫌弃了。。。

**Comment by PeachScript** [comment]
哈，欢迎切换到 father-doc，但这个是 father doc 命令出的问题吗？我理解应该是 father build 构建出的包不对？

**Comment by crazyair** [comment]
https://codesandbox.io/s/father-antd-demo-evrt1 

这个是加了 runtime 的 0.0.4 版本，还报错

**Comment by PeachScript** [comment]
是 father-antd-demo 这个库的 module 配置引起的，见 [antd#21262#comment](https://github.com/ant-design/ant-design/issues/21262#issuecomment-585756271)，issue 先关闭了

**Comment by PeachScript** [comment]
话说这个 issue 和 antd 的 issue 的关联是？我在 demo 中只看到了 getInputClassName 的错误

**Comment by crazyair** [comment]
两个问题，现在是页面直接报错，之前开  issue 的时候是 input 文本框改变值的时候报 regeneratorRuntime，[这里都有说](https://github.com/ant-design/ant-design/issues/21262)

**Comment by PeachScript** [comment]
了解了，regeneratorRuntimie 是 rc-input 抛出来的，后来配置上 `runtimeHelpers` 这个重新打包发版问题没有了，目前还剩下 `getInputClassName` 这个，那这边就先关闭了

**Comment by nicolo-ribaudo** [comment]
Hi! We just found a problem which might be the same as this one: https://github.com/dvajs/dva/issues/2493 It looks like the `runtimeHelpers` option is always ignored when compiling to CJS, so `regeneratorRuntime` is not defined.
