### ISSUE TITLE
之前用umi-library，这个星期升级为father后，报滑动的错误

### ISSUE THREAD

**Issue by johanazhu** [umijs/father#198]
错误代码：scrollama error: step elements cannot be children of a scrollable element. Remove any css on the parent element with overflow: scroll; or overflow: auto; on elements with fixed height. <body>​…​</body>
ant-design中也有人问道这个问题，好像还没解决
https://github.com/ant-design/ant-design/issues/20062​

**Comment by PeachScript** [comment]
father 4 已发布，可尝试升级到最新版：https://github.com/umijs/father/blob/master/docs/guide/migrate.md

旧版本不再维护，感谢支持

**Comment by johanazhu** [comment]
阿里嘎多
