### ISSUE TITLE
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten

### ISSUE THREAD

**Issue by kakariko-village** [umijs/father#206]
I got this error message when run "father build":

"The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten"

## Context

- **Father Version**: 2.29.2
- **Node Version**: 12.16.1
- **Platform**: MAC OS Catalina 10.15.4

**Comment by zhangfu-git** [comment]
same problem, import @ant-design/icon
![image](https://user-images.githubusercontent.com/19772048/79213645-1ca76b80-7e7c-11ea-8176-3765509b4496.png)

**Comment by caozihao** [comment]
经过测试，用require就行了，比如：
const { PlusCircleFilled } = require('@ant-design/icons');

**Comment by Topgt** [comment]
同样的问题 导入immutable.js 


Build cjs with rollup
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
Error when using sourcemap for reporting an error: Can't resolve original location of error.
✖  error     Error: 'OrderedSet' is not exported by node_modules/_immutable@3.8.2@immutable/dist/immutable.js 
    at error (/Users/lambda/code/my-draft-js/node_modules/_rollup@1.27.8@rollup/dist/rollup.js:5363:30)

**Comment by afc163** [comment]
@Topgt +1

**Comment by LJJCherry** [comment]
how to fix ?

**Comment by leerle** [comment]
how to fix ?

**Comment by xiaohuoni** [comment]
https://rollupjs.org/guide/en/#error-this-is-undefined

**Comment by PeachScript** [comment]
father 4 已发布，可尝试升级到最新版：https://github.com/umijs/father/blob/master/docs/guide/migrate.md

旧版本不再维护，感谢支持
