### ISSUE TITLE
React-Hot-Loader: react-🔥-dom patch is not detected. React 16.6+ features may not work.

### ISSUE THREAD

**Issue by chiaweilee** [umijs/father#207]
## What happens?

`React-Hot-Loader: react-🔥-dom patch is not detected. React 16.6+ features may not work.`

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

https://codesandbox.io/s/quizzical-silence-dgokn

## How To Reproduce

**Steps to reproduce the behavior:** 
1. `npm install`
2. `father doc dev`

## Context

- **Father Version**: 2.29.2
- **React Version**: 16.13.0
- **Node Version**: 12.16.1 & 12.14.x
- **Platform**: Mac OS x 2

**Comment by PeachScript** [comment]
Thanks for your detailed feedback!

The built-in docz is very legacy, so it may have many problems, and father 3.x is coming soon, will exclude `father doc` part and focus on bundle.

For now, it is recommended that use `dumi` as the doc & dev tool, and use `father-build` to bundle library, you can simply start via `tnpx @umijs/create-dumi-lib`, more documentation here (but no English version currently...): https://d.umijs.org/guide/getting-started
