### ISSUE TITLE
mac系统father build babel模式下生成没有文件出来

### ISSUE THREAD

**Issue by gao525280067** [umijs/father#208]
Build cjs with babel
Clean lib directory
Build esm with babel
Clean es directory

**Comment by PeachScript** [comment]
如何复现？

**Comment by 7kms** [comment]
有可能是文件没有匹配上

```js
  const babelTransformRegexp = disableTypeCheck ? /\.(t|j)sx?$/ : /\.jsx?$/;
```
`disableTypeCheck`设置为`false`只匹配`jsx?`文件.   要设置为`true`才能都匹配. 
没看懂这里为什么要这样做.

**Comment by ifiknew** [comment]
> 有可能是文件没有匹配上
> 
> ```js
>   const babelTransformRegexp = disableTypeCheck ? /\.(t|j)sx?$/ : /\.jsx?$/;
> ```
> 
> `disableTypeCheck`设置为`false`只匹配`jsx?`文件. 要设置为`true`才能都匹配.
> 没看懂这里为什么要这样做.

为什么要这样匹配呢 @PeachScript

**Comment by PeachScript** [comment]
启用类型检查的情况下，gulp-ts 会预先把 tsx 编译为 jsx

**Comment by jiaolongshenme** [comment]
我也遇见这个问题了
```
export default {
  cjs: {
    type: 'babel',
    minify: true,
    lazy: true,
  },
  esm: 'babel',
  extraExternals: [
    'react',
    'react-dom',
    /^@babel\/runtime/,
  ],
  extraBabelPlugins: [
    [
      'import',
      {
        libraryName: 'antd',
        libraryDirectory: 'es',
        style: 'css',
      },
    ],
  ],
  disableTypeCheck: true,
  runtimeHelpers: true,
}
```
当disableTypeCheck 为false 时不会将 src下ts文件打包到es lib 下的相应文件下；为true 就会出现js 文件

**Comment by jiaolongshenme** [comment]
@PeachScript

**Comment by jiaolongshenme** [comment]
我用的是dumi 里自带的 father-build

**Comment by PeachScript** [comment]
请提供最小可复现仓库

**Comment by jiaolongshenme** [comment]
https://gitee.com/uixepm/dumi.git @PeachScript 可改变.fatherrc.ts中disableTypeCheck的值分别打包yarn build 我的机器是
![image](https://user-images.githubusercontent.com/22339560/123910088-88f08b00-d9ac-11eb-8cbb-2a4829713a0c.png)

**Comment by jiaolongshenme** [comment]
https://gitee.com/uixepm/dumi.git @PeachScript 可改变.fatherrc.ts中disableTypeCheck的值分别打包yarn build 我的机器是
![image](https://user-images.githubusercontent.com/22339560/123910088-88f08b00-d9ac-11eb-8cbb-2a4829713a0c.png)

**Comment by jiaolongshenme** [comment]
有大佬解答下困惑吗

**Comment by PeachScript** [comment]
father 4 已发布，可尝试升级到最新版：https://github.com/umijs/father/blob/master/docs/guide/migrate.md

旧版本不再维护，感谢支持
