### ISSUE TITLE
Namespace '"vfile-message"' has no exported member 'VFileMessage'.

### ISSUE THREAD

**Issue by yedegesong** [umijs/father#209]
配置babel 打包

@types/vfile-message

Namespace '"vfile-message"' has no exported member 'VFileMessage'.

export default {
  esm: 'babel',
  cjs: 'babel',
};

**Comment by hnsylitao** [comment]
碰到相同的问题，babel 打包总是遇到问题

**Comment by Mr-jiangzhiguo** [comment]
我遇到了这个问题，我看了下 `node_moduels` 下的依赖

`vfile-message` 是 v1 版本的，而 `@types/vfile-message` 是v2版本的

`vfile-message` v1 没提供 ts声明文件，所以需要 安装 `@types/vfile-message` v1版本的

`vfile-message` v2 自身提供了ts声明文件，所以 `@types/vfile-message` v2 去掉了 声明
，也就不起作用了

究其原因 是版本的问题

### 解决方案：

```sh
$ yarn add -P vfile-message
```

**Comment by hnsylitao** [comment]
建议开发暂时配置tsconfig
```json
skipLibCheck: true
```
