### ISSUE TITLE
使用father-build打包svg遇到的问题

### ISSUE THREAD

**Issue by Lpmvb** [umijs/father#211]
## What happens?

![image](https://user-images.githubusercontent.com/34727913/79336210-e807e280-7f55-11ea-9115-f1c732cb82aa.png)

## Mini Showcase Repository(REQUIRED)

https://github.com/Lpmvb/icon

## Context

- **Father Version**: ^1.17.2
- **Node Version**: v12.16.1
- **Platform**: Mac OS

**Comment by leftstick** [comment]
你用的rollup插件`@svgr/rollup`不行。试这个：

```
yarn add @svgr/webpack babel-plugin-inline-react-svg babel-plugin-named-asset-import 
```

然后修改 `.fatherrc.ts`

```typescript

export default {
  esm: 'rollup',
  cjs: 'rollup',
  extraBabelPlugins: ['inline-react-svg', [
    require.resolve('babel-plugin-named-asset-import'),
    {
      loaderMap: {
        svg: {
          ReactComponent: `${require.resolve(
            '@svgr/webpack',
          )}?-svgo,+titleProp,+ref![path]`,
        },
      },
    },
  ]]
};
```

最后，`yarn build` 一下看看，是不是ok了?

**Comment by Lpmvb** [comment]
@leftstick  thx, 问题已解决。顺便问一下，这是什么原理那？是 father 打包过程中用到了 webpack ？如果是的话插件是自动引入？（ps: 感觉并不是这样）

**Comment by leftstick** [comment]
感觉和`@umijs/preset-react`有关，涉及 svg引入的配置似乎已经有了，就差一个依赖。。。。

我认为，dumi 这个部分应该优化一下。。。

**Comment by Lpmvb** [comment]
> 感觉和`@umijs/preset-react`有关，涉及 svg引入的配置似乎已经有了，就差一个依赖。。。。
> 
> 我认为，dumi 这个部分应该优化一下。。。

https://github.com/umijs/father/blob/804f2c720e678ead6eb4ef418c148c47ffac93b8/packages/father-build/src/getRollupConfig.ts#L16
原来本来就是支持的。。。
