### ISSUE TITLE
father build无法打包babel-plugin-react-directives

### ISSUE THREAD

**Issue by movemoving** [umijs/father#213]
react使用babel-plugin-react-directives使用类似v-if功能
示例如下：
       <p r-if={main.invoiceInfo.baseInfo.jxxlx === 1)></p>
使用father build打包，r-if没有被编译解析
![image](https://user-images.githubusercontent.com/13317571/79433503-c6633580-7fff-11ea-9c1e-a18225e6fa2f.png)
.fatherrc.js配置如下
export default {
    entry: "src/index.ts",
    esm: "babel",
    disableTypeCheck: false,
    extraBabelPlugins: [
        [
            'react-directives',
            {
                prefix: 'r',
                pragmaType: 'hooks'
            }
        ],
        ['import', { libraryName: 'antd', libraryDirectory: 'es', style: true }]
    ]
};

**Comment by PeachScript** [comment]
father 4 已发布，可尝试升级到最新版：https://github.com/umijs/father/blob/master/docs/guide/migrate.md

旧版本不再维护，感谢支持
