### ISSUE TITLE
ts build报错，疑似d.ts文件未生效

### ISSUE THREAD

**Issue by NexxLuo** [umijs/father#217]
## What happens?

1. 配置了tsconfig.json文件，如下：
```javascript
{
    "compilerOptions": {
        "rootDir": "./",
        "baseUrl": "./",
        "jsx": "react",
        "target": "esnext",
        "module": "esnext",
        "moduleResolution": "node",
        "importHelpers": true,
        "sourceMap": true,
        "esModuleInterop": true,
        "noImplicitAny": true,
        "noEmitOnError": true,
        "strictNullChecks": true,
        "resolveJsonModule": true,
        "experimentalDecorators": true,
        "strictPropertyInitialization": false,
        "allowSyntheticDefaultImports": true,
        "skipLibCheck": true,
        "noUnusedLocals": false
    },
    "exclude": ["node_modules", "public"],
    "include": ["src", "typings.d.ts"]
}

```
2. typings.d,ts文件如下：
```javascript
declare module '*.png'
declare module "reactcss" {
    export default function (p: any): any;
}
```

3. 在d.ts文件中进行了declare后，vscode不再有ts错误提示，但是father build报错
代码如下：
```javascript
import React from 'react'
import testImg from './img.png'
import reactCSS from 'reactcss'

export default function() {
  let s: any = reactCSS({
    default: {
      wrapper: {
        display: 'block',
      },
    },
  })
  return (
    <div style={s.wrapper}>
      <img src={testImg}></img> <div>hello word</div>
    </div>
  )
}
```

4.报错如下：

![QQ图片20200506153442](https://user-images.githubusercontent.com/18549980/81148596-2883da80-8faf-11ea-906d-2835b8efcf8d.png)

5. 复现库：
 
[umi-ts.zip](https://github.com/umijs/father/files/4585329/umi-ts.zip)

## Context

- **Father Version**: 1.18.0
- **Node Version**: 10.15.3
- **Platform**: windows 10，cmd

**Comment by Mr-jiangzhiguo** [comment]
试试 disableTypeCheck: true,

```ts
// fatherrc.ts
export default {
    ...
    disableTypeCheck: true,
    ...
}
```

**Comment by aweiu** [comment]
> 试试 disableTypeCheck: true,
> 
> ```ts
> // fatherrc.ts
> export default {
>     ...
>     disableTypeCheck: true,
>     ...
> }
> ```

这样有点一刀切了。。试试 https://github.com/umijs/father/issues/48#issuecomment-730857244

**Comment by daolou** [comment]
## [临时方案](https://github.com/umijs/father/issues/227)

## [demo](https://github.com/jsany/lean/blob/master/tsconfig.json#L18)
