### ISSUE TITLE
es与lib下没有生成 d.ts

### ISSUE THREAD

**Issue by git-lt** [umijs/father#219]
## What happens?

tsx 组件打包，es 与 lib 下面没有生成 d.ts 类型声明文件，只有 dist 目录下生成的 d.ts;

## 最小可复现仓库
![image](https://user-images.githubusercontent.com/8443758/81890528-c2afd800-95d8-11ea-8728-65d98252c7fc.png)

## 复现步骤，错误日志以及相关配置
fatherrc的配置
```ts
  esm: 'babel',
  cjs: 'babel',
  umd: {
    name: 'rui',
    sourcemap: true,
    globals: {
      react: 'React',
      antd: 'antd',
    },
  },
```

## 相关环境信息

- **Father 版本**：2.29.3
- **Node 版本**：10.x
- **操作系统**：mac

**Comment by Mr-jiangzhiguo** [comment]
我分析到原因了，你可以看看：https://github.com/umijs/father/issues/218#issuecomment-629002970

**Comment by git-lt** [comment]
`tsconfig.json` 中配置添加 `declaration:true` 就能生成了

**Comment by Mr-jiangzhiguo** [comment]
> `tsconfig.json` 中配置添加 `declaration:true` 就能生成了

这是我的复现地址：https://github.com/bug-repos/dumi/blob/master/tsconfig.json

declaration:true 已经是打开了的

**Comment by ChenYCL** [comment]
同问题

**Comment by theprimone** [comment]
@ChenYCL 有解决吗？我现在看 esm 和 lib 下也是没有生成对应的 d.ts 文件。已配置 `declaration:true`

版本信息：

- "father-build": "^1.19.6"
- "typescript": "^4.3.2"

**Comment by theprimone** [comment]
啊这，换成 father 还是不行。试了试 https://github.com/react-component/trigger 发现是能生成 d.ts 的，头疼...

**Comment by ChenYCL** [comment]
没有解决

**Comment by theprimone** [comment]
@ChenYCL https://github.com/umijs/father#disabletypecheck 看看是不是这个问题。

**Comment by ChenYCL** [comment]
@theprimone 当前我们的组件库使用的是https://github.com/ant-design/pro-components这个结构改造的，官方的看了下是可以生成d.ts的，learn+ dumi，参照https://github.com/umijs/dumi/blob/master/packages/preset-dumi/package.json 这里每个pakcages/* 包下添加了tsconfig.json 会触发ts类型检查编译，不过遗憾的是类型检查报错很多，直接报错了，预期可能会生成.d.ts吧，`disableTypeCheck`这个没有配置 默认应该是false

**Comment by theprimone** [comment]
> @theprimone 当前我们的组件库使用的是[ant-design/pro-components](https://github.com/ant-design/pro-components) 这个结构改造的，官方的看了下是可以生成d.ts的，learn+ dumi，参照 [umijs/dumi@`master`/packages/preset-dumi/tsconfig.json](https://github.com/umijs/dumi/blob/master/packages/preset-dumi/tsconfig.json?rgh-link-date=2021-06-18T02%3A57%3A32Z) 这里每个pakcages/* 包下添加了tsconfig.json 会触发ts类型检查编译，不过遗憾的是类型检查报错很多，直接报错了，预期可能会生成.d.ts吧，`disableTypeCheck`这个没有配置 默认应该是false

所以是因为类型报错导致的没有生成 d.ts 吗？:joy:

**Comment by daolou** [comment]
有问题请提供 miniRepo

**Comment by ChenYCL** [comment]
> > @theprimone 当前我们的组件库使用的是[ant-design/pro-components](https://github.com/ant-design/pro-components) 这个结构改造的，官方的看了下是可以生成d.ts的，learn+ dumi，参照 [umijs/dumi@`master`/packages/preset-dumi/tsconfig.json](https://github.com/umijs/dumi/blob/master/packages/preset-dumi/tsconfig.json?rgh-link-date=2021-06-18T02%3A57%3A32Z) 这里每个pakcages/* 包下添加了tsconfig.json 会触发ts类型检查编译，不过遗憾的是类型检查报错很多，直接报错了，预期可能会生成.d.ts吧，`disableTypeCheck`这个没有配置 默认应该是false
> 
> 所以是因为类型报错导致的没有生成 d.ts 吗？😂

我觉得不是，你可以抽一个procomponets的最小配置看看，缺失tsconfig配置，
![image](https://user-images.githubusercontent.com/25706676/122500495-7b8ae680-d025-11eb-927a-657ed618a751.png)

**Comment by lvpangpang** [comment]
father不支持的 要自己写脚本
或者你组件里面写js再写一个index.d.ts

**Comment by NexxLuo** [comment]
‘declaration:true’  、`disableTypeCheck:false`可正常生成

**Comment by nnmax** [comment]
如果 tsconfig.json 文件已经设置了 `declaration: true` 并且 .father.js 也设置了 `disableTypeCheck: false` 还是不生效，请将 [`isolatedModules`](https://www.typescriptlang.org/tsconfig#isolatedModules) 设置为 `false`，这对于我有用。

**Comment by superAo005** [comment]
disableTypeCheck 设置为false的话 打包编译报错

**Comment by kaqiinono** [comment]
没有配置include
