### ISSUE TITLE
使用umi创建ant-degin-pro项目编译storybook样式无效

### ISSUE THREAD

**Issue by Caitingwei** [umijs/father#223]
## What happens?

通过cssModules模式引入的样式没有被编译。

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

我尝试在src/stories/目录下创建storybook相关文档，如下:
![image](https://user-images.githubusercontent.com/24822015/82195027-4e539c80-992a-11ea-9849-8bb767d53434.png)

```javascript
//  /.storybook/main.tsx
module.exports = {
  stories: ['../src/stories/*.tsx'],
};
```

```javascript
// Button.stories.tsx
import React from 'react';
import { Button } from 'antd';
import styles from './index.less';

export const CustomButton = () => <button className="custom_button">加了className的button</button>

export const AddClassCustomButton = () => <button className={styles.CustomButton}>cssModules的button</button>

export const AntButton = () => (
  <Button>添加样式后的按钮</Button>
);

export default {
  title: 'CustomButton',
  component: CustomButton,
};
```

```css
/* index.less */
.CustomButton {
    background: red;
}
.custom_button {
    background: red;
}
```

```
$ npx father doc dev --storybook
```
执行命令后结果如下:
![image](https://user-images.githubusercontent.com/24822015/82195219-996daf80-992a-11ea-99c1-65696b316fd5.png)
![image](https://user-images.githubusercontent.com/24822015/82195235-9d99cd00-992a-11ea-9d37-43038393dae7.png)
![image](https://user-images.githubusercontent.com/24822015/82195248-a12d5400-992a-11ea-897a-bbc7715cfacb.png)

没有使用cssModules的button样式正常如期渲染，使用了cssModules的button样式没有被编译进去。并且通过antd导入的button组件 也没有样式。

然后我尝试通过.fatherrc.js配置参数重新编译:

```javascript
// .fatherrc.js
export default {
  esm: {
    type: 'rollup',
    importLibToEs: true,
  },
  cjs: 'rollup',
  cssModules: true,
  extractCSS: true,
  lessInBabelMode: true,
  runtimeHelpers: true,
  extraBabelPlugins: [
    [
      'babel-plugin-import',
      {
        libraryName: 'antd',
        libraryDirectory: 'es',
        style: true,
      },
    ],
  ],
};
```
```
$ npx father doc dev --storybook
```
重新编译后, 发现样式依然是没有被渲染。

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Father Version**:  5.3.18 
- **Node Version**: v12.16.3
- **Platform**: Win10专业版 64位。 Chrome  81.0.4044.138（正式版本） （64 位）

**Comment by Caitingwei** [comment]
@sorrycc 大佬帮忙看下如何处理，谢谢！

**Comment by PeachScript** [comment]
组件开发不建议开启 CSS Modules，另外，建议使用 dumi 作为组件开发 & 文档编写工具，可以初始化一个 dumi & father-build 的脚手架试试看：https://d.umijs.org/guide/getting-started#%E7%BB%84%E4%BB%B6%E5%BC%80%E5%8F%91%E8%84%9A%E6%89%8B%E6%9E%B6

**Comment by gaoryrt** [comment]
有问题 -> 提问题
提问题 -> 建议不要写会出问题的代码
✘ -> ✔︎
