### ISSUE TITLE
[DISCUSS] feature requests for the father 3

### ISSUE THREAD

**Issue by PeachScript** [umijs/father#225]
## 背景
father 3 还在炉子里，为了使得新的 father 能发挥更大的作用，在这里搜集大家对 father 3 的功能期望，可以是 2.x 的痛点或遗留问题、竞品的亮点、实际应用中的边界场景等。

## 格式
为了便于整理，希望以如下形式提供建议：

> ### 功能描述
> 希望增加 XXX
> ### 解决的问题
> 可以使得 XXX 更加高效
> ### 解决方案参考（可选）
> 采用 XXX 方式

感谢 ❤

**Comment by Mr-jiangzhiguo** [comment]
## 功能描述

希望增加 对 babel 方式下编译默认 @ 别名为真实目录的支持

umi 默认：@/*  => src/* 

在 dumi 中使用 umi 提供的别名 @，打包后，别名 @ 符号没有被替换成映射的真实目录，如图：

![image](https://user-images.githubusercontent.com/22312092/84159438-a56b0e00-aa9f-11ea-8299-0cb3ffba49eb.png)

### miniRepo：<https://github.com/bug-repos/dumi-alias>



## 解决的问题

- 可以提高开发效率
- 方便移动到另外的目录
- 和项目（umi）保持统一

## 解决方案参考

babel 是文件到文件的编译，没有 插件/中间件 处理，可以使用 webpack + babel 进行编译处理别名 @ 问题

**Comment by Mr-jiangzhiguo** [comment]
## 功能描述
希望增加 babel 方式下，引入静态资源，并生成 d.ts 文件的支持

有些场景是需要在组件中引入静态资源（image、font）的

```tsx
import Img1 from './images/01.png'
```

![image](https://user-images.githubusercontent.com/22312092/84161436-dc422380-aaa1-11ea-9200-0f79dc615319.png)

### miniRepo：<https://github.com/bug-repos/dumi>

## 解决的问题
- 扩大使用场景

## 解决方案参考
针对 father2，我提了 [PR](https://github.com/umijs/father/pull/220) 进行处理，官方还未 merge，可以先 hack 实现一下，demo: <https://github.com/jsany/lean>

father3 的话，同样可以通过 webpack + ts-loader 进行处理静态资源

**Comment by CJY0208** [comment]
组件库打包产物是否做到像 antd 那样，less/sass 样式既能打包成 css，又可以保留原来的 less/sass 文件？

查看文档后没找到可行的实现方式，不确定目前是否支持...如果不支持的话，此处也当作一个 feature requests，期待能支持

**Comment by huzhongchun** [comment]
babel模式下好像不支持less文件的编译
