### ISSUE TITLE
babel模式编译ts，无法识别声明文件

### ISSUE THREAD

**Issue by huzhongchun** [umijs/father#227]
根目录下的typings.d.ts，配置如下：
![image](https://user-images.githubusercontent.com/6973866/85018409-b9012d80-b19f-11ea-9d0b-755e011b4ce6.png)
执行father build --cjs babel，提示如下

![image](https://user-images.githubusercontent.com/6973866/85018594-ff568c80-b19f-11ea-8292-a67748d312a8.png)
尝试把typings.d.ts放到src下也是同样的问题

@sorrycc 大佬帮忙看下啊

**Comment by huzhongchun** [comment]
![image](https://user-images.githubusercontent.com/6973866/85099848-1f825c00-b231-11ea-9732-101099598b5c.png)
跟踪源码发现是father-build的源码里isTsFile过滤掉了.d.ts文件，导致gulpTs获取获取声明文件。

临时解决方法：修改father-build/lib/babel.js下的isTsFile方法，去掉对.d.ts的过滤，同时把声明文件放到src目录下

**Comment by Mr-jiangzhiguo** [comment]
我提了 [pr](https://github.com/umijs/father/pull/220) 

但没 merge，等 father3 出来吧，

或者你可以看看我[这里](https://github.com/jsany/lean/blob/master/scripts/hack-depend.js)是怎么处理的

**Comment by PeachScript** [comment]
临时方案：

1. 在 `tsconfig.json` 中新增 `compilerOptions.typeRoots` 配置：
``` diff
{
  "compilerOptions": {
+    "typeRoots": ["./typings"]
  }
}
```

2. 创建 `typings/global/index.d.ts`，里面声明全局自定义的 module：
```diff
+ declare module "*.less";
```

3. 注意 `typeRoots` 包含类似 `node_modules/@types` 的默认值，进行改写默认值会失效，如果用到 `@types/xxx` 的类型定义需要手动把默认值加回来

**Comment by aweiu** [comment]
试试 https://github.com/umijs/father/issues/48#issuecomment-730857244

**Comment by watsonhaw5566** [comment]
> 试试 [#48 (comment)](https://github.com/umijs/father/issues/48#issuecomment-730857244)

这个有用，但是感觉是build的时候gulp找不到typing文件了。期待dumi3可以修复这个问题。

**Comment by javaxiu** [comment]
@huzhongchun 请问最后是怎么解决的呢？目前 father-build@1.21 仍然有这个问题

**Comment by WillCoco** [comment]
/// <reference path="你的 xxx.d.ts 路径" />

或者xx.d.ts改成xx.ts（father-build中babel.ts过滤了d.ts）

lerna的话注意在子包的src下添加声明文件

**Comment by shallinta** [comment]
I run into the same issue. 
Temporary solution was to add a triple slash reference sentence. But would cause an eslint error in type of `@typescript-eslint/triple-slash-reference`.

**Comment by PeachScript** [comment]
father 4 已发布，可尝试升级到最新版：https://github.com/umijs/father/blob/master/docs/guide/migrate.md

旧版本不再维护，感谢支持

**Comment by johanazhu** [comment]
用了方案还是不行，只能升级至 father 4
