### ISSUE TITLE
umd模式构建的语法错误问题

### ISSUE THREAD

**Issue by milobluebell** [umijs/father#228]
## What happens?

使用umd模式构建，原先通过lint的代码依然`semantic error`。修了一个又一个，有点烦

## Mini Showcase Repository(REQUIRED)

> https://github.com/milobluebell/mlz-admin

## How To Reproduce

** 直接使用运行`sudo npm run dist`，即可看到在umd构建时的错误。但是如果去掉father.ts的umd构建，则可以成功。说明umd和esm/cjs走了不同的lint策略

## Context

- **Father Version**: ^1.17.2
- **Node Version**: v10.21.0
- **Platform**: macOS catalina 10.15.5 (19F101)

@sorrycc

**Comment by 0820Jones** [comment]
请问最后咋解决的呢？ @milobluebell

**Comment by PeachScript** [comment]
father 4 已发布，可尝试升级到最新版：https://github.com/umijs/father/blob/master/docs/guide/migrate.md

旧版本不再维护，感谢支持
