### ISSUE TITLE
左下角自带的文案 “Build with father and docz” 是否可以去掉？

### ISSUE THREAD

**Issue by papuaer** [umijs/father#229]
构建出的页面中，左下角自带了一个文案 “Build with father and docz” 这个应该怎么才能去掉呢

## 相关环境信息

- **Father 版本**：
2.29.3
- **Node 版本**：
10.15
- **操作系统**：
mac os

**Comment by PeachScript** [comment]
这是 https://github.com/umijs/docz-theme-umi 的默认文案，目前无法配置，且 father 内置的 docz 版本已经比较旧了，如果不是必须使用 docz，建议使用 dumi 来做组件库开发：https://d.umijs.org/guide/getting-started#%E7%BB%84%E4%BB%B6%E5%BC%80%E5%8F%91%E8%84%9A%E6%89%8B%E6%9E%B6
