### ISSUE TITLE
可以修改packages 的目录名称吗？

### ISSUE THREAD

**Issue by ziven27** [umijs/father#230]
## What happens?

在 lerna 模式下，修改了 packages 的目录名称之后执行 father build 找不到目录

## 最小可复现仓库

> 请上传到你的 GitHub 仓库。

`.fatherrc.js`

```json
export default {
  esm: 'babel',
  cjs: 'babel',
}
```

`lerna.json`
```json
{
  "packages": ["react/*"],
  "private": true,
  "command": {
    "bootstrap": {
      "hoist": true
    },
    "publish": {
      "ignoreChanges": ["*.md", "**/test/**", "**/demo/**", "**/dist/**"],
      "conventionalCommits": true,
      "message": "chore(release): publish"
    }
  },
  "useWorkspaces": true,
  "npmClient": "yarn",
  "version": "independent"
}

```

## 相关环境信息

- **Father 版本**：v2.29.3
- **Node 版本**：v12.16.3
- **操作系统**：macOS Catalina 10.15.5

**Comment by PeachScript** [comment]
目前不支持修改，默认约定是 `packages`。修改的初衷是什么？

**Comment by zen0822** [comment]
@PeachScript 可以希望加上 ;D，可以根据 lerna.json 读取包名？我希望修改的初衷是管理多个 npm 包，归类好位置

**Comment by wangxingkang** [comment]
https://github.com/umijs/father/pull/313  这个PR解决了这个问题

**Comment by wangxingkang** [comment]
直接解析lerna.json的配置

**Comment by wangxingkang** [comment]
暂时关闭了，有问题再重新打开
