### ISSUE TITLE
father-build 打包 包含自定义xx.d.ts报错

### ISSUE THREAD

**Issue by Veath** [umijs/father#232]
## What happens?

father-build 使用babel 打包的时候,包含`d.ts`报错
## 最小可复现仓库

> 请上传到你的 GitHub 仓库。

https://github.com/Veath/father-demo
## 复现步骤，错误日志以及相关配置
`yarn instll`
`yarn build`

**Comment by aweiu** [comment]
https://github.com/umijs/father/issues/48#issuecomment-730857244

**Comment by aweiu** [comment]
Duplicate of #48

**Comment by PeachScript** [comment]
参考：https://github.com/umijs/father/issues/227#issuecomment-720928000
