### ISSUE TITLE
babel 方式 cjs 包会默认引入 react

### ISSUE THREAD

**Issue by daolou** [umijs/father#235]
## What happens?

采用 babel 方式，target 设置为 node，打 cjs 包，默认引入了 react，工具包不需要 react

![image](https://user-images.githubusercontent.com/22312092/88253545-e4b68c80-cce4-11ea-8448-e5001698e1fc.png)

## Context

- **Father Version**: ^1.18.1
- **Node Version**: 10
- **Platform**: mac

**Comment by PeachScript** [comment]
father 4 已发布，可尝试升级到最新版：https://github.com/umijs/father/blob/master/docs/guide/migrate.md

旧版本不再维护，感谢支持
