### ISSUE TITLE
为什么src不存在的时候，将entry指向components/index时，打包后没lib和es文件夹

### ISSUE THREAD

**Issue by gongfuxiaocai** [umijs/father#245]
现在将dumi创建出来的demo中的src改成components后，将.fatherrc.ts改成
`{
  entry: 'components/index',
  esm: 'babel',
  cjs: {
    type: 'babel',
    lazy: true
  },
}`

运行 father build

运行结果是没有lib和es文件夹的，请问怎么为什么entry不生效呢？

**Comment by PeachScript** [comment]
babel 是文件到文件的编译，是根据 `src` 下的目录结构对应输出到 `lib` or `es`，该行为不支持配置；
entry 仅在 rollup 模式下生效，会根据 entry 进行打包并输出文件，一个 entry 最终只会输出一个文件。
