### ISSUE TITLE
[Feature Request] 请问，打包方式是babel的时候，antd怎么更换主题呢？

### ISSUE THREAD

**Issue by sorryxc** [umijs/father#246]
开发环境可以通过umirc配置更改antd的主题，但是打包用的是father-build，并不走umirc，这时候配置的主题也就不生效了，而文档上又没有关于这方面的描述，请教一下在打包的时候怎么给antd设置主题呢？

**Comment by PeachScript** [comment]
babel 模式是文件到文件的编译，目前没有优雅的方式控制三方库的主题，建议在仓库中提供 `theme.less` or `theme.js`，让使用的项目引用该配置

**Comment by zhaoyu69** [comment]
@PeachScript 有具体点的写法示例吗
