### ISSUE TITLE
使用rollup方式打包，代码中引入lib文件内的某些文件，不会被打包到index.esm.js内

### ISSUE THREAD

**Issue by SwnCowDevil** [umijs/father#263]
### 项目代码中引用 node_modules内的文件
import 'codemirror/lib/codemirror.css';
![image](https://user-images.githubusercontent.com/23211134/94260245-65526d00-ff62-11ea-87c9-38cb88ff7c65.png)

### 使用rollup方式打包
`
export default {
  esm: 'rollup',
  cjs: 'rollup',
  disableTypeCheck: true,  // 禁用类型检查
  cssModules: true,
};
`

### 生成的index.esm.js中没有引用codemirror.css的相关代码

![image](https://user-images.githubusercontent.com/23211134/94260590-08a38200-ff63-11ea-8dd9-43c0f21e9eb1.png)

### 相关版本

father-build: 1.18.5

**Comment by PeachScript** [comment]
codemirror 放入 `depdendencies` 了吗

**Comment by SwnCowDevil** [comment]
codemirror 加入到 dependencies 后 成功，感谢
