### ISSUE TITLE
请问 dumi + father 如何搭配 lerna 使用？

### ISSUE THREAD

**Issue by wpnl** [umijs/father#264]
请问怎么使用，有一个项目使用案例可以参考吗

**Comment by xiaohuoni** [comment]
https://github.com/alitajs/father-lerna-init 看这个吧，dumi 第一次提交我 fork 下来的

**Comment by PeachScript** [comment]
> https://github.com/alitajs/father-lerna-init 看这个吧，dumi 第一次提交我 fork 下来的

竟然还有这一手

**Comment by xiaohuoni** [comment]
穷人家过日子，未雨绸缪。

**Comment by hangaoke1** [comment]
https://github.com/hangaoke1/dumi-lerna-tpl 模版可以参考一下

**Comment by xiaohuoni** [comment]
移动端组件的可以参考 https://github.com/alitajs/antd-mobile-plus
