### ISSUE TITLE
babel模式下extraPostCSSPlugins没有生效

### ISSUE THREAD

**Issue by zhangyu1818** [umijs/father#265]
extraPostCSSPlugins在rollup下生效，在babel下不生效
复现仓库 https://github.com/zhangyu1818/father-postcss.git

**Comment by PeachScript** [comment]
是的，目前 babel 模式下仅支持启用 less 编译，不支持其他预处理器

**Comment by xuehebinglan** [comment]
这个问题有没有更新解决呀？babel模式下使用extraPostCSSPlugins不生效！
