### ISSUE TITLE
右侧目录切换后，页面中的组件会卸载，并重新渲染。

### ISSUE THREAD

**Issue by HarveyZgit** [umijs/father#266]
通过点击右侧目录切换锚点，发现页面中已渲染的组件会卸载，并重新渲染。

请问如何解决？

**Comment by HarveyZgit** [comment]
版本：
father: 2.29.5
docz: 1.3.2
react: 16.13.1

**Comment by PeachScript** [comment]
father 内置的 docz 很老了，如果要使用建议单独使用 docz + father-build；遇到 docz 的问题请移步 docz 的项目 issue；另外推荐使用 dumi + father-build 做组件库研发，体验更好：https://github.com/umijs/father/issues/241
