### ISSUE TITLE
Bable模式下编译tsx/ts，require自动变成绝对路径，如何将其变为包的相对路径？

### ISSUE THREAD

**Issue by qingzi-king** [umijs/father#267]
.fatherrc.ts配置

> export default {
  entry: 'src/*',
  extractCSS: true,
  lessInBabelMode: true,
  runtimeHelpers: true,
  esm: {
    type: 'babel',
    minify: false,
  },
  cjs: {
    type: 'babel',
    lazy: true,
  }
};

编译后的文件中require部分为绝对路径，这样导致换了位置无法使用，有什么方法解决吗？

> var _interopRequireWildcard = require("/Users/***/Desktop/project/carkings/agile-mobile/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/interopRequireWildcard");

**Comment by PeachScript** [comment]
无法复现，项目里还有额外的 babel 配置吗？

**Comment by yingzi4773** [comment]
我也遇到了相同的问题，请问题主解决了吗

**Comment by qingzi-king** [comment]
> 我也遇到了相同的问题，请问题主解决了吗

解决了，你可以参考下：https://github.com/qingzi-king/agile-mobile

**Comment by yingzi4773** [comment]
> .fatherrc.ts配置
> 
> > export default {
> > entry: 'src/*',
> > extractCSS: true,
> > lessInBabelMode: true,
> > runtimeHelpers: true,
> > esm: {
> > type: 'babel',
> > minify: false,
> > },
> > cjs: {
> > type: 'babel',
> > lazy: true,
> > }
> > };
> 
> 编译后的文件中require部分为绝对路径，这样导致换了位置无法使用，有什么方法解决吗？
> 
> > var _interopRequireWildcard = require("/Users/***/Desktop/project/carkings/agile-mobile/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/interopRequireWildcard");



> > 我也遇到了相同的问题，请问题主解决了吗
> 
> 解决了，你可以参考下：https://github.com/qingzi-king/agile-mobile ，`tsconfig.json`、`.fatherrc.ts`配置。
> 
> 编译过程中对`.babelrc`进行了备份调整。
> 
> ![image](https://user-images.githubusercontent.com/13265583/115520806-1cc31e00-a2bd-11eb-8d5c-5db361db0515.png)
大佬，解决了这个问题了！！！膜拜～这个问题是因为自己项目有额外的babel配置导致和father里的babel冲突吗？还请大佬指点一二

**Comment by PeachScript** [comment]
father 4 已发布，可尝试升级到最新版：https://github.com/umijs/father/blob/master/docs/guide/migrate.md

旧版本不再维护，感谢支持
