### ISSUE TITLE
能不能支持sass呢，急求~

### ISSUE THREAD

**Issue by thisXY** [umijs/father#268]
能不能支持sass呢，急求~

**Comment by PeachScript** [comment]
rollup 模式支持的：https://github.com/umijs/father#sassinrollupmode

**Comment by thisXY** [comment]
> rollup 模式支持的：https://github.com/umijs/father#sassinrollupmode

试了不行呢，能简单给个配置demo吗，感谢！

**Comment by PeachScript** [comment]
https://github.com/umijs/father/tree/master/packages/father-build/src/fixtures/build/rollup-sass

**Comment by thisXY** [comment]
> https://github.com/umijs/father/tree/master/packages/father-build/src/fixtures/build/rollup-sass

我也是这样配置的，但一直都是如图提示报错，请问是不是对node-sass的版本有要求
![微信图片_20201102101506](https://user-images.githubusercontent.com/26090682/97823810-02888a00-1cf5-11eb-9b41-e627a368229b.png)

**Comment by PeachScript** [comment]
这是说 sass 配置要放进 `sassOptions` 吧

**Comment by thisXY** [comment]
发现确实是对sass-loader版本有限制，目前降级到@^7.3.1解决了
https://github.com/JeffreyWay/laravel-mix/issues/2206

**Comment by PeachScript** [comment]
> 发现确实是对sass-loader版本有限制，目前降级到@^7.3.1解决了
> [JeffreyWay/laravel-mix#2206](https://github.com/JeffreyWay/laravel-mix/issues/2206)

#274 合并升级到 rollup 2 后就能解锁版本了

**Comment by thisXY** [comment]
谢谢！还有个问题：
关于配置cssModules：默认是 .module.css 走 css modules，.css 不走 css modules。配置 cssModules 为 true 后，全部 css 文件都走 css modules。（less 文件同理）
如何配置使得.module.sass走css modules，其他都不走呢，我试了关于sass的，要么都走要么都不走

**Comment by thisXY** [comment]
> > 发现确实是对sass-loader版本有限制，目前降级到@^7.3.1解决了
> > [JeffreyWay/laravel-mix#2206](https://github.com/JeffreyWay/laravel-mix/issues/2206)
> 
> #274 合并升级到 rollup 2 后就能解锁版本了

谢谢！还有个问题：
关于配置cssModules：默认是 .module.css 走 css modules，.css 不走 css modules。配置 cssModules 为 true 后，全部 css 文件都走 css modules。（less 文件同理）
如何配置使得.module.sass走css modules，其他都不走呢，我试了关于sass的，要么都走要么都不走

**Comment by PeachScript** [comment]
已升级到 rollup 2，可以解锁版本了；sass 的部分能力可能是对不齐的，可以在 postcss-plugin 的仓库里找找看
