### ISSUE TITLE
typescript@4.x、rollup@2.x 什么时候升级支持

### ISSUE THREAD

**Issue by huixisheng** [umijs/father#269]
https://github.com/rollup/rollup/blob/master/CHANGELOG.md
https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/

**Comment by PeachScript** [comment]
最近了，一大批依赖需要升级

**Comment by PeachScript** [comment]
@huixisheng 有时间的话可以帮忙验证下 `father-build@1.19.0-alpha.0` 是否正常工作，这个版本是 rollup 2 的测试版，感谢
