### ISSUE TITLE
关于TS组件相互依赖的编译报错问题

### ISSUE THREAD

**Issue by programmer-yang** [umijs/father#270]
在使用father编译多个组件（ts）的时候，如果A组件依赖的B组件，然后编译顺序是A、B这样，这个时候会报错，是因为在编译A组件的时候会检查B组件的声明文件，这个时候B还没被编译，所以声明文件还没创建，然后这里就过不去了

目前是通过配置disableTypeCheck绕过类型检查，执行一次全量编译，就可以绕过这个问题

**Comment by PeachScript** [comment]
A 组件直接依赖了 B 的产物文件？依赖源码应该不存在这个问题，很多项目都有类似场景

**Comment by programmer-yang** [comment]
可以通过修改配置文件`.fatherrc.ts`里的`pkgs`属性，调整需要优先编译的组件名称到包名称列表前面来解决这个问题
