### ISSUE TITLE
docz版本太低，导致无法写出文档

### ISSUE THREAD

**Issue by yunyi1895** [umijs/father#271]
![image](https://user-images.githubusercontent.com/16249023/97671989-3e88d880-1ac4-11eb-8d58-37265e02d459.png)
![image](https://user-images.githubusercontent.com/16249023/97672054-5a8c7a00-1ac4-11eb-8562-80b1a7c68b73.png)

**Comment by xiaohuoni** [comment]
用 [dumi](https://d.umijs.org/) 啊。

**Comment by shaoqiwang-fe** [comment]
这个为啥不升级呢 docz
