### ISSUE TITLE
father build 报错 Error: 'isFragment' is not exported by node_modules/react-is/index.js

### ISSUE THREAD

**Issue by fzhange** [umijs/father#275]
✖  error     Error: 'isFragment' is not exported by node_modules/react-is/index.js
    at error (/node_modules/rollup/dist/rollup.js:5363:30)

>father-build 依赖rollup版本过低导致异常

**Comment by PeachScript** [comment]
依赖是否放进 `dependencies` 或者 `peerDependencies`？和 rollup 版本无关，组件库不应该把 react 一起打进去

**Comment by fzhange** [comment]
> 依赖是否放进 `dependencies` 或者 `peerDependencies`？和 rollup 版本无关，组件库不应该把 react 一起打进去

自己的依赖中不存在rollup依赖，该依赖是在father-build包里的依赖。
stackoverflow 上说这个错误的原因是 rollup版本过低导致的。

**Comment by fzhange** [comment]
> 依赖是否放进 `dependencies` 或者 `peerDependencies`？和 rollup 版本无关，组件库不应该把 react 一起打进去

**Comment by netty0911** [comment]
请问这个问题怎么解决的？

**Comment by netty0911** [comment]
> > 依赖是否放进 `dependencies` 或者 `peerDependencies`？和 rollup 版本无关，组件库不应该把 react 一起打进去
> 
> 自己的依赖中不存在rollup依赖，该依赖是在father-build包里的依赖。
> 
> [参考地址](https://github.com/mui-org/material-ui/issues/18791l)
> [相关地址](https://stackoverflow.com/questions/50080893/rollup-error-isvalidelementtype-is-not-exported-by-node-modules-react-is-indel)

请问这个问题是怎么解决的？

**Comment by netty0911** [comment]
> ✖ error Error: 'isFragment' is not exported by node_modules/react-is/index.js
> at error (/node_modules/rollup/dist/rollup.js:5363:30)
> 
> > father-build 依赖rollup版本过低导致异常

请问这个问题你是怎么解决的？
