### ISSUE TITLE
cjs打包后第三方模块用的还是esm

### ISSUE THREAD

**Issue by wpnl** [umijs/father#277]
`
.fatherrc.js

export default {
  esm: 'rollup',
  cjs: 'rollup',
};
`
打包后的文件
`
dist
'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

function _interopDefault (ex) { return (ex && (typeof ex === 'object') && 'default' in ex) ? ex['default'] : ex; }

require('antd/es/modal/style');
var _Modal = _interopDefault(require('antd/es/modal'));
require('antd/es/message/style');
var _message = _interopDefault(require('antd/es/message'));
require('antd/es/tag/style');
var _Tag = _interopDefault(require('antd/es/tag'));
require('antd/es/button/style');
var _Button = _interopDefault(require('antd/es/button'));
....
`
请问为什么引入的还是 antd/es... 而不是 antd/lib...

`
  "devDependencies": {
    "@commitlint/cli": "^11.0.0",
    "@commitlint/config-conventional": "^11.0.0",
    "@umijs/test": "^3.0.5",
    "chalk": "^4.1.0",
    "commitizen": "^4.2.1",
    "cz-lerna-changelog": "^2.0.3",
    "dumi": "^1.0.10",
    "father-build": "^1.17.2",
    "gh-pages": "^3.0.0",
    "husky": "^4.3.0",
    "lerna": "^3.22.1",
    "lint-staged": "^10.0.7",
    "prettier": "^1.19.1",
    "yorkie": "^2.0.0"
  }
`

**Comment by PeachScript** [comment]
father 4 已发布，可尝试升级到最新版：https://github.com/umijs/father/blob/master/docs/guide/migrate.md

旧版本不再维护，感谢支持
