### ISSUE TITLE
bug: build(father-build)  got "TypeError: Cannot read property 'replace' of undefined"

### ISSUE THREAD

**Issue by ruoqy** [umijs/father#284]
### Versions

- dumi:  1.0.37
- father-build: 1.19.1
- node:  10.16.3
- npm:  6.9.0
- OS:  mac os

### Steps to reproduce
1. yarn create @umijs/dumi-app
2. lerna  create two packages
3. npm run build

### What is Expected?
success

### What is actually happening?
![image](https://user-images.githubusercontent.com/8544859/100986345-0889b900-3588-11eb-9711-9da447b59f37.png)

**Comment by ineedacatmiao** [comment]
我也遇到同样的问题

**Comment by jemygraw** [comment]
遇到同样的问题，很容易复现，`yarn create @umijs/dumi-app --site` 然后build就会遇到。

**Comment by jackywq** [comment]
@PeachScript 我也是遇到同样的问题，怎么处理呢？
![image](https://user-images.githubusercontent.com/21954704/132797004-727ebf31-c830-44b2-8ff8-b18e0aa4fee3.png)

**Comment by wangmeijian** [comment]
the same problem
![image](https://user-images.githubusercontent.com/9384140/135065355-eda36c0c-fd9f-4094-ada4-804bd2ba16b2.png)

**Comment by jimwong666** [comment]
我是打包umd时报的这个错误，后来发现是src目录下没有入口文件导致的，我加了入口文件就解决了
