### ISSUE TITLE
dumi中使用构建father-build遇到问题

### ISSUE THREAD

**Issue by milobluebell** [umijs/father#289]
## Question

我在global.d.ts声明了一个全局变量(比如 TESTVAR )。然后使用father build构建项目，通过extraRollupPlugins字段引用了rollup-plugin-typescript2插件，指向的是在tsconfig.dist.json配置进行编译，tsconfig.dist.json extends了tsconfig.json，只有exclude不同。  平时开发、在eslint和tsc里都没有任何报错。 所以按理说father build也不应该报错吧？ 但是father-build出来，说没有找到TESTVAR。这个是怎么回事，怎么解决呢。

开发时：
![image](https://user-images.githubusercontent.com/11535146/102339370-05eb8280-3fd0-11eb-8cfa-003b65aeac04.png)

father-build时的报错：
![image](https://user-images.githubusercontent.com/11535146/102339381-084ddc80-3fd0-11eb-896c-ce701775d1ea.png)

## Sample Code

复现Repo: https://github.com/milobluebell/mlz-admin/tree/aStableVersion [aStableVersion分支]

复现方式：
```shell
$ sudo npm install 
$ 
$ npm run lint && sudo npm run dist
```

TY.

**Comment by milobluebell** [comment]
辛苦！但是感觉貌似不是这个导致的哦。因为就算使用的是`father-build里的rollup-plugin-typescript2`，也应该读的是 tsconfig.json ，那应该也没问题呀。

**Comment by milobluebell** [comment]
除非连tsconfig.json都读错了？也不太像，那天在群里问过你。你说是lerna的pkg最重，然后就是根目录。这样其实是对的，也符合理解。

**Comment by milobluebell** [comment]
@sorrycc 大佬麻烦给看下吧，多谢了。

**Comment by PeachScript** [comment]
father 4 已发布，可尝试升级到最新版：https://github.com/umijs/father/blob/master/docs/guide/migrate.md

旧版本不再维护，感谢支持
