### ISSUE TITLE
这个工具依赖太多了

### ISSUE THREAD

**Issue by yuki070** [umijs/father#291]
这个工具依赖太多了，安装特别久，能否优化一下？

**Comment by kokiy** [comment]
关键没有一个模板  demo 啥的 默认配置 有点懵逼

**Comment by PeachScript** [comment]
建议使用 dumi + father-build 的组合做组件研发，father = father-build + docz + storybook，后两者版本已经很陈旧了、而且安装体积巨大

**Comment by yuki070** [comment]
> 建议使用 dumi + father-build 的组合做组件研发，father = father-build + docz + storybook，后两者版本已经很陈旧了、而且安装体积巨大

在npm中找的father-build就是跳转到这里呀😂，比较困惑。
https://www.npmjs.com/package/father-build

**Comment by PeachScript** [comment]
这是 lerna 仓库，包含 father 和 father-build 两个子包
