### ISSUE TITLE
代码中引用了umi，发包会报错

### ISSUE THREAD

**Issue by KellenHe** [umijs/father#293]
比如在代码中使用`import { useRequest } from 'umi';`
打包会报如下错误：
![image](https://user-images.githubusercontent.com/9713892/102763987-6c4c1880-43b5-11eb-8897-dd6c57ef0d31.png)

**Comment by PeachScript** [comment]
Umi 是前端开发框架，组件库不应该直接引用，可以单独安装 `umi-request`
