### ISSUE TITLE
构建时报这个错，请问是什么原因？

### ISSUE THREAD

**Issue by KellenHe** [umijs/father#294]
![image](https://user-images.githubusercontent.com/9713892/102771434-de762a80-43c0-11eb-9940-141120877f60.png)

**Comment by PeachScript** [comment]
检查下源代码，用到的依赖要写入 `dependencies`

**Comment by KellenHe** [comment]
@PeachScript 
问题找到了，还想请问一个问题，在类库中不引用umi这种权限访问如何引用？
`import { useAccess, Access } from 'umi';`

**Comment by PeachScript** [comment]
这是 Umi Plugin 的能力，组件库用不了的；而且组件库应和业务逻辑解耦、保持纯粹性
