### ISSUE TITLE
umd构建会出现语法错误，有木有配置可以规避？

### ISSUE THREAD

**Issue by wo-de-ping-er** [umijs/father#297]

**Comment by PeachScript** [comment]
请补充问题详情、错误截图、复现步骤

**Comment by wo-de-ping-er** [comment]
> 请补充问题详情、错误截图、复现步骤

就是eslint代码格式校验问题，这个有配置可以规避吗

**Comment by wo-de-ping-er** [comment]
> > 请补充问题详情、错误截图、复现步骤
> 
> 就是eslint代码格式校验问题，这个有配置可以规避吗

![Uploading image.png…]()
