### ISSUE TITLE
打包工具未对组件中引用到的静态资源进行路径转换/转码，应该如何配置？

### ISSUE THREAD

**Issue by wjq990112** [umijs/father#300]
在组件开发中，组件及组件中的 css 文件引用到了图片，在组件中是直接以路径的方式引入，在组件 css 中是使用 `url()` 引入，如何对静态资源进行处理？比如对路径进行转换，将图片 copy 至 `dist/assets` 目录下或转码为 `base64`？

**Comment by nuoer2048** [comment]
想知道这个问题解决了么？

**Comment by jackywq** [comment]
> 在组件开发中，组件及组件中的 css 文件引用到了图片，在组件中是直接以路径的方式引入，在组件 css 中是使用 `url()` 引入，如何对静态资源进行处理？比如对路径进行转换，将图片 copy 至 `dist/assets` 目录下或转码为 `base64`？

同问

**Comment by wjq990112** [comment]
这个问题未解决，看了一圈 Rollup 生态，没有找到满足这个需求的插件，如果要解决这个问题，有可能需要自定义插件。

**Comment by Huanqiang** [comment]
> 
这个用 postcss 插件解决，比如 postcss-url
