### ISSUE TITLE
mdx文件中使用语法 类似 ## 1.项目介绍, 数字开头的标题会报错

### ISSUE THREAD

**Issue by lsshavedream** [umijs/father#301]
mdx文件中使用语法 类似 ## 1.项目介绍, 数字开头的标题会报错

代码: ## 1.操作说明

AppContainer, in LocationProvider (created by Routes)) SyntaxError: Failed to execute 'querySelectorAll' on 'Document': '#1操作说明' is not a valid selector.

**Comment by PeachScript** [comment]
docz 目前不再建议直接使用内置版本，可以 father-build + docz 的形式，或者迁移到 dumi：https://github.com/umijs/father/issues/241
