### ISSUE TITLE
设置typeRoots之后构建失败

### ISSUE THREAD

**Issue by mfoonirlee** [umijs/father#302]
![image](https://user-images.githubusercontent.com/6947182/103782126-037dc500-5072-11eb-9e2b-5fdd2e41f8f0.png)
其中XData是通过typeRoots声明的隐式引用，没有显示引用，这是ts支持的特性。。但是fatherbuild时失败了。。

**Comment by PeachScript** [comment]
father 4 已发布，可尝试升级到最新版：https://github.com/umijs/father/blob/master/docs/guide/migrate.md

旧版本不再维护，感谢支持
