### ISSUE TITLE
打包后样名称丢失

### ISSUE THREAD

**Issue by SmartWrh** [umijs/father#303]
`.action` 打包后可以正常显示， `.drop-action` 这种打包后丢失，本地运行是ok得，
```
<span className={classNames(styles.dropAction, className)} style={style}>
      <span className={styles.action}></span>
</span>
```
打包后样式名称丢失
```
<span class>
      <span class="action"></span>
</span>
```
.fatherrc.ts 
```
cssModules: {
    generateScopedName: function(name: any, filename: any, css: any) {
      return name;
    },
  },
```

**Comment by SmartWrh** [comment]
可以通过 `localsConvention` 解决 - -

**Comment by liangGeek** [comment]
能看下你的.fatherrc.ts文件吗，我配置了，没有生效

**Comment by SmartWrh** [comment]
> 能看下你的.fatherrc.ts文件吗，我配置了，没有生效

你好，时间有的久了，我也有点忘记当时怎么修复的了，我看了一下代码，在 `.fatherrc.ts` 和 `.umirc.ts` 都配置了 `localsConvention `

**Comment by liangGeek** [comment]
在.umirc.ts里这样配置是可以的cssLoader: {
    localsConvention: 'camelCase'
  },在.fatherrc.ts不行，贴下代码看下呢

**Comment by Fidelgithub** [comment]
> > 能看下你的.fatherrc.ts文件吗，我配置了，没有生效
> 
> 你好，时间有的久了，我也有点忘记当时怎么修复的了，我看了一下代码，在 `.fatherrc.ts` 和 `.umirc.ts` 都配置了 `localsConvention `

具体配置是怎样的？`localsConvention: {}`？

**Comment by SmartWrh** [comment]
> > > 能看下你的.fatherrc.ts文件吗，我配置了，没有生效
> > 
> > 
> > 你好，时间有的久了，我也有点忘记当时怎么修复的了，我看了一下代码，在 `.fatherrc.ts` 和 `.umirc.ts` 都配置了 `localsConvention `
> 
> 具体配置是怎样的？`localsConvention: {}`？

localsConvention: 'camelCase'
