### ISSUE TITLE
设置了base，默认打开跟路由Page Not Found

### ISSUE THREAD

**Issue by ytudt** [umijs/father#305]
.fatherrc.js配置了base: '/fe'，本地启动服务默认跳到'/'而不是跳到'/base'导致页面现实Page Not Found。如何解决

**Comment by PeachScript** [comment]
.fattherrc 没有 base 这个配置项

**Comment by ytudt** [comment]
> .fattherrc 没有 base 这个配置项

有的呀，传给doc配置项,如下

export default  {
 ...
 doc: {
    title: 'xu_ui',
    themeConfig: { mode: 'light' },
    base: '/galaxy/happy-ui',
    dest: 'docsite',
  },
...
}

**Comment by PeachScript** [comment]
docz 目前不再建议直接使用内置版本，可以 father-build + docz 的形式，或者迁移到 dumi：https://github.com/umijs/father/issues/241
