### ISSUE TITLE
esm模式如何编译node_modules中的sass

### ISSUE THREAD

**Issue by 328480460** [umijs/father#307]
node_modules中的某个依赖包只是进过了babel编译，没有处理.scss文件就直接发npm了，现在想在打包esm包的时候处理了这个第三方包的.scss文件，如何做

**Comment by PeachScript** [comment]
目前仅 rollup 模式能编译 sass，配置项：https://github.com/umijs/father#sassinrollupmode

**Comment by ChenYCL** [comment]
@328480460 你好，请问有处理方案么

**Comment by chenxiaoqiang123** [comment]
> node_modules中的某个依赖包只是进过了babel编译，没有处理.scss文件就直接发npm了，现在想在打包esm包的时候处理了这个第三方包的.scss文件，如何做

有解决方案吗
