### ISSUE TITLE
怎么排除snapshot文件

### ISSUE THREAD

**Issue by gnoyixiang** [umijs/father#320]
想请问如何把snapshot文件从build files 里排除掉？
现在我的snapshots都会output在src文档里，跟components js 文件一起。
我在用babel 来build

```
// .fatherrc.js
export default {
  esm: 'babel',
  cjs: 'babel',
  extraBabelPlugins: [['transform-remove-console', { exclude: ['error', 'warn'] }]]
}
```

**Comment by PeachScript** [comment]
father 4 已发布，可尝试升级到最新版：https://github.com/umijs/father/blob/master/docs/guide/migrate.md

旧版本不再维护，感谢支持
