### ISSUE TITLE
cjs 模式下，build时候如何忽略node_modules 的检查？

### ISSUE THREAD

**Issue by BryanYang** [umijs/father#322]
...
Clean dist directory
Build cjs with babel
Clean lib directory
/opt/jenkins/workspace/1046474-yanggaofei-rms-table-newtest/node_modules/resize-observer-polyfill/src/index.d.ts(19,18): error TS2717: Subsequent property declarations must have the same type.  Property 'contentRect' must be of type 'DOMRectReadOnly', but here has type 'DOMRectReadOnly'.
Transform to cjs for src/ColGroup.js
Transform to cjs for src/Table.js
Transform to cjs for src/index.js
Transform to cjs for src/interface.js
Transform to cjs for src/stickyScrollBar.js
Transform to cjs for src/Cell/index.js
Transform to cjs for src/Body/BodyRow.js

**Comment by PeachScript** [comment]
tsconfig 里配 skipLibCheck
