### ISSUE TITLE
给CLI添加新特性

### ISSUE THREAD

**Issue by jinyang1994** [umijs/father#329]
@sorrycc 你好，如果想给CLI添加新特性的话，测试应该怎么写？
想支持一下指定配置文件路径

**Comment by PeachScript** [comment]
@jinyang1994 father 中内置的 test 命令背后是旧版本的 umi-test，可以帮忙迁移到新版的 @umijs/test，目前 father 收到的参数都是透传的，推测是旧版本没有透传给 jest 导致的
