### ISSUE TITLE
lack of babel-import-plugin when updated

### ISSUE THREAD

**Issue by milobluebell** [umijs/father#334]
你好，更新到1.19.3之后，在自己项目里dist，报错找不到`babel-import-plugin`，请问是更新了哪里的依赖吗？

**Comment by milobluebell** [comment]
通过在项目本身install该插件当然是可以解决的，但是还是想和以前一样，并且好奇改了哪里。

**Comment by PeachScript** [comment]
其他使用 father-build 的仓库没发现这个情况，请提供下复现

**Comment by milobluebell** [comment]
> 其他使用 father-build 的仓库没发现这个情况，请提供下复现

先确定一下，如果使用father-build，是否还需要在项目里安装babel-import-plugin？ （之前是内置了的反正）

**Comment by milobluebell** [comment]
如果不需要的话，我晚点给你复现repo

**Comment by PeachScript** [comment]
> > 其他使用 father-build 的仓库没发现这个情况，请提供下复现
> 
> 先确定一下，如果使用father-build，是否还需要在项目里安装babel-import-plugin？ （之前是内置了的反正）

需要安装，father-build 的依赖里没有 `babel-plugin-import`

**Comment by milobluebell** [comment]
@PeachScript 
那很奇怪，我之前一直都沒有安裝，并且正確build。直到那天我刪除了lock文件，重新install，再build就缺少這個插件了。如果必須安裝，那之前不安裝也可以運行就很奇怪了。

現在已經通過安裝它解決了該問題。
