### ISSUE TITLE
如何忽略__tests__ 文件夹

### ISSUE THREAD

**Issue by Simon-Bin** [umijs/father#340]
不能忽略文件 

babel 打包

**Comment by Simon-Bin** [comment]
tsconfig excludes 添加**/__tests__ 不能忽略

**Comment by Simon-Bin** [comment]
![image](https://user-images.githubusercontent.com/26505011/115831560-56726100-a444-11eb-95d9-4d994bdc6fbb.png)

**Comment by Simon-Bin** [comment]
暂时只能通过配置npmignore 发布时候 忽略文件

**Comment by xrkffgg** [comment]
```json
"exclude": [
    "**/__tests__"
]
```

**Comment by Simon-Bin** [comment]
> ```json
> "exclude": [
>     "**/__tests__"
> ]
> ```

这样只忽略了ts 文件,没有忽略测试快照文件,还有测试文件夹中不是.test.ts结尾的文件也会被babel打包

**Comment by xrkffgg** [comment]
我有项目 tsconfig 都没配，打包也没事啊。

你看下 https://github.com/react-component/progress

**Comment by Simon-Bin** [comment]
> 我有项目 tsconfig 都没配，打包也没事啊。
> 
> 你看下 https://github.com/react-component/progress

我这个项目把单元测试写到了每个组件的文件夹里，测试文件再src文件夹里

**Comment by Simon-Bin** [comment]
https://github.com/umijs/father/pull/323 这个pr感觉可以
