### ISSUE TITLE
无法单独构建 monorepo package

### ISSUE THREAD

**Issue by helsonxiao** [umijs/father#344]
```
# 只构建 packages/foo
$ PACKAGE=foo father build
```

以上写法在 `1.19.3` & `1.19.4` 中已失效，我降级到 `1.19.2` 后恢复正常，应该是 https://github.com/umijs/father/pull/313 导致的。辛苦你们修复问题，或者在文档中给出最新的用法。

**Comment by PeachScript** [comment]
cc @wangxingkang 有空看下哈

**Comment by helsonxiao** [comment]
已经解决了
