### ISSUE TITLE
build构建错误

### ISSUE THREAD

**Issue by xiaoxiong113** [umijs/father#349]
### Question
自定义组件build 执行father-build报错
### Sample Code
![image](https://user-images.githubusercontent.com/36941094/117604017-f0e1dc80-b186-11eb-8534-16ff51b6e132.png)

**Comment by PeachScript** [comment]
配置了 runtimeHelpers，一定要在 dependencies 里有 @babel/runtime 依赖

**Comment by KellenHe** [comment]
@PeachScript 

1、添加@babel/runtime依赖后报另外一个错：Error: 'isFragment' is not exported by node_modules\react-is\index.js
2、然后添加了react-is，现在报Error: 'default' is not exported by node_modules\classnames\index.js
上周的代码还是build正常的，不知道哪里的问题。

**Comment by PeachScript** [comment]
father 4 已发布，可尝试升级到最新版：https://github.com/umijs/father/blob/master/docs/guide/migrate.md

旧版本不再维护，感谢支持
