### ISSUE TITLE
.fatherrc.js中 rollup plugins无法删除和修改

### ISSUE THREAD

**Issue by hezhengjie** [umijs/father#364]
.fatherrc.js中rollup plugins只能新增，无法删除和修改吗，想要修改内部的一些plugins的配置

**Comment by wangxingkang** [comment]
后续会支持，有兴趣的话，欢迎PR

**Comment by wangxingkang** [comment]
相关issues

- #255

**Comment by PeachScript** [comment]
father 4 已发布，可尝试升级到最新版：https://github.com/umijs/father/blob/master/docs/guide/migrate.md

旧版本不再维护，感谢支持
