### ISSUE TITLE
babel模式支持启用 PostCSS

### ISSUE THREAD

**Issue by li00-7** [umijs/father#365]
father打包配置中的extraPostCSSPlugins支持PostCSS
![image](https://user-images.githubusercontent.com/51317853/120162541-15cbeb80-c22b-11eb-9e6b-d06350de7d7f.png)

**Comment by PeachScript** [comment]
father 4 已发布，可尝试升级到最新版：https://github.com/umijs/father/blob/master/docs/guide/migrate.md

旧版本不再维护，感谢支持
