### ISSUE TITLE
使用babel打包cjs, 且开启lazy引入时, 会产生冗余的react引用

### ISSUE THREAD

**Issue by 7kms** [umijs/father#368]
#### 使用版本`"father-build": "^1.19.6"`
有如下配置

```ts
import { IBundleOptions } from 'father-build/src/types';
export default {
  target: 'node',
  cjs: {
    type: 'babel',
    lazy: true
  }
} as IBundleOptions
```
其中设置了`lazy=true`开启了运行时加载特性,  最后输出的目标代码中包含了冗余的`react`引用.

```js

"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

function _react() {
  const data = _interopRequireDefault(require("react"));

  _react = function _react() {
    return data;
  };

  return data;
}

// ... 省略余下代码

```

但是源代码中并无`jsx`语法,  期待不要有冗余的`react`相关引用, 虽然不影响运行, 但是多少有点瑕疵.

## 问题原因

产生该问题是由于`babel-plugin-react-require`和`@babel/plugin-transform-modules-commonjs`两个插件修改`ast`时有一定的冲突, 导致`babel-plugin-react-require`在`exit`阶段无法正确删除`react`引用.

## 解决方案(已调研)

如果不修改任何第三方库的情况下, 可以将`babel-plugin-react-require`放在`@babel/plugin-transform-modules-commonjs`前面,使`babel-plugin-react-require`能够不受其他插件影响(在`babel-plugin-react-require`的[github主页上](https://github.com/vslinko/babel-plugin-react-require#usage)也特别说明了将其放置在`@babel/plugin-transform-modules-commonjs`前).

**Comment by PeachScript** [comment]
father 4 已发布，可尝试升级到最新版：https://github.com/umijs/father/blob/master/docs/guide/migrate.md

旧版本不再维护，感谢支持
