### ISSUE TITLE
father build 构建后中文被转义了，怎么能不被转义？

### ISSUE THREAD

**Issue by xydegithub** [umijs/father#370]
build后 
export declare const a = "\u6D4B\u8BD5";
declare const _default: ({ title }: {
    title: string;
}) => JSX.Element;
export default _default;

build 前
import React from 'react';

export const a ='测试'

export default ({ title }: { title: string }) => <h1>{title}</h1>;

**Comment by xydegithub** [comment]
@xiaohuoni 大佬

**Comment by PeachScript** [comment]
转义之后的问题是啥

**Comment by xydegithub** [comment]
> 转义之后的问题是啥

代码里写的是export const a ='测试'，然后build之后变成了export declare const a = "\u6D4B\u8BD5";汉字被转了

**Comment by Shipeijing** [comment]
相同的问题，应该是bug吧

**Comment by PeachScript** [comment]
father 4 已发布，可尝试升级到最新版：https://github.com/umijs/father/blob/master/docs/guide/migrate.md

旧版本不再维护，感谢支持
