### ISSUE TITLE
command not found: father

### ISSUE THREAD

**Issue by huanghly** [umijs/father#371]
用yarn add father安装了father，报错command not found: father，昨天使用的时候，是可以执行的，
![image](https://user-images.githubusercontent.com/28948944/123727722-a77b5700-d8c4-11eb-802f-2002310e3df9.png)
package.json配置如下：
![image](https://user-images.githubusercontent.com/28948944/123727791-ca0d7000-d8c4-11eb-92e7-9835af2838d6.png)
.fatherrc.jsp配置如下：
![image](https://user-images.githubusercontent.com/28948944/123727836-dc87a980-d8c4-11eb-904c-24dfc38d8c08.png)

**Comment by PeachScript** [comment]
`npm run build:doc`
