### ISSUE TITLE
直接使用father-build包配置esm, esm.file不生效

### ISSUE THREAD

**Issue by zslucky** [umijs/father#372]
在简单debug追踪了一下问题，发现这里的`entry`始终是`string`类型值，因为前面的逻辑已经对数组类型的entry进行了拆分。因此这里的`entry.length`直接用了`string`的`length`, 以至于我无法设置`esm.file`，不知道我的理解是否正确。
![image](https://user-images.githubusercontent.com/15725589/124744606-89ab9300-df51-11eb-8780-f188ca9ba536.png)

**Comment by PeachScript** [comment]
@wangxingkang 有空看下哈

**Comment by zslucky** [comment]
贴下我的配置，方便你们复现问题
![image](https://user-images.githubusercontent.com/15725589/124851820-d46eee80-dfd5-11eb-9b25-93a88c164a16.png)

**Comment by citrusjunoss** [comment]
+1

**Comment by wangxingkang** [comment]
OK

**Comment by wangxingkang** [comment]
先关闭了，有问题再打开吧
