### ISSUE TITLE
配置了cssModules+lessInBabelMode后build结果的css文件没走CSSModules

### ISSUE THREAD

**Issue by sdhr27** [umijs/father#375]
```
// .fatherrc.ts
import themes from './src/components/style/index';

export default {
  esm: 'babel',
  // lessInBabelMode: true,
  // disableTypeCheck: true,
  // cjs: 'rollup',
  cssModules: {
    generateScopedName: '[name]__[local]___[hash:base64:5]',
    scopeBehaviour: 'global',
    globalModulePaths: [/components\//],
  },
  runtimeHelpers: true,
  lessInBabelMode: {
    modifyVars: themes,
    javascriptEnabled: true,
  },
};
```
![image](https://user-images.githubusercontent.com/37827411/126744728-e0025323-9492-4095-852e-2c3afedca475.png)
原文件：
![image](https://user-images.githubusercontent.com/37827411/126744858-f6e689b4-f241-4f17-8d64-02e7f39007a3.png)
导致引用包时，全局样式失效、CSSModules样式被当做全局样式。

**Comment by sdhr27** [comment]
https://github.com/umijs/father/blob/84b61b32983aa1238ba1dc0808160c8964efadf8/packages/father-build/src/getRollupConfig.ts#L168
注意到该文件下的一个貌似是拼写的错误，有关系么？
![image](https://user-images.githubusercontent.com/37827411/126885161-71ac2ce9-59a4-4c80-a70a-e9b1afacb37d.png)

**Comment by PeachScript** [comment]
cssModules 配置项仅支持 rollup 模式

**Comment by sdhr27** [comment]
我使用rollup模式打包后，产物生成了css文件dist/index.esm.css，CSSModules也正确，但是最终引用发布包的时候发现样式没有生效，这是我的.fatherrc文件：
```
export default {
  esm: 'rollup',
  cssModules: true,
  extractCSS: true,
  runtimeHelpers: true,
  lessInRollupMode: {
    modifyVars: themes,
    javascriptEnabled: true,
  },
};

```
@PeachScript 是不是引用包的时候还需要额外配置一下样式？

**Comment by PeachScript** [comment]
@sdhr27 是的，手动引入 css

**Comment by sdhr27** [comment]
> @sdhr27 是的，手动引入 css

但是我手动引用的css文件是没有:global包裹的
![image](https://user-images.githubusercontent.com/37827411/126943185-22e1e34b-fd60-420a-81f1-ddb5b06d12e4.png)
但是项目里开了CSS Modules：
![image](https://user-images.githubusercontent.com/37827411/126943232-42cff51b-a0df-4578-974a-151601fc7b67.png)
所以反而无法生效了，这种情况应该怎么处理呢？

**Comment by sdhr27** [comment]
> > @sdhr27 是的，手动引入 css
> 
> 但是我手动引用的css文件是没有:global包裹的
> ![image](https://user-images.githubusercontent.com/37827411/126943185-22e1e34b-fd60-420a-81f1-ddb5b06d12e4.png)
> 但是项目里开了CSS Modules：
> ![image](https://user-images.githubusercontent.com/37827411/126943232-42cff51b-a0df-4578-974a-151601fc7b67.png)
> 所以反而无法生效了，这种情况应该怎么处理呢？

傻了，应该用js去引用node_modules里的css文件，然后cssModules配置就自动忽略了

**Comment by airwaycai** [comment]
> 

你问题解决了吗

**Comment by hanzhangmin** [comment]
大佬们，怎么解决呀
