### ISSUE TITLE
require.context 异常

### ISSUE THREAD

**Issue by sxfmao** [umijs/father#376]
start 运行加载正常，build之后加载不到

build 之前

![image](https://user-images.githubusercontent.com/32216262/127111400-a2efdb5b-2aaf-47de-b77f-1d10ca862e2a.png)

build 之前
![image](https://user-images.githubusercontent.com/32216262/127111781-eff27d9d-33bc-4082-8114-f54029ff4ffe.png)

**Comment by PeachScript** [comment]
require.context 是 webpack 的特有语法，dev 是 webpack，但构建是 rollup，所以不行；组件库不应该依赖打包工具的语法，建议采用其他方式实现
