### ISSUE TITLE
js中解构css Modules :export报错：Error: 'x' is not exported by xxx.less, imported by yyy.tsx

### ISSUE THREAD

**Issue by sdhr27** [umijs/father#386]
![image](https://user-images.githubusercontent.com/37827411/128958774-5d0f60e8-3d3f-487c-95b7-08b088c738f6.png)
theme.less：
![image](https://user-images.githubusercontent.com/37827411/128958807-07a268be-bd74-4353-ba2f-036d52e0883c.png)
RadioButton.tsx：
![image](https://user-images.githubusercontent.com/37827411/128958840-f5f62b17-8373-4b4a-823b-5c6be1f2d5d4.png)
配置文件：
```
import themes from './src/components/style/index';

export default {
  esm: 'rollup',
  cssModules: true,
  extractCSS: true,
  runtimeHelpers: true,
  lessInRollupMode: {
    modifyVars: themes,
    javascriptEnabled: true,
  },
};
```

**Comment by sdhr27** [comment]
仅发生在解构时，直接引用可以

**Comment by sdhr27** [comment]
![image](https://user-images.githubusercontent.com/37827411/129501215-24f1a211-da9a-49ef-bdab-742427c1c828.png)
添加`namedExports: true`后正常，但是father没有提供配置项供外部配置，能否加个自定义rollup-plugin-postcss配置的配置项？
@PeachScript

**Comment by PeachScript** [comment]
father 4 已发布，可尝试升级到最新版：https://github.com/umijs/father/blob/master/docs/guide/migrate.md

旧版本不再维护，感谢支持
