### ISSUE TITLE
How to config context or onwarn of rollup to avoid annoying warns ?

### ISSUE THREAD

**Issue by gengxuelei** [umijs/father#398]
Hi, I get some warn :

```
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
Circular dependency: node_modules/antd/es/alert/index.js -> node_modules/antd/es/alert/ErrorBoundary.js -> node_modules/antd/es/alert/index.js
```
And I get some tips to solve them. But I don't know how to config them in your lib of `umijs/father`

https://github.com/ant-design/ant-design/issues/27209
https://stackoverflow.com/questions/43556940/rollup-js-and-this-keyword-is-equivalent-to-undefined

Thx

**Comment by PeachScript** [comment]
Add antd into dependencies of the package.json file

**Comment by gengxuelei** [comment]
@PeachScript 
Much appreciate for your reply.
But it seems not work:

![image](https://user-images.githubusercontent.com/11707936/130169404-23846b7f-0839-44ef-9873-577f670c8cae.png)
![image](https://user-images.githubusercontent.com/11707936/130169446-af7e7ccb-bd0e-4d9f-9a09-6ab01ef6f787.png)

I still get these warns:
![image](https://user-images.githubusercontent.com/11707936/130169594-b6affb84-a76f-4127-a87e-b4e9847da18f.png)

**Comment by krmao** [comment]
> Add antd into dependencies of the package.json file

perfect ! all log fixed!
