### ISSUE TITLE
father 打包配置了输出umd格式包，配置了@babel/plugin-transform-runtime 报错

### ISSUE THREAD

**Issue by woshi555bin** [umijs/father#401]
Error: You have declared using "bundled" babelHelpers, but transforming /index.ts resulted in "runtime". 
Please check your configuration. 

@babel/plugin-transform-runtime 中默认配置中开启了helpers :true，会报上述错误

**Comment by woshi555bin** [comment]
建议优化下

**Comment by Jeggery** [comment]
找到解决方法了吗

**Comment by woshi555bin** [comment]
> 找到解决方法了吗

将helpers关闭

**Comment by PeachScript** [comment]
father 4 已发布，可尝试升级到最新版：https://github.com/umijs/father/blob/master/docs/guide/migrate.md

旧版本不再维护，感谢支持
