### ISSUE TITLE
father-build v1.19.8配置pkgFilter报错

### ISSUE THREAD

**Issue by Soundmark** [umijs/father#403]
### 问题描述
1. 通过dumi脚手架搭建一个项目，修改成lerna结构，然后再`.father.ts`中配置`pkgFilter`后打包报错，如下图

![image](https://user-images.githubusercontent.com/57323166/132199570-06194c9b-da05-4592-8b36-1baf659a1496.png)

2. 查看根据报错信息追踪到`node_modules/father-build/src/schema.ts`中发现并无pkgFilter配置项
3. 在仓库的`packages/father-build/src/schema.ts`中则存在pkgFilter配置项

*个人猜测是否该版本打包出了问题*

### 期待修复得到的效果
能够正常配置pkgFilter

**Comment by PeachScript** [comment]
还没发版，今天发下

**Comment by PeachScript** [comment]
之前 `pkgFilter` 功能没发版，已发 `v1.20.0`，可以重装依赖试下
