### ISSUE TITLE
【rollup打包问题】如何将Type-Only写法的ts定义转成低版本支持

### ISSUE THREAD

**Issue by leerle** [umijs/father#404]
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export

打包前
![image](https://user-images.githubusercontent.com/32125150/132678029-4c2bf083-049f-4931-bef2-acf15dfd51e7.png)

打包后的ts定义文件
![image](https://user-images.githubusercontent.com/32125150/132678079-5a58c8c0-597b-4087-80c7-f0894b0a810a.png)

export type的定义在3.8以下的ts中不支持，怎么配置成在打包之后自动去除上图圈中的位置呢

**Comment by leerle** [comment]
@PeachScript

**Comment by leerle** [comment]
配置文件：
![image](https://user-images.githubusercontent.com/32125150/132678555-228d5a5a-6aa3-44e6-b058-7d41c1ec14db.png)

**Comment by PeachScript** [comment]
father 4 已发布，可尝试升级到最新版：https://github.com/umijs/father/blob/master/docs/guide/migrate.md

旧版本不再维护，感谢支持
