### ISSUE TITLE
如何移除 umd 包中，打出的 css 里面的注释呢？

### ISSUE THREAD

**Issue by maquannene** [umijs/father#405]
如题；
文档中没有找到相关的配置项；
![image](https://user-images.githubusercontent.com/8757564/133016969-dc929726-74e4-4f50-bd8d-0b006acc3e43.png)

**Comment by PeachScript** [comment]
father 4 已发布，可尝试升级到最新版：https://github.com/umijs/father/blob/master/docs/guide/migrate.md

旧版本不再维护，感谢支持
