### ISSUE TITLE
dumi引入静态资源，father-build 报错

### ISSUE THREAD

**Issue by jackywq** [umijs/father#406]
图片描述：
![image](https://user-images.githubusercontent.com/21954704/133222037-a1d710f7-4039-4486-a9da-161d13daac1b.png)
![image](https://user-images.githubusercontent.com/21954704/133222147-257e960b-6ab3-4f3d-bab0-a171925d6d83.png)
本地构建展示正常，当执行npm run build, 提示`TypeError: Cannot read property 'replace' of undefined `

**Comment by jackywq** [comment]
@sorrycc @yesmeck 大佬们帮忙看下问题，谢谢

**Comment by PeachScript** [comment]
father-build 是用来做组件库源码构建的，构建文档用 dumi build

**Comment by jackywq** [comment]
> father-build 是用来做组件库源码构建的，构建文档用 dumi build

好的，我试试哈
