### ISSUE TITLE
rollup 打包模式 less里的 图片url 打完之后还是相对路径，请问如何修改配置或者转换成base64!!!

### ISSUE THREAD

**Issue by dongcer** [umijs/father#414]
如题

**Comment by dongcer** [comment]
@PeachScript 恳请解答一下

**Comment by jingkeke** [comment]
我是换个思路,extraRollupPlugins配置 把所有的大图片也转成base64; 

参考 https://github.com/umijs/father/issues/164

**Comment by 1084350607** [comment]
相同的问题，请问怎么处理了
