### ISSUE TITLE
[BUG] eslint^8.0.1 Package subpath './bin/eslint' is not defined by "exports"

### ISSUE THREAD

**Issue by GreatAuk** [umijs/father#415]
eslint 版本： ^8.0.1
```js
// fatherrc.js
export default {
  cjs: {
    type: 'babel',
    minify: true
  },
  esm: { type: 'babel', importLibToEs: true },
  preCommit: {
    eslint: true,
    prettier: true,
  },
  runtimeHelpers: true,
};
```
git commit 后报错
![image](https://user-images.githubusercontent.com/20253809/137258028-0517d389-a912-4aa9-b442-4cf0b75e9e7f.png)

**将 eslint 版本降为 7.30.0 后不报错**

**Comment by PeachScript** [comment]
暂不支持 eslint 8，如果需要使用最新版，建议单独安装 eslint + 配置 precommit hook 使用，下个大版本计划不再提供 `preCommit` 能力
