### ISSUE TITLE
配置 externalsExclude 打包失败，需要额外配置 commonjs 插件

### ISSUE THREAD

**Issue by ltaoo** [umijs/father#416]
项目依赖 `is-buffer`，希望把这个三方包打到产物中，是这样配置的

```js
// .fatherrc.ts
export default {
  cjs: 'rollup',
  externalsExclude: ['is-buffer'],
};
```

打包时出现错误提示

```bash
✖  error     Error: 'default' is not exported by node_modules/is-buffer/index.js, imported by src/index.js
```

排查后发现加上 `commonjs` 插件就正常了，给遇到相同问题的同学一个参考。

```js
//  .fatherc.ts
import commonjs from '@rollup/plugin-commonjs';

export default {
  cjs: 'rollup',
  externalsExclude: ['is-buffer'],
  // 增加这个配置
  extraRollupPlugins: [commonjs()],
};
```

源码中 `getRollupConfig` 中我看只有 `umd` 包会增加 `commonjs` 插件，是特意这样设计的吗？

复现示例
https://stackblitz.com/edit/father-build-without-commonjs?file=.fatherrc.ts
`yarn build` 打包

**Comment by Barretem** [comment]
遇到了相同的问题，确实是加上commonjs的相关插件就正常打包了，感谢！

**Comment by JiaweiUTSCHINA** [comment]
补充说明，father_build(1.21.0)锁了rollup版本在2.33.3，@rollup/plugin-commonjs需要降版本才能用，"@rollup/plugin-commonjs": "^15.1.0"可用
