### ISSUE TITLE
如何使用father build将依赖umi（dva）的源代码打包

### ISSUE THREAD

**Issue by yagang94** [umijs/father#419]
因为项目是用umi搭建的工程且项目中又使用到umi中的一些dva等依赖，目前想将该工程抽离成npm组件包形式输出，但是直接用babel或者rollup打包输出的npm包代码会找不到dva的model。
请教下能不能将依赖的dva源代码直接和工程代码一起打包输出来实现该需求
@sorrycc @yesmeck @afc163 @wadezhan @xudafeng  大佬们，求救！

**Comment by PeachScript** [comment]
打包不了，umi 是开发框架，很多能力是编译时的行为，只能做 external

**Comment by yagang94** [comment]
如果是external的话。 就拿不到dva里面的model了，项目就跑不起来了,想了解下还有没有其他的方案上述的需求呢。😭

**Comment by yagang94** [comment]
@PeachScript  大佬求救
