### ISSUE TITLE
lerna项目，rollup模式下，出现打包产物位置错误

### ISSUE THREAD

**Issue by fengbozhi** [umijs/father#420]
场景lerna搭建项目，安装father-build，react
![image](https://user-images.githubusercontent.com/19235574/140245602-130755a6-fbff-4cd2-82ac-0969979fefe0.png)

**Comment by PeachScript** [comment]
子包间文件相互依赖用了相对路径？

**Comment by fengbozhi** [comment]
> 子包间文件互相依赖用了相对路径？

无依赖关系，此项目知识做测试多包场景

**Comment by fengbozhi** [comment]
改为babel打包，不会有这个问题

**Comment by Fidelgithub** [comment]
请问问题解决了吗，我这里遇到了同样问题，其中一个包依赖了另一个包，不过是通过包的形式不是相对路径

**Comment by PeachScript** [comment]
father 4 已发布，可尝试升级到最新版：https://github.com/umijs/father/blob/master/docs/guide/migrate.md

旧版本不再维护，感谢支持
