### ISSUE TITLE
father-build 构建 vue 使用 jsx 语法，意外引入 react

### ISSUE THREAD

**Issue by victorykong** [umijs/father#421]
![image](https://user-images.githubusercontent.com/50655436/140252227-5b419b48-0947-40d2-ad8d-98e99a23b661.png)
![image](https://user-images.githubusercontent.com/50655436/140252262-1dcf3b41-258d-47bf-a0ff-ba87903dd78e.png)
![image](https://user-images.githubusercontent.com/50655436/140252414-b9b9ef1d-9dfd-4a4f-bc15-a111e195a731.png)

**Comment by PeachScript** [comment]
father 4 已发布，可尝试升级到最新版：https://github.com/umijs/father/blob/master/docs/guide/migrate.md

旧版本不再维护，感谢支持
