### ISSUE TITLE
rollup打包，less样式丢失

### ISSUE THREAD

**Issue by fengbozhi** [umijs/father#422]
配置
![image](https://user-images.githubusercontent.com/19235574/140275115-00c193c2-16e2-40c9-a232-4dc02398e30b.png)

组件文件
![image](https://user-images.githubusercontent.com/19235574/140275190-4fcec2ff-0d0c-46ac-9b2d-e81d590cf84b.png)
![image](https://user-images.githubusercontent.com/19235574/140275220-6aa8c7de-4a89-446b-8086-0efcdb2be28d.png)

打包产物
![image](https://user-images.githubusercontent.com/19235574/140275309-db51504c-0aad-47c4-816a-8e14209a6342.png)
![image](https://user-images.githubusercontent.com/19235574/140275329-1cd0342c-0b2a-44dc-aa19-d25783ed11ba.png)

使用的是dumi提供的组件库模板  https://github.com/umijs/dumi-template 

打包后less，样式丢失

**Comment by fengbozhi** [comment]
复现仓库 https://github.com/fengbozhi/father-error

**Comment by PeachScript** [comment]
样式被 tree-shaking 掉了：https://github.com/fengbozhi/father-error/blob/master/package.json#L42
改成 `['**/*.less']`
