### ISSUE TITLE
【已解决】father快速入门，教你快速打包一个npm模块

### ISSUE THREAD

**Issue by daifuyang** [umijs/father#426]
# 创建项目并初始化
我们需要创建一个新项目（test）并实现初始化。
1.进入test并安装father
```
cd test
npm install father
```
2.初始化项目包
```
npm init
```
3.完成package创建
4.npm link
用于测试
# 配置father
新建.fatherrc.js
这里需要postcss-url处理样式文件的图片路径转换
```
import postcssUrl from 'postcss-url'

export default {
  entry: "src/index.ts",
  esm: {
    type: 'rollup',
  },
  cssModules: {
    generateScopedName: '[local]___[hash:base64:5]',
  },
  extraPostCSSPlugins:[
    postcssUrl({
      url: 'inline'
    })
  ]
};
```
# 可选项（ts支持）
tsconfig.json
```
{
  "compilerOptions": {
    "target": "esnext",
    "moduleResolution": "node",
    "jsx": "react-jsx",
    "esModuleInterop": true
  }
}
```

# 进行测试
npm link [package-name] // npm link test
import Test from 'test';

# 常见问题
css/less的background图片路径问题
通过postcss-url解决
注意postcss-url版本不能太高，目前我使用的是8.0.0

**Comment by PeachScript** [comment]
组件库不建议使用 CSS Modules，用户想复写样式会很困难

**Comment by daifuyang** [comment]
感谢大佬的指正。这块组件如果对样式有要求的话可以不配置cssModules，通过通用css来复写样式
