### ISSUE TITLE
lerna项目rollup模式打包时把包外无关文件都打包进了dist

### ISSUE THREAD

**Issue by Fidelgithub** [umijs/father#430]
![image](https://user-images.githubusercontent.com/17291450/141278460-93bcac1e-f594-4dee-98af-e3c442fdf61d.png)

如图，这个项目里有a和b两个包，打包后a和b的dist产物里都有对方以及外边的mock文件夹。
复现仓库：[reproduce](https://github.com/Fidelgithub/reproduce)

运行下方指令即可复现
```
npm run init
```

**Comment by Fidelgithub** [comment]
tsconfig.json放到包内可以正常打包，看起来应该是没有找到根目录的tsconfig

**Comment by Fidelgithub** [comment]
type.d.ts同样需要在子包放一份，不然打包会包TS2307错误

**Comment by PeachScript** [comment]
> tsconfig.json放到包内可以正常打包，看起来应该是没有找到根目录的tsconfig

根目录的 tsconfig.json 会识别，但 `baseUrl` 指向了根目录的当前目录（`.`），应该是这个原因导致的，可以删掉 `baseUrl` 的配置试试

**Comment by Fidelgithub** [comment]
> > tsconfig.json放到包内可以正常打包，看起来应该是没有找到根目录的tsconfig
> 
> 根目录的 tsconfig.json 会识别，但 `baseUrl` 指向了根目录的当前目录（`.`），应该是这个原因导致的，可以删掉 `baseUrl` 的配置试试

删掉 `baseUrl` 还是没有改变，打包产物和删除前一样

**Comment by Fidelgithub** [comment]
@PeachScript

**Comment by Fidelgithub** [comment]
> > tsconfig.json放到包内可以正常打包，看起来应该是没有找到根目录的tsconfig
> 
> 根目录的 tsconfig.json 会识别，但 `baseUrl` 指向了根目录的当前目录（`.`），应该是这个原因导致的，可以删掉 `baseUrl` 的配置试试

@PeachScript 我看了下，rollup-plugin-typescript2是以tsconfig.json所在文件夹作为识别文件目录的，没有用到`baseUrl`

```javascript
export function parseTsConfig(context: IContext, pluginOptions: IOptions)
{
	const fileName = tsModule.findConfigFile(pluginOptions.cwd, tsModule.sys.fileExists, pluginOptions.tsconfig);
	...
	let baseDir = pluginOptions.cwd;
	...
	if (fileName)
	{
		...
		baseDir = dirname(fileName);
		...
	}

	const mergedConfig = {};
	_.merge(mergedConfig, pluginOptions.tsconfigDefaults, loadedConfig, pluginOptions.tsconfigOverride);

	const preParsedTsConfig = tsModule.parseJsonConfigFileContent(mergedConfig, tsModule.sys, baseDir, getOptionsOverrides(pluginOptions), configFileName);
```

**Comment by PeachScript** [comment]
@Fidelgithub 👍 看起来目前只能在子包放 tsconfig.json 解了
