### ISSUE TITLE
lerna项目，babel模式打包，引用时class样式名丢失

### ISSUE THREAD

**Issue by Fidelgithub** [umijs/father#434]
包内引用less样式
![image](https://user-images.githubusercontent.com/17291450/141927713-94cfeae0-c07b-42dc-858d-9604a8b391a6.png)

页面引用
![image](https://user-images.githubusercontent.com/17291450/141927410-60db1d9c-6a8b-4c40-8981-129617da5b54.png)

渲染结果
![image](https://user-images.githubusercontent.com/17291450/141927883-f83ddec5-d78d-4171-9408-27253a722a19.png)

### 复现仓库
https://github.com/Fidelgithub/reproduce/tree/class-miss

### 复现步骤
通过`npm link`引用即可复现
```javascript
import { PageContainer } from 'a-test';
```

**Comment by PeachScript** [comment]
给项目里的 Umi 配置加上自己的组件库，配置项：https://umijs.org/config#extrababelincludes

**Comment by Fidelgithub** [comment]
> 给项目里的 Umi 配置加上自己的组件库，配置项：https://umijs.org/config#extrababelincludes

赞！
另外这个动作有办法在组件库里做掉吗？想要按需加载，又不想在项目里做多余操作- -

**Comment by PeachScript** [comment]
做不了，组件库不建议用 CSSModules，使用方很难覆写样式
