### ISSUE TITLE
father 4 collaborator invitation

### ISSUE THREAD

**Issue by PeachScript** [umijs/father#435]
感谢你对 father 项目的持续关注，并且打开了这条 issue ❤️

距离 father 上一个 major 版本的发布已经过去了两年多，在这期间打包方案、NPM 社区、组件研发流程等方面都发生了不小的变化，也涌现了许多优秀的同类工具，加上 father 项目已经堆积了大量 issue、且有很大一部分是由于技术方案陈旧导致的，相信你也深有体会 (很想吐槽)。

所以，我们决定开始新一代 father 的设计和研发工作，如果你对此感兴趣，欢迎一起参与 father 4 的建造 🚀

father 4 功能介绍 + 任务集合请访问：https://github.com/umijs/father-next/issues/5

**Comment by chenyulun** [comment]
`father 3`加油
