### ISSUE TITLE
不同文件下引入了同一份less样式，编译后被styleInject注入多次

### ISSUE THREAD

**Issue by XiaoXuan001** [umijs/father#438]
![image](https://user-images.githubusercontent.com/31761281/143516233-a5b1766c-283b-4730-8047-500a124ebab4.png)

![image](https://user-images.githubusercontent.com/31761281/143516262-92d5cedd-f8e7-494b-b87e-f0fc3bacc1e0.png)
该问题如何处理呀

**Comment by PeachScript** [comment]
father 4 已发布，可尝试升级到最新版：https://github.com/umijs/father/blob/master/docs/guide/migrate.md

旧版本不再维护，感谢支持
