### ISSUE TITLE
@babel/plugin-proposal-class-properties 的 loose 配置项似乎未生效

### ISSUE THREAD

**Issue by xiaoiver** [umijs/father#440]
复现仓库：https://github.com/xiaoiver/test-father-build/

https://babeljs.io/docs/en/babel-plugin-proposal-class-properties#loose

father 应该已经开启了 `{loose: true}`，https://github.com/umijs/father/blob/master/packages/father-build/src/getBabelConfig.ts#L80

但是使用 rollup 模式构建出来的 cjs、esm、umd 产物中依然包含 `Object.defineProperty.`：
```js
_createClass(Test, [{
    key: "func",
    value: function func() {}
  }]);
```
https://github.com/xiaoiver/test-father-build/blob/master/dist/index.esm.js#L30-L33

切换成 babel 模式正常：
```js
// 这应该是 loose 模式的正常产物
var Test = function () {
  function Test() {
    this.prop = 1;
  }

  Test.prototype.func = function () {};

  return Test;
}();
```

看起来像是 rollup-babel 这个插件的问题？

**Comment by xiaoiver** [comment]
https://github.com/babel/babel/issues/13292#issuecomment-839101063

Babel `7.13` 使用 [assumptions](https://babeljs.io/docs/en/assumptions) 替代 loose 配置项。希望能早日升级 father-build 的依赖吧，现在是固定了 `7.12`，因此无法使用 `assumptions`。

**Comment by PeachScript** [comment]
father-build 基本不会更新了，father 4 RC 版已发布，可以试用看看：https://github.com/umijs/father-next

**Comment by wozien** [comment]
father v4 怎么配置呀？
