### ISSUE TITLE
使用antd配置@ant-prefix 未生效 

### ISSUE THREAD

**Issue by sountstars** [umijs/father#441]
配置文件 .fatherrc
以下两种都试过 未生效
// lessInRollupMode: {
  //   modifyVars: {
  //     '@ant-prefix': 'kxxxxx',
  //   },
  // },
  // lessInBabelMode: {
  //   modifyVars: {
  //     '@ant-prefix': 'kxxxxx'',
  //   },
  // },

**Comment by PeachScript** [comment]
father 4 已发布，可尝试升级到最新版：https://github.com/umijs/father/blob/master/docs/guide/migrate.md

旧版本不再维护，感谢支持
