### ISSUE TITLE
umd 是否可以只生成压缩版本

### ISSUE THREAD

**Issue by jianfei** [umijs/father#442]
设置了 `{ minFile: true }` 之后, 构建会进行两次。一次正常的，一次压缩的。
当项目构建时间已经很长时，这双倍的时间就更明显了。
请问是否可以配置，只生成压缩版本。

**Comment by PeachScript** [comment]
father 4 RC 版已发布，只会生成压缩版本，可以试用看看：https://github.com/umijs/father-next
