### ISSUE TITLE
npm打包发布后，在安装使用组件库时，组件中引用的静态文件地址依然是根路径下的地址导致访问不到，该如何解决

### ISSUE THREAD

**Issue by scw1997** [umijs/father#455]
例如某图片的地址为/images/xxxx.png。在进行静态站点文档部署后可以访问到，但是如果是组件库的npm包发布后，则组件使用时路径依然是/images/xxx.png。这样在其他项目服务中肯定是访问不到的，这种情况该如何处理？

更新：并且我发现，执行npm build打包时不会打包public中的静态文件，只是在组件中把文件路径添加上去了。这又是什么情况？

**Comment by PeachScript** [comment]
public 是给文档站点用的静态资源目录，和组件库打包的产物无关，组件库的静态资源一般有这几种处理方式：
1. rollup 模式可以借助一些插件把图片转 base64
2. babel 模式把图片当做模块引入，在项目里再进行编译
3. 或者图片托管在 CDN 上

**Comment by yang200258** [comment]
> public 是给文档站点用的静态资源目录，和组件库打包的产物无关，组件库的静态资源一般有这几种处理方式：
> 
> 1. rollup 模式可以借助一些插件把图片转 base64
> 2. babel 模式把图片当做模块引入，在项目里再进行编译
> 3. 或者图片托管在 CDN 上

大佬：
babel 模式把图片当做模块引入

**Comment by AttackXiaoJinJin** [comment]
大哥们解决了吗

**Comment by LeiYao123** [comment]
> > public 是给文档站点用的静态资源目录，和组件库打包的产物无关，组件库的静态资源一般有这几种处理方式：
> > 
> > 1. rollup 模式可以借助一些插件把图片转 base64
> > 2. babel 模式把图片当做模块引入，在项目里再进行编译
> > 3. 或者图片托管在 CDN 上
> 
> 大佬： babel 模式把图片当做模块引入 ![image](https://user-images.githubusercontent.com/38518538/165055439-894e84b1-3402-416c-883c-54b19e45df06.png) 这么引入会报错： ![image](https://user-images.githubusercontent.com/38518538/165055494-90ab280e-c78a-40cd-a87f-9a89a54005c8.png) 我也配置了tsconfig加入images的declare了
@yang200258 
现在最新版本已经没了 rollup , babel 模块导入按照这个 issue 操作也不行，还是把图片放在 cdn 吧
