### ISSUE TITLE
pnpm下如何使用呢

### ISSUE THREAD

**Issue by Loogeek** [umijs/father#462]
你好，使用pnpm管理monorepo项目，没有使用lerna.json管理项目，好像是没办法进行打包

**Comment by PeachScript** [comment]
是的，目前不支持 pnpm；下个大版本会进行自持

**Comment by yanmao-cc** [comment]
lerna 似乎已经不在维护状态了，turborepo rush 后续会支持吗？

**Comment by ityuany** [comment]
@Loogeek  你在项目根目录 新建一个  lerna.json 就可以了。  嘻嘻

**Comment by Loogeek** [comment]
@ityuany 目前也是这样处理，觉得不太优雅

**Comment by PeachScript** [comment]
father 4 不再关心 monorepo 工具，而是和 tsc 一样支持配置文件继承，在子包里各自构建；father 4 RC 版已发布，可以试用看看：https://github.com/umijs/father-next

**Comment by eleven-net-cn** [comment]
> father 4 不再关心 monorepo 工具，而是和 tsc 一样支持配置文件继承，在子包里各自构建；father 4 RC 版已发布，可以试用看看：https://github.com/umijs/father-next

使用了 father@next，pnpm workspaces 的 monorepo 项目，构建没走成功

**Comment by PeachScript** [comment]
Umi 4 是 pnpm，正在切 father 4，供参考：https://github.com/umijs/umi/tree/support/use-father
