### ISSUE TITLE
father-build 打包后 less 样式无效

### ISSUE THREAD

**Issue by DarkForst** [umijs/father#463]
node 版本 v16.13.1
father-build 版本 v1.21.1
``` 
export default {
  esm: 'babel' ,
  cssModules: true,
}
```
```
import style from './style.less';

<div className={style.posBtw}>title</div>
```
## 复现仓库
项目地址 https://github.com/DarkForst/strategy-demo

## 复现步骤
` npm i strategy-demo `
` import { StrategyHeader } from 'strategy-demo' `

**Comment by airwaycai** [comment]
同样的问题，是不支持了还是什么？ "father-build": "1.22.1"版本是这个

**Comment by PeachScript** [comment]
Duplicate of #481
