### ISSUE TITLE
[Feature]是否可以新增clean配置用于控制build时是否清空ouputDir

### ISSUE THREAD

**Issue by 3lang3** [umijs/father#464]
### 场景

在编程式的调用 `father build`和其他构建脚本(eg: gulp workflow)联合工作时，father build强制清理了dist文件夹

### 期望

新增`clean`配置，默认为`true`, 在编程式调用时用户可以进行自定义

如果可行，我可以提PR

**Comment by PeachScript** [comment]
目前在做下个大版本，这个版本不会新增功能了

如果强依赖的话可以先 PR 一个命令行控制参数，比如 `father-build --clean=false`，我们发个版本先临时解你的问题；下个大版本会把 clean 的行为考虑进去

**Comment by 3lang3** [comment]
ok 稍后我提一个

当前 `father build` 的bundless产出(umd)不太能接受，无奈只能自己写script打包umd，下个版本是否有考虑下 bundless这方便的优化？

**Comment by 3lang3** [comment]
@PeachScript 有时间review下pr吗，等着father build发版😀

**Comment by PeachScript** [comment]
+ father-build@1.21.2 可以试试

**Comment by 3lang3** [comment]
@PeachScript 可以了 🙌
