### ISSUE TITLE
babel编译模式下，是否可以添加上postcss支持？

### ISSUE THREAD

**Issue by shen774411223d** [umijs/father#469]
1. 实践发现 切换至 `babel`编译模式后，`extraPostCSSPlugins`参数失效。看了源码发现 `babel`模式下根本没使用extraPostCSSPlugins

2. `babel`基于 `gulp`编译。是否可以暴露出一些`gulp`的自定义让开发者配置呢？原因是 `babel`模式下不能使用`postcss` 但是`gulp`可以支持 `postcss`。而`gulp`又不能修改配置。只能根据 暴露出的 `lessInBabelMode`来为 `gulp-less`增加插件解决`postcss`的使用

**Comment by PeachScript** [comment]
没有这个计划，babel 模式是文件到文件编译，非 js 文件最好都交给实际项目去编译
