### ISSUE TITLE
.docz 的 localUserConfig 读取的依然是 .umirc.library.json

### ISSUE THREAD

**Issue by Lpmvb** [umijs/father#47]
https://github.com/umijs/father/blob/3495fbae889ab44c229efd2d8fca363f648ee742/packages/father/src/doc/docz.ts#L16
https://github.com/umijs/father/blob/3495fbae889ab44c229efd2d8fca363f648ee742/packages/father/src/doc/doczrc.ts#L14

这两处应该是 `fatherrc.json` 吧

**Comment by sorrycc** [comment]
是的。有兴趣可以提 PR 改下，不过这是临时文件，对用户来说是无感的。
