### ISSUE TITLE
构建读取不到全局的scss变量，Undefined variable: "$money

### ISSUE THREAD

**Issue by yangzhen0** [umijs/father#471]
<img width="930" alt="image" src="https://user-images.githubusercontent.com/45879273/161423949-9d9df039-5007-4d9a-ad14-31fec46b4b5d.png">
<img width="959" alt="image" src="https://user-images.githubusercontent.com/45879273/161424030-c56509dd-6b0c-44b2-bd8d-6366b22143ee.png">

请教一下father build如何使用全局的scss变量，现在打包的时候发现他读取不到，我应该怎么配置

**Comment by PeachScript** [comment]
father 4 已发布，可尝试升级到最新版：https://github.com/umijs/father/blob/master/docs/guide/migrate.md

旧版本不再维护，感谢支持
