### ISSUE TITLE
使用babel模式打包，如何自己设置忽略不打包的文件

### ISSUE THREAD

**Issue by jsnobug** [umijs/father#472]
babel 模式下一些文件不会被编译到 es 和 lib 下，包含：

__test__ 目录
fixtures 目录
demos 目录
mdx 文件
md 文件
测试文件，比如 test.js、spec.js、e2e.js，后缀还支持 jsx、ts 和 tsx

看到文档默认有些文件已忽略，是否可以增加配置，自己可以忽略某些文件

**Comment by PeachScript** [comment]
当前版本不支持，下个大版本会支持

**Comment by PeachScript** [comment]
father 4 RC 版已发布，可以试用看看：https://github.com/umijs/father-next
