### ISSUE TITLE
cssModules为true，打包的组件应用的时候，样式没了

### ISSUE THREAD

**Issue by airwaycai** [umijs/father#481]
import styles from './index.less';
less文件内容

.content{
    width: 100%;
    margin: 0 auto 30px;
    padding: 10px 17px 40px 16px;
    background: white;
}

 

结果打包出来，样式没了
<---<div> 111 </div>-->

用的是v1.22.1 father-build

**Comment by airwaycai** [comment]
<div className={styles.transfer}>111</div>

**Comment by airwaycai** [comment]
import styles from './index.less';
less文件内容

.content{
    width: 100%;
    margin: 0 auto 30px;
    padding: 10px 17px 40px 16px;
    background: white;
}


 

结果打包出来，样式没了
<---<div>111</div>-->

用的是v1.22.1 father-build

**Comment by airwaycai** [comment]
<img width="623" alt="image" src="https://user-images.githubusercontent.com/10701733/164365925-b0ef0de3-b77b-48ca-b37c-018dd1811ad0.png">

**Comment by PeachScript** [comment]
1. 组件库不建议使用 CSS Modules，使用方很难覆写样式
2. 强行要用的话，确保引入组件库的项目有编译 node_modules 下的 CSS Modules，比如 Umi 项目要配置 `extraBabelIncludes` 配置项
