### ISSUE TITLE
babel打包带图片资源组件报error TS2307: Cannot find module '../assets/authForbit.png'

### ISSUE THREAD

**Issue by yang200258** [umijs/father#482]
报错信息：
![image](https://user-images.githubusercontent.com/38518538/165052660-d28146c6-db4a-4da0-b6c0-cf208078cb89.png)
![image](https://user-images.githubusercontent.com/38518538/165052696-f286eb40-fd63-4551-9e81-6614fed31fab.png)

tsconfig已加入配置：
![image](https://user-images.githubusercontent.com/38518538/165052409-e9a36f4f-524b-434f-8e58-ad1902e1dcce.png)
images.d.ts文件内容如下：
![image](https://user-images.githubusercontent.com/38518538/165052477-f1d8615b-3fa4-4726-a505-789c021bf46e.png)
使用rollup可以正常打包，但是babel不行

**Comment by wangjingyolo** [comment]
有解决办法了吗？同求

**Comment by yang200258** [comment]
> 有解决办法了吗？同求

暂时没有用babel了。用rollup，

**Comment by kimhou** [comment]
+1

**Comment by PeachScript** [comment]
参考：https://github.com/umijs/father/issues/227#issuecomment-720928000
也可以切换到 father 4 RC，不再有这个怪异的问题：https://github.com/umijs/father-next
