### ISSUE TITLE
提供 terser 配置项

### ISSUE THREAD

**Issue by xiaoiver** [umijs/father#483]
希望能通过配置项关闭例如 terser 的 `unsafe`。
https://github.com/umijs/father/blob/master/packages/father-build/src/getRollupConfig.ts#L152

现在默认开启后，对于 `symbol.toString()` 的改写是不安全的。例如使用 inversify 时：
```js
// raw code
symbol.toString();

// after minified
"symbol" == typeof t ? "" + t : t // throw "TypeError: Cannot convert a symbol to a string"
```
https://github.com/terser/terser/issues/952#issuecomment-1133874871

**Comment by PeachScript** [comment]
father 2 不会新增 feature 了，可以考虑试用 father 4 RC 版：https://github.com/umijs/father-next
