### ISSUE TITLE
sideEffects 配置打开后，umd 构建产物缺少相应的style部分

### ISSUE THREAD

**Issue by ACERY1** [umijs/father#488]
源码是这样的，并且该文件作为变量export出去了。
```js
import './index.less'

// do something
```

然后 `package.json`里配置的`sideEffects` 是: `['*.css', '*.less']`

fatherrc里面的相应umd配置是这样的：

```
          umd: {
            minFile: false,
          },
```

但是最后在看构建产物的时候，发现css部分没有打进去，不知道为什么

**Comment by PeachScript** [comment]
rollup 识别的有效语法是 `**/*.css`，和 webpack 不一致
