### ISSUE TITLE
安装依赖时会删除node_modules

### ISSUE THREAD

**Issue by CaptainJon** [umijs/father#491]
我是使用@umijs/create-dumi-lib创建的组件库，发现每次安装某个依赖的时候，会自动清空大部分的node_modules，但是也不会完全清空，只会清除大概80%，导致每次新增依赖都要重新npm install。问dumi表示dumi不会导致这种情况，因为dumi不负责打包，请问这是什么原因呢？
win10系统，dumi@1.1.0，father-build@1.17.2

**Comment by PeachScript** [comment]
复现不了，father 4 已发布，可升级到最新版试下：https://github.com/umijs/father/blob/master/docs/guide/migrate.md
