### ISSUE TITLE
esm为babel时，cssModules无效

### ISSUE THREAD

**Issue by xieyt203** [umijs/father#498]
当esm为babel时，cssModules无效。
![image](https://user-images.githubusercontent.com/47019192/185097103-15671070-4cbe-4d7b-a76a-22714a4a9cca.png)
![image](https://user-images.githubusercontent.com/47019192/185097236-319a505b-c3bc-4ab4-8ff9-61e16cfc455f.png)
打包后less的名称没有增加前缀，要怎么做才能在esm为babel时使cssModules有效呢？？
PS：在esm为rollup时有效，但是组件库中存在不可避免的循环引用，打包后在项目中运行加载组件库时会报错。

**Comment by GreatAuk** [comment]
+1 ，正好遇到了

**Comment by PeachScript** [comment]
babel 模式处理不了 CSSModules，组件库也不建议使用 CSSModules
