### ISSUE TITLE
.fatherrc.ts是否可以支持modifyVars？

### ISSUE THREAD

**Issue by slevisp** [umijs/father#499]
我在使用
dumi： 1.1.47，
father：4.0.0-rc.9

我在 .umirc.ts 中使用了babel-plugin-import，并且在theme字段里覆盖了less 变量。
请问在 .fatherrc.ts中同样使用babel-plugin-import，有没有办法也可以覆盖less变量？

**Comment by PeachScript** [comment]
仅 umd 构建可配置：https://github.com/umijs/father/blob/master/docs/config.md#theme
