### ISSUE TITLE
father not support remove `console.log` code

### ISSUE THREAD

**Issue by hackftz** [umijs/father#503]
in my dumi project, run the `father build` I get the output files, but I found the `console.log` code didn't get removed, so how to fix the problem?

**Comment by PeachScript** [comment]
For umd and esm/cjs with babel transformer, using `extraBabelPlugins`, add this: https://babeljs.io/docs/en/babel-plugin-transform-remove-console/

For esm/cjs with esbuild transformer, it is not supported yet
