### ISSUE TITLE
打包完并未生成 .d.ts 声明文件

### ISSUE THREAD

**Issue by wubostc** [umijs/father#505]
不知哪里有问题？
```js
import { defineConfig } from 'father'
export default defineConfig({
  esm: {
    output: 'esm',
  },
  cjs: {
    output: 'cjs',
  },
  umd: {
    output: 'dist',
  }
});
```

**Comment by PeachScript** [comment]
如果是走脚手架生成的，提供最小可复现仓库；如果是自己创建的，检查 tsconfig.json 是否配置了 `declaration: true`

**Comment by wubostc** [comment]
> 如果是走脚手架生成的，提供最小可复现仓库；如果是自己创建的，检查 tsconfig.json 是否配置了 `declaration: true`

我发现指定 output 属性时，不会生成声明文件
我参考脚手架生成的文件 .fatherrc.ts，改成input就好了，是个bug？

```js
export default defineConfig({
  esm: {
    input: 'src',
  },
  cjs: {
    input: 'src',
  },
  umd: {
    output: 'dist',
  }
});
```

**Comment by PeachScript** [comment]
用脚手架 + 设置 `output` 复现不了；可以提供最小可复现仓库，只贴配置不足以复现问题

**Comment by qingxiao** [comment]
估计是查找 tsconfig.json 路径问题，如果配置了产出目录只有一级，估计是找不到tsconfig.json, 读取的`declaration: undefined`,
把output改成如下，可以生成d.ts
```
  esm: {
    input: 'src', 
    output: './es/', // ================ 这里路径加个末尾 '/'
    platform: 'browser', 
    transformer: 'babel'
  }
```

**Comment by PeachScript** [comment]
> 把output改成如下，可以生成d.ts

这个解法不科学、也没法理解原因，可以贴一下最小复现仓库我们看下

**Comment by qingxiao** [comment]
再次更新下：开始项目没配置     `declaration": true` 执行过build， 添加配置 `    "declaration": true, ` 后 不生效，需要删除node_modules后重装。

**Comment by NicoKam** [comment]
我去掉 noEmit: true 就好了
