### ISSUE TITLE
father从1升级到4，打包后使用svg作为jsx报错

### ISSUE THREAD

**Issue by wanzijinx** [umijs/father#509]
源代码：
![image](https://user-images.githubusercontent.com/28819509/188839960-2793c92d-3b56-4067-99a0-a610c75d2182.png)
打包后使用报错：
![image](https://user-images.githubusercontent.com/28819509/188840045-4b012320-e6d8-4ab7-b8e9-3495dbea934e.png)
![image](https://user-images.githubusercontent.com/28819509/188840117-f4bf9337-a720-4a62-a311-672a186ae9ec.png)
配置：
![image](https://user-images.githubusercontent.com/28819509/188840339-4094ed49-5f24-489a-bcb7-636a1528eaa3.png)
版本：
"father": "^4.0.0",

**Comment by PeachScript** [comment]
提供下最小复现仓库

**Comment by panfei15623** [comment]
遇到了同样问题，使用 dumi2 搭建组件库，father4 打包，xx组件中将 svg 作为 React 组件引用：
import { ReactComponent as CheckedIcon } from '../../assets/checkbox-checked.svg'

dumi 启动文档，svg 图标正常显示，项目中引用 xx组件，svg 图标报错：（svg 没被导出成组件）
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

**Comment by panfei15623** [comment]
好的，多谢。
不过导致出现问题的原因是，father 配置生成 esm，但是构建产物确是 cjs （这个很奇怪，已无法复现），导致项目中使用组件的时候 svg 报错。
export default defineConfig({
  esm: { output: 'esm' },
});
------
最终将组件库中 node_modules 删掉，重新安装依赖，再构建，生成了 esm 产物，因为项目中打包工具处理 了 svg，所以恢复正常。

**Comment by ynmlqdl** [comment]
> > `import { ReactComponent as XX }`这是 svgr loader 的解决方案，dumi 2 集成 svgr loader 是为了主题包开发，组件库不建议这么写，除非以下两种情况：
> > 
> > 1. 只给特定项目消费并且项目已经集成了 svgr loader
> > 2. 只创建了 umd 产物并通过`chainWebpack`为父亲配置了 svgr loader
> 
> 组件库中用到svg作为react组件引入，不写成`import { ReactComponent as XX }`，文档会报错

但是如果非要用SVGR处理方式写应该怎么解决呢？

**Comment by ynmlqdl** [comment]
> > `import { ReactComponent as XX }`这是 svgr loader 的解决方案，dumi 2 集成 svgr loader 是为了主题包开发，组件库不建议这么写，除非以下两种情况：
> > 
> > 1. 只给特定项目并且消费项目已经集成了 svgr loader
> > 2. 只创建了 umd 产物并通过`chainWebpack`为父亲配置了 svgr loader
> 
> 组件库中用到svg作为react组件引入，不写成`import { ReactComponent as XX }`，文档会报错

但是如果非得用这种方式引入svg应该怎么解决呢？

**Comment by ynmlqdl** [comment]
> 遇到类似问题，使用 dumi@2.0.13 搭建组件库，father@4.1.0 打包，xx组件中将 svg 作为 React 组件引用： import { ReactComponent as IconChecked } from '../../assets/checked.svg'
> 
> dumi 启动文档，svg 图标正常显示，项目中引用 xx组件，svg 图标报错：（svg 没被导出成组件） Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

我在项目引用了这种方式导入的svg后的组件，控制台报错就是这个，怎么搞QAQ

**Comment by ynmlqdl** [comment]
> `import { ReactComponent as XX }` 这是 svgr loader 的用法，dumi 2 集成 svgr loader 是为了主题包开发，组件库不建议这么写，除非以下两种情况：
> 
> 1. 只给特定项目消费且项目已经集成了 svgr loader
> 2. 只产出 umd 产物且通过 `chainWebpack` 为 father 配置了 svgr loader

不太明白您的意思，我dumi组件库中有个组件就是用的这种导入的svg，有办法解决吗，报错就是上述的那个Warning...求~

**Comment by ynmlqdl** [comment]
> 遇到类似问题，使用 dumi@2.0.13 搭建组件库，father@4.1.0 打包，xx组件中将 svg 作为 React 组件引用： import { ReactComponent as IconChecked } from '../../assets/checked.svg'
> 
> dumi 启动文档，svg 图标正常显示，项目中引用 xx组件，svg 图标报错：（svg 没被导出成组件） Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

和我遇到的问题一毛一样，dumi预览啥问题没有，放进项目中报错QAQ

**Comment by shanyijin2** [comment]
father支持extraBabelPlugins了嘛，可以在build的时候处理svg资源，
比如？
`  extraBabelPlugins: [
    [
      'inline-react-svg',
      {
        svgo: {
          plugins: [
            {
              name: 'preset-default',
              params: {
                overrides: {
                  removeViewBox: false,
                },
              },
            },
            'removeDimensions',
            'convertStyleToAttrs',
          ],
        },
      },
    ],
  ]`
