### ISSUE TITLE
v4版本 umd打包 怎么使用terser进行压缩呢

### ISSUE THREAD

**Issue by hnxyhcz** [umijs/father#516]
我现在使用的v4.0.5版本，umd打包，想使用terser进行压缩，但是不知道怎么配置

**Comment by PeachScript** [comment]
默认就是 terser

**Comment by hnxyhcz** [comment]
好的谢谢，然后就是我看打包中有console.log，在配置中加了这段，貌似并没有将console.log移除
![image](https://user-images.githubusercontent.com/10190358/191014418-f4dfee01-5067-40d7-9903-3500411d0312.png)

**Comment by fz6m** [comment]
```ts
export default {
  umd: {
    extraBabelPlugins: ['...']
  }
}
```

**Comment by hnxyhcz** [comment]
额额我的错，没注意到extraBabelPlugins是公共配置，还以为是直接配置到外面。谢谢~
