### ISSUE TITLE
配置项如果没有 prebundle， 就不会生成 declaration 文件

### ISSUE THREAD

**Issue by GreatAuk** [umijs/father#519]
<img width="341" alt="image" src="https://user-images.githubusercontent.com/20253809/192077479-da2da11f-cfed-4056-b1ed-32a4209e56da.png">
如果没有 `prebundle`, `build` 时就不生成 declaration file。

**Comment by wangxingkang** [comment]
是不是 tsconfig.json 没设置 declaration: true

**Comment by wangxingkang** [comment]
提供个最小复现吧
