### ISSUE TITLE
需要 css 注入 到js 文件中，不成功

### ISSUE THREAD

**Issue by cgaof** [umijs/father#520]
![image](https://user-images.githubusercontent.com/29372321/192556694-73f790a9-7d8f-40c6-a897-ab4710fc8522.png)
代码如 上图， 一直注入不了

**Comment by cgaof** [comment]
![image](https://user-images.githubusercontent.com/29372321/192558982-cf53319b-61f6-4ece-b97c-ddc378414ddb.png)
改成 less 也是不能注入

**Comment by PeachScript** [comment]
要删 mini-css-extract-plugin 才行，后续版本考虑把配置项加回来

**Comment by fz6m** [comment]
```ts
export default {
  umd: {
    styleLoader: {}
  }
}
```

**Comment by cgaof** [comment]
> 要删 mini-css-extract-plugin 才行，后续版本考虑把配置项加回来

![image](https://user-images.githubusercontent.com/29372321/192668593-c7a9b632-db3c-4697-b0b1-bb5e095251fa.png)
删除 会报错，报找不到 这个插件

**Comment by cgaof** [comment]
> 要删 mini-css-extract-plugin 才行，后续版本考虑把配置项加回来

![image](https://user-images.githubusercontent.com/29372321/192668757-79c8c467-98ff-43c0-bd01-66f4a3437840.png)
删除 会报，找不到这个插件

**Comment by wangxingkang** [comment]
问题已处理

**Comment by cgaof** [comment]
> 问题已处理

需要 重新 拉取版本吗？

**Comment by PeachScript** [comment]
稍等，预计下午发版

**Comment by PeachScript** [comment]
v4.0.6 已发布，umd 支持 extractCSS 配置项：https://github.com/umijs/father/blob/master/docs/config.md#extractcss
