### ISSUE TITLE
请问怎么打包主题文件

### ISSUE THREAD

**Issue by maoxuanlong** [umijs/father#524]
[](https://gitee.com/shuaishao/and-theme)
[https://gitee.com/shuaishao/and-theme](url),
类似这样子的主题

**Comment by PeachScript** [comment]
这只是普通的 js 模块，正常打包即可，具体问题是什么

**Comment by maoxuanlong** [comment]
我在执行build命令时候把我在src目录下的less文件同时放到dist/cjs或者dist/esm目录下面，谢谢

**Comment by PeachScript** [comment]
bundless 的 input 目录下的 less 默认就会 copy 输出，如果有问题提供最小复现仓库及步骤，先关闭了

**Comment by BennieMeng** [comment]
看文档bundless 会对非js 文件直接输出，看md文件没有做处理。
