### ISSUE TITLE
[Feature Request] 支持配置去除 import 样式文件语句

### ISSUE THREAD

**Issue by moecasts** [umijs/father#525]
在打包组件库的时候，希望样式文件能被完全分离，将控制权完全交给用户。

目前打包后的文件还是保留了 `import 'xxx.css'` 语句，能不能配置成去掉呢？

**Comment by PeachScript** [comment]
属于特定场景需求，暂不在框架内置能力的考虑范围内，两种建议解法：
1. 和 antd v4 类似，需要同步引入样式时、使用 babel-plugin-import 来载入样式，源码里不包含 css 引入语句
2. 源码里保留 css 引入语句，自己写一个 babel plugin 在 father 构建时把 css 语句去掉
