### ISSUE TITLE
4.x版本的如何把less编译成css 

### ISSUE THREAD

**Issue by cgaof** [umijs/father#529]
1. 目前 编译出来的 esm 产物，less 没有 编译成css。 其他项目中(没有配置less) 使用报错。
2.  如果 用umd 形式 ，会都打包到一起。多个业务组件会打包到一起。
3.  用 esm 形式 有没有办法 less 变成 css ?

**Comment by PeachScript** [comment]
不支持，bundless 暂不考虑编译非 JS 文件，ref: https://github.com/umijs/father/issues/514#issuecomment-1246148925
