### ISSUE TITLE
cssModules配置会导致antd样式加载失败

### ISSUE THREAD

**Issue by chj-damon** [umijs/father#53]
重现的github地址：https://github.com/chj-damon/umi-father-issue-reproduce-demo.git

issue发生的环境：windows，macOS上表现正常

重现步骤：
clone项目之后，yarn install && yarn doc:dev
执行之后在打开的页面发现，windows下浏览器看到Antd的Button的样式没有加载，macOS下antd的button样式正常加载；
打开.fatherrc.js，将cssModules注释掉，然后再次运行yarn doc:dev，在打开的页面发现,windows和macOS的浏览器里面，antd的button的样式都正常加载。

所以我怀疑cssModules这个配置项会导致extraBabelPlugins引入的插件有bug

**Comment by daivdggdev** [comment]
我们也遇到这个问题，没有解答吗

**Comment by chj-damon** [comment]
我目前的需求不需要打包，所以就暂时把cssModule的配置去掉了。

**Comment by fodurrr** [comment]
I have the same issue, when cssModules set true in the config then antd styles are not loaded just my own styles.
Can you help?

**Comment by shengbeiniao** [comment]
应该和css modules无关，是antd的问题，如果组件引用了antd，会导致样式不加载

**Comment by shengbeiniao** [comment]
在组件index.js中最上面引入antd样式
```
import 'antd/dist/antd.css'
```

**Comment by Heshiyu1996** [comment]
> 在组件index.js中最上面引入antd样式
> 
> ```
> import 'antd/dist/antd.css'
> ```

试过这种，但会影响引用方的其它页面样式

**Comment by PeachScript** [comment]
组件库研发不建议启用 CSSModules，这样使用方很难对样式进行复写；另外，推荐使用 dumi + father-build 进行组件库研发：https://d.umijs.org/guide/getting-started
