### ISSUE TITLE
文档 build-mode 有个地方表达错误

### ISSUE THREAD

**Issue by CasualMing** [umijs/father#531]
![image](https://user-images.githubusercontent.com/40878104/196083473-402c8a22-42b0-4f96-9450-2bedc757a62c.png)
这里的
> 可以发现，在 Bundless 模式下，father 会对源码进行打包，最后输出压缩后的 JavaScript 产物和 CSS 产物。

是不是应该是

> 可以发现，在 Bundle 模式下，father 会对源码进行打包，最后输出压缩后的 JavaScript 产物和 CSS 产物。

**Comment by PeachScript** [comment]
感谢指出，已更正，后续发现问题也可以直接提 PR 帮忙完善
