### ISSUE TITLE
基于antd 二次封装问题

### ISSUE THREAD

**Issue by alexzzn** [umijs/father#536]
`    "father": "^4.0.7"`的版本
#### 使用antd 的组件后，出现hooks 报错
<img width="500" alt="iShot_2022-10-20_23 31 19" src="https://user-images.githubusercontent.com/41319735/196992943-ba7ec84c-560b-46e2-b563-1fca18cb8e2a.png">
<img width="500" alt="iShot_2022-10-20_23 30 30" src="https://user-images.githubusercontent.com/41319735/196992948-028e445a-5ac5-46c5-be6b-3d2e7c290f7d.png">

#### 不使用antd 的组件正常，可以显示自定义组件
<img width="500" alt="iShot_2022-10-20_23 31 34" src="https://user-images.githubusercontent.com/41319735/196992935-59025eaa-911c-4967-bf68-c77ba04fecdd.png">
<img width="500" alt="iShot_2022-10-20_23 32 20" src="https://user-images.githubusercontent.com/41319735/196992927-df53c7b5-c7ab-49d6-9c65-66f40da65787.png">

**Comment by fz6m** [comment]
给个复现，多 react 实例问题可能是 多版本、没有 peer、monorepo 等多种原因引起的。

**Comment by alexzzn** [comment]
应该是npm link调试导致的，把node_moudles也链接过来了。
