### ISSUE TITLE
支不支持esbuild配置项？

### ISSUE THREAD

**Issue by kw214** [umijs/father#541]
支不支持esbuild配置项？

**Comment by PeachScript** [comment]
不支持，要改什么配置

**Comment by kimmy214** [comment]
开发了一个组件库，底层用到了antd 和 react，引用打包出来的组件报错。但是使用esbuild打包就正常。

![截屏2022-10-25 18 10 37](https://user-images.githubusercontent.com/19725091/197746583-3d317aac-2429-4b00-8a60-8d335a900210.png)

**Comment by PeachScript** [comment]
如果产物是 umd、检查 externals 配置项；如果产物不是 umd、检查类型声明有没有问题，参考：https://github.com/umijs/father/issues/537#issuecomment-1287017434

father 4 的 esbuild 只支持 bundless，暂不考虑开放配置项，应该也和你遇到的问题无关

**Comment by kimmy214** [comment]
已经这样设置了。

**Comment by PeachScript** [comment]
提供下复现仓库和步骤吧

**Comment by kimmy214** [comment]
1、克隆仓库 `https://github.com/kimmy214/father-issue`
2、执行，`yarn`
3、执行  `yarn build`
4、执行  `yarn link`

5、克隆仓库 `https://github.com/kimmy214/nextjs-father-issue`
6、在此仓库下执行，`yarn`
7、在`dependencies`中添加 `"father-issue": "0.0.1-alpha.0"`
8、执行 `yarn link "father-issue"`
9、执行  `yarn dev`
10、访问  `http://localhost:3000/test`

**Comment by kimmy214** [comment]
@PeachScript 有任何进展吗？
