### ISSUE TITLE
rollup不支持后有什么替换方案或者升级建议么？

### ISSUE THREAD

**Issue by lihqi** [umijs/father#542]
非常nice的升级！！！
想把项目中用到father-build 从 1.17.2升级到father v4
遇到的问题就是项目中用到的rollup插件比如rollup-plugin-copy有替换的方案嘛？
目前输出 ESModule

**Comment by PeachScript** [comment]
感谢认可，但 esm 目前都是 bundless 了、而 rollup 是 bundle 的，所以没有替代方案；不过 bundless 的情况下 copy 也用不到了，默认会把 src 下非 js 文件 copy 到产物目录

具体可以看下构建模式的文档：https://github.com/umijs/father/blob/master/docs/guide/build-mode.md
