### ISSUE TITLE
是否可以支持读取babelrc的配置

### ISSUE THREAD

**Issue by JoeWrights** [umijs/father#543]
现在遇到一个问题：组件中有中文字符，按cjs打包出来中文字符变成了unicode，组件在umi项目里引用报错
<img width="919" alt="image" src="https://user-images.githubusercontent.com/38278949/199272822-63f51ca4-726c-4d89-87fb-3d416c9622d6.png">
 
现在想的是能不能自定义除babel plugin或者presets以外的配置呢，或者umi那边有什么好的处理方法

**Comment by fz6m** [comment]
和 https://github.com/umijs/father/pull/538/files#r1002610497 这个问题同样

**Comment by PeachScript** [comment]
v4.1.1 把 esbuild 默认改成 utf-8 了，可以再试下

**Comment by PeachScript** [comment]
我这里测试是 OK 的，如果装依赖不是删掉 node_modules 再装的话，可能是持久缓存的缘故，删掉 node_modules/.cache 再试下

**Comment by JoeWrights** [comment]
> 我这里测试是 OK 的，如果装依赖不是删掉 node_modules 再装的话，可能是持久缓存的缘故，删掉 node_modules/.cache 再试下

重新试了下，可以了
