### ISSUE TITLE
father4 中对monorepo的打包推荐如何写配置呢？

### ISSUE THREAD

**Issue by ytftianwen** [umijs/father#545]
monorepo多个包该如何配置input呢？
<img width="1252" alt="image" src="https://user-images.githubusercontent.com/13484089/200454315-d57a2791-8e86-42bc-8215-9a701d2746cf.png">

**Comment by PeachScript** [comment]
`.fatherrc.ts` 支持 extends，推荐方式是每个子包单独配构建脚本、单独跑 `father build`、配置继承根目录的 `.fatherrc.ts`

**Comment by GuanJdoJ** [comment]
@PeachScript 能否给个monorepo的example

**Comment by PeachScript** [comment]
可以参考 https://github.com/umijs/umi
