### ISSUE TITLE
father4 是否支持 React 17 的 JSX transform？

### ISSUE THREAD

**Issue by Codennnn** [umijs/father#546]
在我的 React 组件中，没有显式引入 `import React from 'react';`。

在 father4 的 Bundless 模式下，如何配置才能正确转换？

期望编译结果：

```js
import {jsx as _jsx} from 'react/jsx-runtime';
```

**Comment by PeachScript** [comment]
支持，根据实际情况在 package.json 的 dependencies 或者 peerDependencies 里声明类似 >= 17.0.0 的 react 版本即可
