### ISSUE TITLE
father dev 会意外中断

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/father#547]
![image](https://user-images.githubusercontent.com/11746742/202725474-40c6a840-f5cc-4cd9-97b7-20ff8d857353.png)

配置如下

```
import { defineConfig } from 'father';

export default defineConfig({
  plugins: ['father-plugin-dumi-theme'],
});

```

**Comment by xiaohuoni** [comment]
复现步骤：dumi 主分支 
```bash
cd suites/theme-mobile
pnpm dev
```
开发一段时间会偶尔中断，重启（pnpm dev）恢复，开发一段时间还会中断。非毕现，可待留院观察

**Comment by PeachScript** [comment]
v4.1.3 应该修复了，后续遇到再 open
