### ISSUE TITLE
bug:father build无法打包Less样式

### ISSUE THREAD

**Issue by heshuo527** [umijs/father#551]
https://github.com/heshuo527/hs-design 源码地址
结果我把father版本降成了2.xx才可以将less文件打包成css样式,但是引用的话必须每个组件单独引入样式, 希望官方解决一下这个bug

**Comment by fz6m** [comment]
bundleless 只转译，不打包。需要使用宿主项目支持 `less` 。

或者打成 umd 格式的包。
