### ISSUE TITLE
esm sourceMappingURL 

### ISSUE THREAD

**Issue by zoro-r** [umijs/father#553]
esm 打包出来的文件 sourceMappingURL 不对
```
实际打包结果
//# sourceMappingURL=index.js

应该是

//# sourceMappingURL=index.js.map
```

**Comment by PeachScript** [comment]
请提供复现步骤或复现仓库

@2239559319 有空看看吗

**Comment by zoro-r** [comment]
![image](https://user-images.githubusercontent.com/20312469/205604841-636c6c32-e893-4f28-99fb-6530449dd136.png)

官方的demo就行 这里的sourceMappingURL应该是.js.map吧

**Comment by PeachScript** [comment]
v4.1.1 已发布，包含该修复

**Comment by G233** [comment]
升级到最新的版本依然遇到了这样的问题，这是我的配置文件
```ts
import { defineConfig } from 'father';

export default defineConfig({
    platform: 'browser',
    cjs: {
        sourcemap: true,
        input: 'src',
        transformer: 'babel',
        output: 'dist'
    }
});

```

但是也不是全部的文件都有问题
<img width="1522" alt="image" src="https://user-images.githubusercontent.com/39009225/223353065-291957c4-49d0-4095-b8e6-0e8b1d7bbbd1.png">

看了下源码是 js 的文件就会出现这个问题？

**Comment by YangsonHung** [comment]
![Image](https://github.com/user-attachments/assets/c9f52c43-9f0d-4033-8b0a-c9e936de9fde)

我的4.5.3 最新遇到这个问题，js文件就会？
