### ISSUE TITLE
如何使用father4 打包vue use jsx模式

### ISSUE THREAD

**Issue by SamWeichangyue** [umijs/father#558]
###基于vue 和 element-plus 二次封装组件库
.fatherrc.ts 配置 如下
``` 
esm: {
  input: 'src', // 默认编译目录
  output: 'es',
  platform: 'browser', // 默认构建为 Browser 环境的产物
  transformer: 'babel', // 默认使用 babel 以提供更好的兼容性
}
```
得到如下报错
<img width="1731" alt="image" src="https://user-images.githubusercontent.com/30724369/206449031-7f826d81-255b-4d05-9a47-075ed2a55cc1.png">

**Comment by PeachScript** [comment]
Duplicate of #210
