### ISSUE TITLE
antd组件用rollup打包失败

### ISSUE THREAD

**Issue by playedclass** [umijs/father#56]
![image](https://user-images.githubusercontent.com/3337266/60884178-de42a780-a27e-11e9-83cf-608338b27f82.png)

**Comment by sorrycc** [comment]
看不懂你的问题，给复现步骤后再 reopen 吧。

**Comment by playedclass** [comment]
> 看不懂你的问题，给复现步骤后再 reopen。

![image](https://user-images.githubusercontent.com/3337266/60933800-792a9880-a2f6-11e9-9864-ce815cf54672.png)

用message组件做的测试，babel打包没有问题，用rollup就提示上面那个错误。
测试了下，应该是调用Notification.newInstance这个方法时引起的

**Comment by playedclass** [comment]
看了下源和文档，找到问题了
![image](https://user-images.githubusercontent.com/3337266/61166834-2ad00080-a567-11e9-9d74-a76b560ed876.png)
