### ISSUE TITLE
本地样式生效（classnames+less），打包之后样式缺失（class为空）

### ISSUE THREAD

**Issue by xingxiaoxingxing** [umijs/father#563]
本地运行：
![image](https://user-images.githubusercontent.com/38177803/209913131-13cec220-61c5-43cb-86d6-1920b841d351.png)
本地代码：
![image](https://user-images.githubusercontent.com/38177803/209913217-7ac56689-8b5b-49c9-9447-85cdf978985d.png)

打包之后：
![image](https://user-images.githubusercontent.com/38177803/209913073-4c413988-6d9d-4bd8-88e7-90a239548657.png)

**Comment by PeachScript** [comment]
这是 CSS Modules 写法，在 UI 资产研发场景下不是好选择、father 不作支持，请改用传统写法，例如：

```
// index.less
.selector { xxx }

// index.tsx
<div className="selector" />
```
