### ISSUE TITLE
Support typescript 4.9 `satisfies`

### ISSUE THREAD

**Issue by fz6m** [umijs/father#564]
目前在 umi 里想用这个。需要 esbuild > `[0.15.13](https://github.com/evanw/esbuild/releases/tag/v0.15.13)`

**Comment by PeachScript** [comment]
father 用的 bundler-utils 提供的 esbuild，看版本是大于 0.15.13 的，不能正常工作吗，https://github.com/umijs/umi/blob/master/packages/bundler-utils/package.json#L24

**Comment by fz6m** [comment]
后续我调查下 😭
