### ISSUE TITLE
father打包替换ant-prefix后，Upload组件样式丢失

### ISSUE THREAD

**Issue by cuitianze** [umijs/father#568]
🐛 bug 描述

father打包替换ant-prefix后，Upload组件样式丢失
![image](https://user-images.githubusercontent.com/5918515/212674334-66bf655e-210f-4bf8-9aa0-51728bab3cd8.png)

🏞 期望结果

组件库独立运行时是正常的:
![image](https://user-images.githubusercontent.com/5918515/212674754-903c8748-43dd-4566-8f20-e7ad8a73a36a.png)

📷 复现步骤
```
export default {
  umd: {
    name: '@didi/woody-open-spa-test',
    theme: { 'ant-prefix': 'woody' },
    externals: {
      react: 'react',
      'react-dom': 'react-dom', 
    },
  },
};
```

© 版本信息
"antd": "^4.18.3"
father@4.1.3

**Comment by cuitianze** [comment]
仅Upload组件存在问题，其他组件没问题

**Comment by fz6m** [comment]
是多 antd 实例了吗，用 alias 锁 antd 位置后再确认下。

**Comment by cuitianze** [comment]
> 是多 antd 实例了吗，用 alias 锁 antd 位置后再确认下。

场景是
React写的组件（依赖"antd": "^4.18.3"）通过father构建产出npm包，提供给其他团队的vue2项目（依赖"ant-design-vue": "^1.7.7" ）

**Comment by fz6m** [comment]
这样是不行的，因为 umd 打的时候 antd 会被打进去，是一份实例。

而 antdv 那边的接口也和 antd 不一样，这俩天生就是俩，没法互操作

**Comment by cuitianze** [comment]
> 这样是不行的，因为 umd 打的时候 antd 会被打进去，是一份实例。
> 
> 而 antdv 那边的接口也和 antd 不一样，这俩天生就是俩，没法互操作

React提供的组件是自闭环的，为了避免样式冲突，React依赖的ant替换了ant-prefix，
外部的Vue2工程通过CustomEvent消息去控制React组件的显示/隐藏，目前已经集成成功了，
只是React依赖的ant在替换prefix打包后丢了Upload组件相关的样式，其他组件的样式都是正常的。

我这边目前采用在React工程里copy了一份ant库upload样式并替换了前缀，在Vue2工程里显示正常。
.ant-upload > .woody-upload 

目前猜想还是在打包的什么阶段丢了这部分样式造成的。

**Comment by fz6m** [comment]
配了 ConfigProvider 么。

**Comment by PeachScript** [comment]
长时间无响应，issue 关闭，如果仍有问题请提供最小可复现仓库
