### ISSUE TITLE
build ts-babel-css-cssModule get error

### ISSUE THREAD

**Issue by DiamondYuan** [umijs/father#57]
![image](https://user-images.githubusercontent.com/9692408/60902172-c7617c80-a2a1-11e9-863b-d789c70f8d68.png)

例子
https://github.com/webclipper/ecosystem/tree/87ba47fddf6f5aabb31ec5b133ac02b2fd95462a

**Comment by DiamondYuan** [comment]
临时解决方案
css 上面加 
```
//@ts-ignore
```

**Comment by aizigao** [comment]
同样的问题，需要babel后, css module完全没有生效，有其它方案吗

**Comment by PeachScript** [comment]
father 4 已发布，可尝试升级到最新版：https://github.com/umijs/father/blob/master/docs/guide/migrate.md

旧版本不再维护，感谢支持
