### ISSUE TITLE
father支持amd的打包吗？

### ISSUE THREAD

**Issue by ClearLuvMoki** [umijs/father#570]
最近在开发中里面代码一部分文件（大约几十个）用到了amd规范的js，但是在运行和打包都不支持，文档也没有找到说明，请问这是可配置的吗？

**Comment by fz6m** [comment]
umd 是兼容 amd 的，打包成 umd 就行。

**Comment by ClearLuvMoki** [comment]
@fz6m 感谢回复，新年快乐！
我新开的dumi模板，基础配置，默认是umd的，
<img width="748" alt="image" src="https://user-images.githubusercontent.com/61321768/214536525-a5c012d4-1ba3-4d88-8268-e90657258260.png">
====> 但是出现报错
<img width="555" alt="image" src="https://user-images.githubusercontent.com/61321768/214536012-eaebf849-36ee-49af-9fa8-7bad95d58581.png">

这是我的amd文件，格式都是
```javascript
define('expose', function (require, exports, module) {
  module.exports = window.HotBox = require('./hotbox');
});
```

**Comment by fz6m** [comment]
给一个最小复现看看，你的 amd 代码是在这个要被 father 打包的库里引用还是要用 amd 导入 father 打包完的代码。

**Comment by PeachScript** [comment]
> 但是在运行和打包都不支持

运行应该是指用 dumi 启动文档吧，dumi 的构建基于 webpack，默认不识别 AMD 模块，但可以 `chainWebpack` 改配置使其识别，不确定是否支持本地文件，参考：https://webpack.js.org/configuration/other-options/#amd

打包应该是指 father 构建吧，除 umd 打包基于 webpack 可能可以如法炮制以外；其他类型都是 bundless 平行输出，要做模块规范的转换只能找 babel/esbuild 的插件或自己写插件来实现，但这么做很诡异，AMD 产物就应该用 AMD 的模块加载器（比如 Require.js）来消费，否则 AMD 就没有意义了，还不如用 babel/swc ast 把这些模块的源码一次性转成 esm/cjs，一劳永逸

回到问题本身，father 默认不支持 amd 打包，并且考虑到 AMD 的流行度，未来也不会支持；其中 umd 可能可以用 webpack 配置来实现，其他 bundless 构建类型则是完全不支持，只会平行输出 AMD 模块，产物需要借助 AMD 模块加载器或者改项目的 webpack 配置实现识别、加载
