### ISSUE TITLE
请问，有像 webpack-bundle-analyzer 来分析产物构成的方式吗

### ISSUE THREAD

**Issue by lllenggg** [umijs/father#571]
请问，有像 webpack-bundle-analyzer 来分析产物构成的方式吗

**Comment by fz6m** [comment]
bundleless 仅仅 transform 文件，不会打包，只做转译，所以不含有第三方依赖，无需分析。

若是 umd 打包，可使用：

```bash
  ANALYZE=1 father build
```

See https://umijs.org/docs/guides/env-variables#analyze
