### ISSUE TITLE
father-build --watch 无法找到node_modules路径

### ISSUE THREAD

**Issue by buquan** [umijs/father#579]
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/23711051/217831598-30cf8836-b153-4c8e-bad9-6399b7c61d84.png">

<img width="1410" alt="image" src="https://user-images.githubusercontent.com/23711051/217832044-2561d5e3-ca0b-4f2e-abcd-f40849075881.png">

![image](https://user-images.githubusercontent.com/23711051/217828607-d8743996-b9fd-4c8b-b25b-1df76831321b.png)

仓库地址:[https://github.com/buquan/ifss](url)，
在根目录pnpm install，然后pnpm run dev，执行到ui包的dev对应命令是father-build --watch ，此时报错无法找到monorepo的@ifss/tools路径，如图。
但是在ui目录下单独执行pnpm run dev 没报错。
请指点下哪块配置有问题，困扰两天了，感谢🙏🙏🙏

**Comment by buquan** [comment]
请问father 4可以实现项目里import {x} from 'x'自动引入样式么（x.tsx引入了less这种情况）
不过我这个问题应该不是版本问题 ，哎

**Comment by PeachScript** [comment]
> 请问father 4可以实现项目里import {x} from 'x'自动引入样式么（x.tsx引入了less这种情况）

指的是 `babel-plugin-import` 吧，father 4 和 father-build 一样配置 `extraBabelPlugins` 即可实现

father-build 已经不维护了，使用遇到问题无法得到有效解决，建议升级到 father 4：https://github.com/umijs/father/blob/master/docs/guide/upgrading.md
