### ISSUE TITLE
可以在esm和cjs模式下使用 Bundle 构建模式吗？

### ISSUE THREAD

**Issue by qc-z** [umijs/father#583]

**Comment by PeachScript** [comment]
不行，bundless 是发展趋势，esm/cjs 没有支持 bundle 的计划

**Comment by xiazhiqiang** [comment]
可以通过插件实现吗？不知道在哪儿配置的

**Comment by PeachScript** [comment]
不可以，father 不会考虑 cjs/esm bundle 的场景，如果你有需求建议配合其他构建工具实现

**Comment by xiazhiqiang** [comment]
之前有诉求压缩lib和es目录下的资源，我通过插件实现压缩。现在是需要在lib/es目录根据入口文件打包相关的资源，只能通过其他工具实现是吗？以为是webpack什么配置导致的
