### ISSUE TITLE
`doctor` 命令提供 ignore 规则的能力

### ISSUE THREAD

**Issue by shockw4ver** [umijs/father#586]
Hi，

我们希望在项目里引用包时，import 语句可以不包含类似 `dist` 这样的目录，因此构建完成后会将输出目录中的文件复制到外部，但受限于 `PACK_FILES_MISSING` 规则，这样会通不过项目体检，可否提供规则忽略或可配置的能力，如：

.fatherrc.ts
```typescript
import { defineConfig, DoctorRules } from 'father';

export default defineConfig({
  // ...
  doctor: {
    // 忽略能力，规则仍然由 father 闭环，但可以调整严格程度
    ignore: [
      DoctorRules.PACK_FILES_MISSING
    ],
    // or 规则定制，开发者可新增或调整规则以更好的与具体项目结合
    rules: [
        'MY_SPECIFIC_RULE': () => { // ... },
        [DoctorRules.PACK_FILES_MISSING]: () => { // ... }
    ]
  }
  // ...
});

**PS:** 由于宿主环境无法快速升级到较新的 node 和 ts 体系，exports 方案不太适用

```

**Comment by PeachScript** [comment]
感觉不应该通过禁用 doctor 规则来满足这个场景，我理解原始诉求是要把 outputPath 输出到项目根目录，构建配合 `--no-clean` 参数 + 适当调整 `PACK_FILES_MISSING` 规则的路径逻辑即可？

**Comment by PeachScript** [comment]
你可以根据需要直接 PR 优化 `PACK_FILES_MISSING` 的检测逻辑，另外 father 也是支持挂载插件的，可以注册额外的规则做检测，当然如果是通用的规则，也欢迎提 RFC 贡献到 father 里

**Comment by shockw4ver** [comment]
> 你可以根据需要直接 PR 优化 `PACK_FILES_MISSING` 的检测逻辑，另外 father 也是支持挂载插件的，可以注册额外的规则做检测，当然如果是通用的规则，也欢迎提 RFC 贡献到 father 里

好的，争取能找到有价值的贡献点，3q~
