### ISSUE TITLE
使用 analyze 会显示端口号被占用

### ISSUE THREAD

**Issue by huarse** [umijs/father#587]
![image](https://user-images.githubusercontent.com/3724927/220106322-f3cc47cc-9e2f-4a9b-91f9-58a859794bd5.png)

如上图所示

最离谱的是无论将端口号设置成什么，都会提示端口号被占用（实际上并没有）

**Comment by fz6m** [comment]
不设置 analyze_port 试试

**Comment by huarse** [comment]
> 不设置 analyze_port 试试

不设置就是默认的8888，也一样报错

**Comment by PeachScript** [comment]
没有提供复现信息，看截图推测是因为有多个 umd entry

v4.1.9 已支持对多个 umd entry 启动 analyzer，issue 先关闭，有问题可再反馈
