### ISSUE TITLE
umd打包模式，打出来缺少文件

### ISSUE THREAD

**Issue by kentLin0** [umijs/father#588]
umd模式下打包出来的文件，只有第一个index.vue依赖文件，其他在index.vue中引用的文件都没进行打包（比如scss,其他vue），并且也不会对scss内容进行编译，请问有可以参考的.fatherrc.js文件参考吗
这是原文件
![image](https://user-images.githubusercontent.com/31646567/220570624-c804084e-2c57-44bc-bce3-2482f891c761.png)
这是打包出来的产物
![image](https://user-images.githubusercontent.com/31646567/220570699-30a97940-95c6-4154-aa97-efc618a60c4d.png)
下面是配置
export default {
    umd: {
        extractCSS: true,
        output: "dist",
        postcssOptions: {
            autoCSSModules: true
        },
    },
}

**Comment by PeachScript** [comment]
暂不支持 Vue 组件库打包

**Comment by PeachScript** [comment]
Duplicate of #210
