### ISSUE TITLE
打包的产物执行时报错：Must use import to load ES Module:

### ISSUE THREAD

**Issue by blankzust** [umijs/father#591]
原因是引入了一个esm模块依赖：inquirer，该模块无法被require，有什么解决方案吗
node version: v14.19.3
father version: 4.1.5

报错的代码（编译前）
![image](https://user-images.githubusercontent.com/8541906/221805973-37c0c785-65f2-443e-ac80-ea115ddc34be.png)

报错的代码（编译后）
![image](https://user-images.githubusercontent.com/8541906/221806109-8b8b258d-4e13-4a26-ab1c-51c65fb871d1.png)

**Comment by PeachScript** [comment]
三种思路：
1. 引用它提供 cjs 产物的版本
2. 你也用 esm 产物
3. 用 await import 替代 import 绕过
