### ISSUE TITLE
alias能否提供除了路径以外的字符串替换

### ISSUE THREAD

**Issue by blankzust** [umijs/father#592]
![image](https://user-images.githubusercontent.com/8541906/221845913-c41ab6da-4f46-49db-9617-00bc84ceca15.png)
类似这种

**Comment by blankzust** [comment]
这个是在开发monorepo组织的风格，本地调试时，得先build只能才能调试，ts版本读取类型文件都要build之后才能读取，不是很方便

**Comment by fz6m** [comment]
业务项目有 [`monorepoRedirect`](https://umijs.org/docs/api/config#monoreporedirect) 直接映射到源码，或者本地用 `father dev` watch 修改，没必要用 `father build` ，如果 IDE 有 type 更新不及时的问题，在 tsconfig `paths` 里 `../other-package/src/*` 映射到那个包的源码处理下。
