### ISSUE TITLE
[father 4]打包输出组件的antd-v5与调用项目antd-v4样式冲突

### ISSUE THREAD

**Issue by GuanJdoJ** [umijs/father#593]
- 描述：
1 使用dumi开发组件库，father打包，组件库用antd v5版本，用ConfigProvider配置prefixCls为mc
2 引用项目本身使用antd v4版本，导入1组件库中组件
3 引用项目中v4或v5某一个样式失效，有时是v5无样式，有时是v4无样式

- 展示：
下图铃铛来自组件库，按钮来自引用项目
<img width="595" alt="image" src="https://user-images.githubusercontent.com/30386473/222134136-8e563285-331f-4237-85e0-121e46feefac.png">

<img width="557" alt="image" src="https://user-images.githubusercontent.com/30386473/222132473-9d2b08ff-a7b3-4453-b95f-e75632289266.png">

- 组件库配置：
//.fatherrc
import { defineConfig } from 'father';
export default defineConfig({
  esm: { output: 'dist' },
});
//package.json
"antd": "^5.2.2",
"dumi": "^2.1.10",
"father": "^4.1.5",

- 引用项目配置：
//package.json
"antd": "4.24.8",

- 期望：
组件库与调用项目样式互不影响

- 疑问：
什么原因导致的这种现象发生，是打包配置原因吗

**Comment by PeachScript** [comment]
prefixCls 生效且产物运行不报错，说明打包是正常的，antd v5 是 css-in-js，也不存在样式编译的问题，所以从描述看该问题可能和组件库具体实现、项目依赖安装或实际项目编译有关，请自行排查解决

**Comment by GuanJdoJ** [comment]
我也没太想明白为什么会出现这种情况，我试了如果两个都用v5样式就正常了，能不能给一些具体点的可能点，启发一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月1日(周三) 晚上9:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [umijs/father] [father 4]打包输出组件的antd-v5与调用项目antd-v4样式冲突 (Issue #593)




 
prefixCls 生效且产物运行不报错，说明打包是正常的，antd v5 是 css-in-js，也不存在样式编译的问题，所以从描述看该问题可能和组件库具体实现、项目依赖安装或实际项目编译有关，请自行排查解决

**Comment by GuanJdoJ** [comment]
知道原因了，问题在于引用项目，该项目是用umi3创建的，查看了默认情况下的webpack配置，发现有别名配置
```
alias: {
  antd: '/umi-cra-v3/node_modules/antd',//v4
}
```
导致别的包中的antd也被指向了该处，需要在.umirc/config.ts中配置
```
export default {
  antd: false
}
```
