### ISSUE TITLE
如何分析构建产物，命令行和插件的方式都不生效

### ISSUE THREAD

**Issue by limerence19** [umijs/father#594]
1、命令方式 

"analyze": "ANALYZE=1 father build"

2、插件方式

import { defineConfig } from 'father';
const BundleAnalyzerPlugin = require('umi-webpack-bundle-analyzer').BundleAnalyzerPlugin;

export default defineConfig({
  plugins: [
    new BundleAnalyzerPlugin()
  ]
});

**Comment by limerence19** [comment]
father 版本 4.1.1

**Comment by PeachScript** [comment]
仅 umd 支持分析，`ANALYZE=1 father build` 即可

**Comment by limerence19** [comment]
> 仅 umd 支持分析，`ANALYZE=1 father build` 即可

后续有支持cjs esm 的分析计划吗，刚用插件试了下 umd 分析，就1个Index.ts，看不到细节，不知道使用的包的大小

**Comment by PeachScript** [comment]
> 后续有支持cjs esm 的分析计划吗

cjs/esm 没有计划，产物是 bundless 的，不含依赖，分析作用不大

> 就1个Index.ts，看不到细节，不知道使用的包的大小

切 stats 试下，使用方式参考 webpack-bundle-analyzer 的文档：https://www.npmjs.com/package/webpack-bundle-analyzer

**Comment by dinfer** [comment]
ANALYZE=1 father build 无法打开分析界面，配置上没有和分析相关的信息
