### ISSUE TITLE
配置 alias 无法生效

### ISSUE THREAD

**Issue by wy1009** [umijs/father#595]
配置：

``` JavaScript
import { defineConfig } from 'father'
import path from 'path'

export default defineConfig({
  // more father config: https://github.com/umijs/father/blob/master/docs/config.md
  alias: {
    src: path.join(__dirname, './src'),
  },
  esm: { output: 'dist' },
})
```

使用：

``` JavaScript
import BaseButton, { ButtonProps } from 'src/components/BaseButton'
```

报错：

![image](https://user-images.githubusercontent.com/18343973/222699603-9bb64a57-c9ff-4b59-addc-b997641b789e.png)

搜了下，尝试做过删 .dumi 文件夹的操作，也没能成功。
极极极大概率是我的问题，真问了蠢问题就删！

**Comment by PeachScript** [comment]
自行配置组件 alias 在文档里使用不是 dumi 的正确用法，参考 dumi 文档的最佳实践：https://d.umijs.org/guide/write-demo#%E5%9C%A8-demo-%E4%B8%AD%E5%BC%95%E5%85%A5%E7%BB%84%E4%BB%B6

另外对于问题本身，`.fatherrc.ts` 的配置仅对组件库源码构建生效，组件库文档构建相关配置需要参考 dumi 文档使用 .dumirc.ts

**Comment by wy1009** [comment]
> 自行配置组件 alias 在文档里使用不是 dumi 的正确用法，参考 dumi 文档的最佳实践：https://d.umijs.org/guide/write-demo#%E5%9C%A8-demo-%E4%B8%AD%E5%BC%95%E5%85%A5%E7%BB%84%E4%BB%B6
> 
> 另外对于问题本身，`.fatherrc.ts` 的配置仅对组件库源码构建生效，组件库文档构建相关配置需要参考 dumi 文档使用 .dumirc.ts

您好，您误解了呢。我提供的代码的“使用”部分就是组件库的源码，并不是文档 demo。我是在源码里抽离了一个公共组件，然后在源码中使用的，全程都没有涉及到文档部分。
