### ISSUE TITLE
father v4版本 targets参数不生效

### ISSUE THREAD

**Issue by hnliji1107** [umijs/father#613]
![image](https://user-images.githubusercontent.com/3294058/228723833-17e23e44-94a6-47cf-9b51-706f3059a4bd.png)
指定targets里chrome的版本号，构建出来的polyfill支持的chrome版本号没变
![image](https://user-images.githubusercontent.com/3294058/228723930-33bffabf-94ab-476c-b25d-08d28d4cf972.png)

**Comment by hnliji1107** [comment]
或者换一种思路，怎么让es.array.at这个polyfill支持更低版本的chrome?

**Comment by PeachScript** [comment]
father 将 targets 配置透传给 babel-preset-env 了，polyfill 的兼容性可以到 babel 或 core-js 社区寻找答案

**Comment by WanQuanXie** [comment]
@PeachScript 可以支持传递 core-js 的配置吗？看了下源码内部，目前只是将 target 透传了。但其它配置项，比如：swc 的 coreJs 和 mode 配置项用户就无法通过 defineConfig，如此一来，对于低版本浏览器不支持的语法，swc 只是针对新语法做了转译，无法注入 core-js 的 polyfill 代码

**Comment by PeachScript** [comment]
不支持，NPM 包的 bundless 产物带 polyfill 比较少见，由最终消费 NPM 包的应用来统一引入 polyfill 更合适，比如 Umi 就会根据 targets 自动引入需要的 polyfill
