### ISSUE TITLE
v4 版本打包 cjs 后每个文件有重复的代码

### ISSUE THREAD

**Issue by onlyling** [umijs/father#614]
## 配置文件

```ts
import { defineConfig } from 'father'

export default defineConfig({
  esm: {
    output: 'es',
  },
  cjs: {
    output: 'lib',
  },
  extraBabelPlugins: [
    [
      'babel-plugin-import',
      {
        libraryName: 'antd',
        libraryDirectory: 'es',
        style: true,
      },
    ],
  ],
})
```

## 构建产物

[npm code](https://www.npmjs.com/package/@fruits-chain/react-bailu/v/0.2.4-beta.0?activeTab=code) 点击 `lib` 文件夹内任意一个 `.js` 文件，每个文件都有 34 行代码是相同的。

## 需求

规避 `cjs` 每个文件相同的代码。

**Comment by PeachScript** [comment]
cjs 是给 Node.js 环境用的，构建速度比尺寸更重要，所以默认是 esbuild 构建，没有 babel 类似的 runtime helpers

如果需要用 runtime helpers，确保依赖里存在 `@babel/runtime-helpers` 且 cjs 的 transformer 设置为 `babel` 即可

**Comment by Flcwl** [comment]
我配置了不怎么失效呢。。编译出来的全是 @babel/runtime/helpers/ 里的东西，一顿冗余
![image](https://user-images.githubusercontent.com/26050644/231976404-3dc28ca8-b35f-42a1-9d4d-3c8fd4bd5782.png)

**Comment by Flcwl** [comment]
> @babel/runtime

在 monorepo 项目下，@babel/runtime 不能装在根目录下， 必须装在每个 father 编译的子包下面吗？
