### ISSUE TITLE
umd 模式打包，配置了externals 后，引入umd, window.xxxx = undefined

### ISSUE THREAD

**Issue by xuzhouchen1104** [umijs/father#615]
umd:{
    name:'xxxx',
    externals:{
      'react': 'React',
      'react-dom':"ReactDom"
    }
  },

去掉 externals 之后 就可以取到 window.xxxx

**Comment by Hwzzzzz** [comment]
这个问题是怎么解决的啊

**Comment by xiyangranhongyan** [comment]
> 这个问题是怎么解决的啊

例如 React, 在使用 umd 的项目里。

``` ts
import React from 'react';

window.React = React;
```

这是我的解决方案，不知道有没有更好的。

**Comment by Hwzzzzz** [comment]
你是externals了react和react-dom吗，我试了两种方式最终引入都报找不到useState,我搞得头都炸了，能详细说下怎么解决的吗，非常感谢

**Comment by PeachScript** [comment]
externals 是用来声明哪些模块不打包到 umd 里，但消费该 umd 时需要在前面引入这些模块的 umd，否则自然是 undefined，例如：

```html
<script src="https://example.com/lib/react.production.min.js"></script>
<script src="https://example.com/lib/react-dom.production.min.js"></script>
<script src="https://example.com/lib/my-library.min.js"></script>
```

关于 externals 详细的用法，建议仔细阅读 webpack 的文档：https://webpack.js.org/configuration/externals/

**Comment by Hwzzzzz** [comment]
![Uploading 1.jpg…]()

**Comment by Hwzzzzz** [comment]
我确实在head里面按顺序引入了react，reactdom，umd打包产物， window上能正常console，但是一但使用就报找不到useSate
