### ISSUE TITLE
umd 模式打包，配置了externals 后，引入umd, 报错

### ISSUE THREAD

**Issue by xuzhouchen1104** [umijs/father#616]
<img width="968" alt="image" src="https://user-images.githubusercontent.com/48044617/229264074-34cb5c94-b844-40e8-8dbd-b6028722879f.png">
经排查，组件库去除antd依赖就可以了，
externals 加入antd好像也不生效

**Comment by xuzhouchen1104** [comment]
father 配置如下 <img width="276" alt="image" src="https://user-images.githubusercontent.com/48044617/229264127-a05026bd-9ef6-44b0-a70f-7f69d80e2231.png">

**Comment by PeachScript** [comment]
提问请给完整复现步骤

**Comment by xuzhouchen1104** [comment]
1. 新建一个基于father打包的组件库仓库。
2. 新建一个组件Button, 直接返回<div>1</div> 即可
3. .fatherrc.ts配置，如下
     umd:{
        name:'repoName',
        externals:{
          'react': 'react',
          'react-dom':"react-dom",
    }
 },
4.   得到产物xx.min.js
5. 新建html ，script引入 
  <img width="569" alt="image" src="https://user-images.githubusercontent.com/48044617/229277194-f1f31aac-4297- 
  432e-9457-a9b318e931ca.png">
6. 没有任何报错，window.repoName 也可以取到
7. 步骤2种，引入antd，返回 antd的Button
8. 重复3,4，5
9. 报错
![image](https://user-images.githubusercontent.com/48044617/229277260-aac7ce30-a712-404e-bb1f-5ab896e735ec.png)

**Comment by fz6m** [comment]
react 的 external 配法是：

```ts
  externals: {
    react: 'React',
    'react-dom': 'ReactDOM',
  },
```

**Comment by xuzhouchen1104** [comment]
> react 的 external 配法是：
> 
> ```ts
>   externals: {
>     react: 'React',
>     'react-dom': 'ReactDOM',
>   },
> ```

一样的问题

**Comment by Atw-Lee** [comment]
这个是有什么标准吗，后面要求是大驼峰吗

> ###
> [Apr 1, 2023](#issuecomment-1492915353)

**Comment by Atw-Lee** [comment]
这个是有什么标准吗。后面要求是大驼峰吗

**Comment by Atw-Lee** [comment]
@xuzhouchen1104 请问如何解决的

**Comment by Atw-Lee** [comment]
createContext未定义是external了react。关掉就好了试试。但我后续会有其他的错误，感觉不是解决方法

**Comment by Atw-Lee** [comment]
太蠢了太蠢了，应该是这个原因https://blog.csdn.net/weixin_39964419/article/details/127263941
