### ISSUE TITLE
tsconfig 中增加 ignoreDeprecations 后打包失败

### ISSUE THREAD

**Issue by zhangminggeek** [umijs/father#620]
操作步骤
1. 执行 `father build`
2. 项目报错，错误内容：error - Error: Error parsing tsconfig.json content: Unknown compiler option 'ignoreDeprecations'.

tsconfig
```ts
{
  "compilerOptions": {
    // ...
    "ignoreDeprecations": "5.0"
  },
  "exclude": ["node_modules"]
}
```

**Comment by PeachScript** [comment]
father 内置的 TypeScript 是 `~4.8.4`，不支持也不需要该配置；father 的 TypeScript 版本会跟随 api-extractor，暂不确定具体时间
