### ISSUE TITLE
CJS_IMPORT_ESM rule cause ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING

### ISSUE THREAD

**Issue by PeachScript** [umijs/father#624]
### 问题

CJS_IMPORT_ESM 在 vm 里引入要检测的模块，通过捕获错误来判定是否引入了 pure esm 包：https://github.com/umijs/father/blob/fd609d481925b9807503f08532e1a13f908ae773/src/doctor/rules/CJS_IMPORT_ESM.ts#L39-L43

但在未开启 `--experimental-vm-modules` 的情况下，没有找到办法支持在 vm 里调用 `import('xxx')`，所以当要检测的模块里用了 `await import` 时，将会引起如下错误：

```bash
node:internal/errors:478
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING]: A dynamic import callback was not specified.
    at new NodeError (node:internal/errors:387:5)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:39:9)
```

### 解法

目前想到的：使用子进程替代 vm 引入要检测的模块，监听错误，不知道有没有更好的方式

### 现状

为了不影响项目，暂时先回滚版本到 `4.1.7` 了

**Comment by fz6m** [comment]
找到那个包看看 `package.json` 的 `"type": "module"` 就可以了吧，这样不可以么。

**Comment by PeachScript** [comment]
实际情况会比较复杂，项目可以通过 exports 字段指定 require 引入，以及仅在子路径下放置非 `"type": "module"` 的 `package.json` 提供 cjs 模块之类的

**Comment by PeachScript** [comment]
担心 eval 引起其他问题，比如检测的文件正好是 requireHook 这种会修改全局模块的，有可能导致 father 自己执行出问题😂

暂时没想到好办法，用 require 也容易有性能问题，打算下个版本先把这套 rule 回滚掉
