### ISSUE TITLE
执行father build时提示“The JSX syntax extension is not currently enabled”

### ISSUE THREAD

**Issue by zjz1993** [umijs/father#627]
因为一些原因，react组件源码中同时包含js和ts文件，使用father v4.1版本 在对react组件进行打包时报错 The JSX syntax extension is not currently enabled

**Comment by starsoul666** [comment]
这个问题如何修复呀，遇到同样的问题, father v4.1

**Comment by yumupinglan** [comment]
@zjz1993 @starsoul666 怎么解决的可以分享一下吗？谢谢
