### ISSUE TITLE
目前 father 针对 d.ts  的构建缓存逻辑存在问题

### ISSUE THREAD

**Issue by Carrotzpc** [umijs/father#637]
从构建结果看，目前 father 构建时是否重新生成 d.ts 取决于对应的 ts 文件是否改变，有些场景下依赖的 ts 文件改变也需要重新生成 d.ts 文件，例如 https://github.com/Carrotzpc/father-ts-project 这个项目，按照下面的步骤可以复现该问题：

- 安装依赖后先构建一次，记住 index.d.ts 的内容
- 然后改动下 src/sdk.ts 中 `getSdk`  函数的返回值内容，新增一个 `test3` 属性
- 重新构建后可以发现 index.d.ts 的内容并没有改变

**Comment by PeachScript** [comment]
是有这个问题，father 的持久缓存不会分析模块间的依赖关系；看来 tsc 的持久缓存基于官方的 incremental 来实现更合适，把缓存目录也指定到 `node_modules/.cache/father/tsc`，有兴趣可以来个 PR

**Comment by Carrotzpc** [comment]
好，晚点儿我试试

**Comment by PeachScript** [comment]
👍速度降低一点问题不大，准确性更重要

> 有 3 个用例没通过

我加了几条 comment，你有空看看，更新完我再触发 GitHub CI 试试

**Comment by Carrotzpc** [comment]
改了，你再看看

**Comment by PeachScript** [comment]
v4.2.0 已发布，感谢贡献 ❤️
