### ISSUE TITLE
基于 antd 的组件库 ssr 时报错

### ISSUE THREAD

**Issue by ycjcl868** [umijs/father#64]
![image](https://user-images.githubusercontent.com/13595509/61195488-e9705a00-a6fa-11e9-8115-add708a7098b.png)

**father build lib 里包含 es styles**，期望 build 是 `lib/styles`

![image](https://user-images.githubusercontent.com/13595509/61195484-e1181f00-a6fa-11e9-9ebb-1a286e509370.png)

**Comment by sorrycc** [comment]
给复现步骤。
