### ISSUE TITLE
lint 报错：TypeError: Cannot destructure property 'umd' of 'userConfig' as it is undefined.

### ISSUE THREAD

**Issue by BBSQQ** [umijs/father#645]
进入 node modules 给 father 加个 ||{} 就好了。
![image](https://user-images.githubusercontent.com/35586469/236145011-fb613670-ce2f-4193-98b7-4f2720fcfb38.png)

我同事和我一样是 father 4.2.0，但是他没有报错。我和他的 npm 版本略不同，我的版本信息如下：
![image](https://user-images.githubusercontent.com/35586469/236145205-5a86e925-a178-4f30-a6e1-54f6bf5454e9.png)

**Comment by PeachScript** [comment]
看截图是内部 Bigfish 组件库项目？在 Bigfish 组件库项目中 `config/config.ts` 里 `library` 配置项是必须的

**Comment by PeachScript** [comment]
内网非直接使用 father 的项目，对社区不具备参考性，已转钉钉讨论，issue 关闭
