### ISSUE TITLE
jest指定collectCoverageFrom不生效

### ISSUE THREAD

**Issue by xchunzhao** [umijs/father#65]
使用`father test`进行单元测试，在`jest.config.js`中指定`collectCoverageFrom`没有生效。

> 看到`father`包中 传入了`collectCoverageFrom: 'src/**/*'`作为`umi-test`的默认参数。最终会覆盖`jest.config.js`中的配置。

https://github.com/umijs/father/blob/master/packages/father/src/test.ts#L6
https://github.com/umijs/umi/blob/master/packages/umi-test/src/index.js#L80

**Comment by xchunzhao** [comment]
@sorrycc 是因为当不设置`jest.config.js`的时候，用来作为`umi-test`的默认参数吗？如果是这样的话，也应该在`umi-test`中去做这样的默认配置。

**Comment by xchunzhao** [comment]
> 使用`father test`进行单元测试，在`jest.config.js`中指定`collectCoverageFrom`没有生效。
> 
> > 看到`father`包中 传入了`collectCoverageFrom: 'src/**/*'`作为`umi-test`的默认参数。最终会覆盖`jest.config.js`中的配置。
> 
> https://github.com/umijs/father/blob/master/packages/father/src/test.ts#L6
> https://github.com/umijs/umi/blob/master/packages/umi-test/src/index.js#L80

上述描述有问题。并不是会覆盖`jest.config.js`的配置，是`jest`中明确表示，cli的参数优先级比`jest.config.js`中的高。https://jestjs.io/docs/en/cli#options

**Comment by PeachScript** [comment]
father 4 已发布，可尝试升级到最新版：https://github.com/umijs/father/blob/master/docs/guide/migrate.md

旧版本不再维护，感谢支持
