### ISSUE TITLE
prebundle esm 失败

### ISSUE THREAD

**Issue by DiamondYuan** [umijs/father#650]
// .fatherrc.js

```
export default {
  prebundle: {
    deps: ['dayjs', 'globby'],
    output: 'compiled',
  },
};

```

<img width="786" alt="CleanShot 2023-05-18 at 10 52 00@2x" src="https://github.com/umijs/father/assets/9692408/57a6f025-b040-464c-aff8-1fb1d69ce7f5">

**Comment by DiamondYuan** [comment]
![CleanShot 2023-05-18 at 10 53 01@2x](https://github.com/umijs/father/assets/9692408/4b75a657-0ebc-4c1c-b136-267fd1ac4da0)


```
// .fatherrc.js
export default {
  prebundle: {
    extraDtsDeps: ['dayjs', 'globby'], // 需要预打包的依赖包名，需要安装在 `devDependencies` 中
    output: 'compiled', // 默认输出目录，有自定义需求时才需配置
  },
};

```

改成 extraDtsDeps 也失败了。

**Comment by PeachScript** [comment]
prebundle 还是实验性特性，不一定能打包所有的 NPM 包，也并非所有的 NPM 包都适合被预打包（比如没有统一的 entry 入口、有动态模块获取等等），遇到打不成功的建议还是声明依赖

另外产物打包的底层包是 [ncc](https://github.com/vercel/ncc) ，类型打包的底层包是 [api-extractor](https://github.com/microsoft/rushstack/tree/main/apps/api-extractor/) ，有兴趣的话也可以 debug 找下原因，它们的维护频次变得很低了，遇到问题估计得靠我们自己投入解决

**Comment by PeachScript** [comment]
问题合并到 #611 ，issue 关闭
