### ISSUE TITLE
如果将某一个文件 直接copy到dist下

### ISSUE THREAD

**Issue by jlv-xjtu** [umijs/father#653]
father4+umijs/max4 umijs中copy命令失效

**Comment by PeachScript** [comment]
father 没有这个功能，有需要可以自己写脚本拷贝

**Comment by jlv-xjtu** [comment]
可以提供个示例吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月28日(周日) 晚上11:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [umijs/father] 如果将某一个文件 直接copy到dist下 (Issue #653)




 
father 没有这个功能，有需要可以自己写脚本拷贝

**Comment by PeachScript** [comment]
package.json:
```diff
{
  "scripts": {
-   "build": "father build",
+   "build": "father build && cp -r xx dist/xx"
  }
}
```
