### ISSUE TITLE
如何指定某些js文件不经过bable编译，还能输出到es/lib目录的

### ISSUE THREAD

**Issue by ksh033** [umijs/father#664]
项目中有已编译umd的js文件，通过require("./assets/aa.js")方式引入。编译不想让aa.js经过bable编译。使用ignores直接不输出了，有没有什么方式可以跳过编译，又能输出到es/lib目录的

**Comment by PeachScript** [comment]
没办法，既然已经编译过了，建议放在与 src 平级的其他目录，比如 `compiled`
