### ISSUE TITLE
打的包太大了，有没有办法配置成输出单文件和压缩的程度高一点

### ISSUE THREAD

**Issue by 1075488066** [umijs/father#666]

**Comment by 1075488066** [comment]
就只有几个ts文件，但是打包的和原来的区别不大。

**Comment by PeachScript** [comment]
单文件仅 umd 支持，其他都是 bundless 的不会做压缩，参考文档：https://github.com/umijs/father/blob/master/docs/guide/build-mode.md

**Comment by Flcwl** [comment]
@PeachScript 为什么bundless就不能压缩？ 期望压缩发包安装包体积呢怎么办

**Comment by Flcwl** [comment]
> @PeachScript 为什么bundless就不能压缩？ 期望压缩发包安装包体积呢怎么办

是否可以配置压缩呢？
