### ISSUE TITLE
minify怎么配置

### ISSUE THREAD

**Issue by zyh2123606** [umijs/father#667]
prebundle: {
    deps: {
      rimraf: { minify: true },
    }
  }
这样配置无效

**Comment by PeachScript** [comment]
依赖预打包默认启用压缩无需配置，参考文档：https://github.com/umijs/father/blob/master/docs/config.md#deps

不过我试了下 rimraf 的 dts 打包会失败，需要对它配置 `dts: false`，有兴趣也可以找下具体原因提 PR 帮 father 修复
