### ISSUE TITLE
father生成.d.ts文件的时候，时灵时不灵

### ISSUE THREAD

**Issue by fhchina** [umijs/father#669]
有的时候能生成所有的.d.ts文件，包括index.d.ts, 经常则是只生成一个.d.ts, 这怎么用？

**Comment by mortalYoung** [comment]
dev 应该是没问题的，看了一下源码我猜测是这一块问题的
https://github.com/umijs/father/blob/8df2e42a880405e1bd527c52a4a1fb65cde4ce6a/src/builder/bundless/dts/index.ts#L167-L211

在生成类型文件的时候是通过 emit 触发 incrementHost 的 writeFile 方法，把结果放到 output 里去。

这里感觉有一个问题，就是 emit 本身是异步的，output 一开始拿到的应该是空的，在 build 的时候由于直接结束掉了，没有 watch 行为，也就导致有时候快的时候生成了，有时候慢的时候没生成。
以上，我的猜测

**Comment by xiaohuoni** [comment]
是有错误的时候没生成吧？你相同的代码执行，会存在随机性吗？

**Comment by fhchina** [comment]
个人怀疑有可能是father吞噬了错误，不管是不是这个原因，作为一个专业的软件工具，尤其是father-build这种transpiler/compiler本质的工具，应该在build的过程中，能够输出详细的warning和error信息。father-build居然没有一个--verbose类似的开关，或者有--log-level这一类的开关，这实在是。。。 @sorrycc @xiaohuoni @mortalYoung @stormslowly

**Comment by fhchina** [comment]
> 

异步并发程序，如果同步处理有问题，会有随机的结果

**Comment by fhchina** [comment]
dev态也有问题，yarn start/dumi dev启动的时候，也是有的生成有的没有生成，没有报任何错误

**Comment by fhchina** [comment]
试了一下npx father dev似乎可以都生成出来，我先用这个方法绕过去

> dev 应该是没问题的，看了一下源码我猜测是这一块问题的
> 
> https://github.com/umijs/father/blob/8df2e42a880405e1bd527c52a4a1fb65cde4ce6a/src/builder/bundless/dts/index.ts#L167-L211
> 
> 在生成类型文件的时候是通过 emit 触发 incrementHost 的 writeFile 方法，把结果放到 output 里去。
> 
> 这里感觉有一个问题，就是 emit 本身是异步的，output 一开始拿到的应该是空的，在 build 的时候由于直接结束掉了，没有 watch 行为，也就导致有时候快的时候生成了，有时候慢的时候没生成。 以上，我的猜测

**Comment by fhchina** [comment]
father dev也不行了，这次一个都不生成了，真是见鬼

**Comment by PeachScript** [comment]
@fhchina 有没有稳定的复现步骤，我试下看，以及对应的运行环境信息也需要提供下

**Comment by mortalYoung** [comment]
试试看：https://github.com/mortalYoung/ant-design-testing
=================== Env =======================
Node.js: v18.16.0
npm: v9.5.1
father: v4.2.0
OS: MacOS Monterey(M1)
==============================================
不是很稳定的复现，但是每次 build 后 rm 掉 dist，再 build 都是没有 .d.ts 的，可以试试看

**Comment by PeachScript** [comment]
> father: v4.2.0

升级到 4.2.3 试下，4.2.0 是有问题的，关联 issue #644

**Comment by mortalYoung** [comment]
4.2.3 我没有复现问题啦～ 🥳

**Comment by xiaohuoni** [comment]
那我偷偷关闭 issues 了（🤫）

**Comment by fhchina** [comment]
升级到4.2.3依然没有解决这个问题。刚升级完之后，再yarn build一次，原本上次上次有的.d.ts文件，全都没有了。什么错都不报。

**Comment by fhchina** [comment]
刚升级到4.2.3后，father build还是不行，然后我把node_modules/, yarn.lock等全删了，然后重来一遍，正常了。用了两天，暂时没有发现.d.ts不生成的情况。我先把这个issue关了。但这个现象也正说明，想要把基于缓存的增量编译在各种情况下都做对是很难的，msvc, gcc这种级别的工具都做不到，偶尔也需要全新构建一次才能正常。工具应该给使用者两种选项，通常情况是可以增量编译的，需要时也可以完全从头clean build。 #670 @PeachScript

**Comment by gintamamadao** [comment]
"father": "^4.2.3" 遇到同样的问题，构建的时候发现有那么一两个文件无法生成 d.ts, 不过把这些文件的内容改一下，再重新跑构建就可以生成 d.ts

**Comment by hustcer** [comment]
4.3.0 依然时灵时不灵 😌

**Comment by PeachScript** [comment]
最好能给个稳定复现步骤

**Comment by hustcer** [comment]
目前没有办法稳定复现，这也是个问题

**Comment by PeachScript** [comment]
在 ant-design-icons 项目里复现了丢 `.d.ts` 的问题，因为项目构建流程特殊，源码是构建前实时生成的，所以排查发现了 #691 提到的问题，目前该 PR 已合并发布 [v4.3.1](https://github.com/umijs/father/releases/tag/v4.3.1)

大家有空可以再试试看，如果仍有问题请反馈

**Comment by Lizhooh** [comment]
今天发现，用的是 4.2.0 版本，搞了一下午，还以为是电脑问题

**Comment by chihm** [comment]
问题在4.5.3版本复现
