### ISSUE TITLE
father生成.d.ts文件时灵时不灵，能否加一个--no-cache开关，就强行rebuild，不用缓存

### ISSUE THREAD

**Issue by fhchina** [umijs/father#670]
如果是和缓存的实现有关，那能否加一个father build --no-cache开关，关闭缓存，全新构建。我的项目小，全量构建性能问题对我影响不大。升级到4.2.3时灵时不灵的问题，依然存在。 @sorrycc @PeachScript

**Comment by PeachScript** [comment]
Duplicate of #669

**Comment by PeachScript** [comment]
.d.ts 丢失的问题原 issue 讨论即可，不需要新开 issue，请在原 issue 下提供稳定的复现步骤

**Comment by PeachScript** [comment]
father 支持通过环境变量 `FATHER_CACHE=none` 禁用持久缓存
