### ISSUE TITLE
覆盖率检查lerna项目覆盖率全部为0

### ISSUE THREAD

**Issue by kakuyogy** [umijs/father#68]
![image](https://user-images.githubusercontent.com/32446924/61264353-d2933b80-a7be-11e9-9464-e0fb254e4009.png)

是要做额外的配置吗？

**Comment by ycjcl868** [comment]
给个复现的 mini 仓库，我看下

**Comment by ycjcl868** [comment]
` "cov": "father test --coverage --collectCoverageFrom=packages/**/**/src/**.{js.jsx,tsx,ts}",`

`father` 默认的是 `collectCoverageFrom: 'src/**/*'`
