### ISSUE TITLE
组件库打包，生成的类型声明（*.d.ts）在Linux环境下，生成的依赖路径是相对路径，windows 下则是正常的

### ISSUE THREAD

**Issue by JaylanChen** [umijs/father#685]
组件库打包，生成的类型声明（*.d.ts）在Linux环境下，生成的依赖路径是相对路径，windows 下则是正常的

father: v4.3.0
lerna: v6.x

windows 下构建
![image](https://github.com/umijs/father/assets/7055008/b2c0ae3f-8cf6-4daf-8fc8-4ffe4ebed704)

Linux 下构建（centos，apline）

![image](https://github.com/umijs/father/assets/7055008/10a456e1-02ea-4100-b611-ddfb26f94020)

**Comment by PeachScript** [comment]
提供最小可复现仓库看看

**Comment by JaylanChen** [comment]
> 提供最小可复现仓库看看

好的，周末看看弄一个

**Comment by PeachScript** [comment]
先关闭了，有复现了再 reopen
