### ISSUE TITLE
怎么使路径不转换“@@“

### ISSUE THREAD

**Issue by wefiy** [umijs/father#688]
因为组件库里面会引用项目的 @@ 目录，但是现在直接给转换成相对路径了，这样组件安装到项目里的时候会有问题。
会出现require('@@/core/routes') 自动转成 require("../../.umi/core/routes")。
如果配置alias  '@@': '@@'，则es模式下 会保持住 require('@@/core/routes')。
我感觉没必要解析 @@ 成相对目录。请问应该怎么保持 require('@@/core/routes') 不会被转换成相对路径？

**Comment by PeachScript** [comment]
组件库引 Umi 临时目录是不对的，作为独立的 NPM 包应该和开发框架解耦

**Comment by wefiy** [comment]
我明白，但是一个特殊的情况需要用到。 但为什么要翻译 @@ 字符呢？ 看了father里面 也找不到翻译的地方。 @PeachScript

**Comment by PeachScript** [comment]
father 会根据 tsconfig paths 自动推导 alias 配置
