### ISSUE TITLE
docz如果包含umi/router依赖，会生成失败

### ISSUE THREAD

**Issue by shengbeiniao** [umijs/father#69]
假设一个组件引用了
```
import router from 'umi/router'
```
[umi/src/router.js源码](https://github.com/umijs/umi/blob/9268d797d5a3c5563b413587871bda0d4ccc9c6d/packages/umi/src/router.js#L2)

因为第一行有一个@tmp引用，翻看umi源码，发现@tmp指向.umi目录，而docz用的rollup编译，不会加载webpack配置，所以生成失败

**Comment by sorrycc** [comment]
组件不要依赖 umi。

**Comment by sukechris** [comment]
> 组件不要依赖 umi。

在`umi`项目中，`components`文件夹下一般是封装的业务组件，组件里引用了umi，比如
```js
import Link from 'umi/link';
```

又或者在这组件中使用`@`（指向src目录）

```js
import EmptyText from @/components/EmptyText
```
会报错：

![image](https://user-images.githubusercontent.com/36565253/62524014-7bd1cc80-b867-11e9-9b24-8811754a4569.png)

如果这样的话，在原有的`umi`项目中，不能使用`father`了

@sorrycc @shengbeiniao

**Comment by sukechris** [comment]
@shengbeiniao 请教下你那个问题是怎么解决的
