### ISSUE TITLE
dev 命令支持 --no-clean 参数

### ISSUE THREAD

**Issue by j3r0lin** [umijs/father#693]
期望 father dev 命令像 father build 命令一样，支持 --no-clean 参数，这样可以在初次启动时，不清除目标目录下的文件。

**Comment by PeachScript** [comment]
暂时没遇到 dev 需要 --no-clean 的场景，如果你有场景需要可以描述下场景，欢迎提交 PR

**Comment by j3r0lin** [comment]
在 monorepo 里面结合 umi 一块使用，在 umirc  中引用了 father dev 构建后的产物。使用 umi dev 时，只要一启动 father dev，就会导致 umi dev 报错依赖的文件找不到。

**Comment by PeachScript** [comment]
v4.3.6 已支持，感谢 @PopperLi 贡献
