### ISSUE TITLE
如何配置打包的时候去掉注释

### ISSUE THREAD

**Issue by shengbaise** [umijs/father#694]
{
   entry: ['src/index.ts'],
  esm: {
    type: 'babel',
  },
  chainWebpack: (config) => {
    config.optimization.minimizer(name).use(TerserPlugin, [
      {
        terserOptions: {
          format: {
            comments: false,
          },
        },
        extractComments: false,
      },
    ]);
  },
}

会报错 Error: Invalid options in .fatherrc.ts

**Comment by PeachScript** [comment]
bundless 不走 webpack，使用 babel 的情况下可以用 extraBabelPlugins 挂额外的插件来移除注释；另外报错的问题是因为 entry 不是顶层配置，具体支持的配置项以文档为准：https://github.com/umijs/father/blob/master/docs/config.md

**Comment by yuanguandong** [comment]
> bundless 不走 webpack，使用 babel 的情况下可以用 extraBabelPlugins 挂额外的插件来移除注释；另外报错的问题是因为 entry 不是顶层配置，具体支持的配置项以文档为准：https://github.com/umijs/father/blob/master/docs/config.md

可以在esm，cjs配置下增加babelConfig吗，类似extraBabelPresets，extraBabelPlugins, 现在babel-plugin-remove-comments已经废弃了，而且babel-preset-minify也没有相关配置
