### ISSUE TITLE
是否可以支持build 和dev时可以选用不用的配置文件

### ISSUE THREAD

**Issue by tgxpuisb** [umijs/father#696]
如果配置中通过配置了 esm 和  umd 在father dev 的时候，会同时构建 umd 与 esm 两份代码，构建时间被拖长

是否可以支持 father dev 与 father build 的时候可以使用 --config=.fatherrc.umd.ts 这种写法

**Comment by PeachScript** [comment]
father 继承自 Umi 内核，`FATHER_ENV=umd` 可以试下，最终配置应该是合并 `.fatherrc.ts` 和 `.fatherrc.umd.ts` 后的结果

**Comment by tgxpuisb** [comment]
试过了，非常好用，感谢提醒

**Comment by fangbicheng** [comment]
> father 继承自 Umi 内核，`FATHER_ENV=umd` 可以试下，最终配置应该是合并 `.fatherrc.ts` 和 `.fatherrc.umd.ts` 后的结果

这个是只能在umi项目使用嘛？其他项目可以用吗？
