### ISSUE TITLE
v4.3.1 生成 cjs 代码时没有 index.d.ts，esm 看概率出现 index.d.ts

### ISSUE THREAD

**Issue by Lizhooh** [umijs/father#698]
**生成 cjs 代码时一直没有 index.d.ts，**

esm 就有时候有，有时候没有，改一下 tsconfig 又出来了。

修改 tsconfig 后编译：

![image](https://github.com/umijs/father/assets/19299088/37d56b1a-c85c-4dfe-a4e6-7ddac14dec4d)

编译完，再次编译，index.d.ts 不生成了：

![image](https://github.com/umijs/father/assets/19299088/d595f352-2d98-4590-951a-87299e6f99a7)

v4.3.1

![image](https://github.com/umijs/father/assets/19299088/8a826cdb-2ec2-4918-ab1b-f789897efe9f)

tsconfig:

```json
{
  "compilerOptions": {
    "target": "ESNext",
    "strict": true,
    "declaration": true,
    "skipLibCheck": true,
    "baseUrl": "./",
    "esModuleInterop": true,
    "removeComments": false,
    "noUnusedParameters": true
  },
  "include": ["src"],
  "exclude": [
    "dist",
    "test",
    "node_modules",
  ]
}
``` 

.fatherrc.ts:

```ts 
import { defineConfig } from 'father';

export default defineConfig({
  esm: {},
  cjs: {},
  prebundle: {
    deps: {}
  },
  sourcemap: false
});
```

### 复现步骤
1. 修改代码，build，esm 有 index.d.ts
2. 什么不要动，再次 build，esm 可能没有 index.d.ts
3. 修改  tsconfig 的字段，再次 build，esm 可能有 index.d.ts
4. 再次 修改  tsconfig 的字段，再次 build，esm 有 index.d.ts

**Comment by Lizhooh** [comment]
每次编译都心惊惊

**Comment by PeachScript** [comment]
.d.ts 缓存改用 incremental 的副作用，father 的 cache 与 tsc 的 tsbuildinfo 失效逻辑不一致造成的，需要想个彻底解

临时方案是改了 tsconfig.json 把缓存删一下，位于 `node_modules/.cache/father/tsc`

**Comment by Lizhooh** [comment]
@PeachScript 根据你的建议，我现在 build 命令改成：
"build": "rm -rf node_modules/.cache/father/tsc && father build" 
能临时解决

**Comment by PeachScript** [comment]
v4.3.2 已修复
