### ISSUE TITLE
father能够打包静态资源文件吗？

### ISSUE THREAD

**Issue by RudyDen** [umijs/father#699]

**Comment by PeachScript** [comment]
esm/cjs 是 bundless，非 JS 文件会直接拷贝到输出目录，不会做编译或打包

umd 是 bundle，图片资源文件且尺寸不超过 10000Bytes 会被 url-loader inline 加载，其他资源文件不会处理，如果有自定义需求可以通过 chainWebpack 改 webpack 打包配置

**Comment by BennieMeng** [comment]
md 文件发现不会被打包到输入目录。另外怎么避免对模板资源的lint解析。只copy到输入目录 @PeachScript
