### ISSUE TITLE
项目命名疑问

### ISSUE THREAD

**Issue by Francecil** [umijs/father#7]
在 umi 看文档发现404，看提交记录才发现迁到这了。

提出来可以，bug和版本也比较容易维护。

就是不知道为什么要叫`father`= =，用`umi-lib` 这类的不是更好么

**Comment by sorrycc** [comment]
更名有几个原因：

* 小步快跑，不用跟 umi 的发布节奏
* 理解上和 umi 解绑，可用于非 umi 项目，虽然现在实际上就是这样，但加 umi- 前缀容易让人误认为只有 umi 的项目能用。
* umi 本身是应用开发的框架，和组件开发关系不大

叫 `father` 只是恰巧有个容易记的包名。

**Comment by Francecil** [comment]
明白

**Comment by caozihao** [comment]
father  = 爸爸

**Comment by rdmclin2** [comment]
docz和storybook的爸爸
