### ISSUE TITLE
组件中引入的less文件在father build时无法被识别

### ISSUE THREAD

**Issue by chj-damon** [umijs/father#70]
假设我有一个组件`Test`，我要在这个组件里面引入一个样式，写成下面这种写法：
```jsx
import styles from './index.module.less';

export default function Test() {
  return (
    <div className={styles.title}>test</div>
  );
}
```

`index.module.less`的内容是：
```less
.title {
  color: red;
}
```

我的`.fatherrc.js`的内容是：
```js
export default {
  entry: 'src/index.tsx',
  esm: {
    type: 'babel',
  },
  cjs: 'babel',
  cssModules: true,
  extractCSS: true,
  lessInBabelMode: true,
  extraBabelPlugins: [
    ['babel-plugin-import', {
      libraryName: 'antd',
      style: true,
    }]
  ],
};
```

执行`father build`的时候会报错：
```js
Cannot find module './index.module.less'.
```

请问会是什么问题引起的？我应该怎么改呢？

**Comment by MingShined** [comment]
你用rollup构建吧，extraBabelPlugins多加一个配置
`      {
        libraryName: 'antd',
        libraryDirectory: 'es',
        style: true
      }`

**Comment by MingShined** [comment]
> 假设我有一个组件`Test`，我要在这个组件里面引入一个样式，写成下面这种写法：
> 
> ```js-jsx
> import styles from './index.module.less';
> 
> export default function Test() {
>   return (
>     <div className={styles.title}>test</div>
>   );
> }
> ```
> 
> `index.module.less`的内容是：
> 
> ```css-less
> .title {
>   color: red;
> }
> ```
> 
> 我的`.fatherrc.js`的内容是：
> 
> ```js
> export default {
>   entry: 'src/index.tsx',
>   esm: {
>     type: 'babel',
>   },
>   cjs: 'babel',
>   cssModules: true,
>   extractCSS: true,
>   lessInBabelMode: true,
>   extraBabelPlugins: [
>     ['babel-plugin-import', {
>       libraryName: 'antd',
>       style: true,
>     }]
>   ],
> };
> ```
> 
> 执行`father build`的时候会报错：
> 
> ```js
> Cannot find module './index.module.less'.
> ```
> 
> 请问会是什么问题引起的？我应该怎么改呢？

你用rollup构建吧，extraBabelPlugins多加一个配置
{ libraryName: 'antd', libraryDirectory: 'es', style: true }

**Comment by chj-damon** [comment]
@MingShined rollup构建有另一个问题，最后build之后，会把除了entry之外的文件夹也打包进来。
比如我的项目结构是这样：
-tests
-components
-examples
-others

在`.fatherrc.js`里面：
```js
export default {
  entry: 'components/index.tsx',
  esm: "rollup",
  cjs: 'rollup',
  extraBabelPlugins: [
    ['babel-plugin-import', {
      libraryName: 'antd',
	  libraryDirectory: 'es',
      style: true,
    }]
  ],
};
```

最后发现build出来的结果里面会包含components之外的文件夹。

**Comment by MingShined** [comment]
> @MingShined rollup构建有另一个问题，最后build之后，会把除了entry之外的文件夹也打包进来。
> 比如我的项目结构是这样：
> -tests
> -components
> -examples
> -others
> 
> 在`.fatherrc.js`里面：
> 
> ```js
> export default {
>   entry: 'components/index.tsx',
>   esm: "rollup",
>   cjs: 'rollup',
>   extraBabelPlugins: [
>     ['babel-plugin-import', {
>       libraryName: 'antd',
> 	  libraryDirectory: 'es',
>       style: true,
>     }]
>   ],
> };
> ```
> 
> 最后发现build出来的结果里面会包含components之外的文件夹。

entry默认是以src/index.ts / index.js为入口的，打包的内容也是以src目录为准，如果有别的目录，最好放置于src目录以外，我的src目录主要放的是组件。

**Comment by chj-damon** [comment]
是的呀。我把components改成src也是一样的。打包的时候始终会把跟src同级的文件夹也打进去。

**Comment by sorrycc** [comment]
不能复现，[sorrycc-Hxf75X.zip](https://github.com/umijs/father/files/3405743/sorrycc-Hxf75X.zip)

**Comment by chj-damon** [comment]
[umi-father-demo.zip](https://github.com/umijs/father/files/3406131/umi-father-demo.zip)
@sorrycc 是typescript环境。你可以用这个包试试。

**Comment by sorrycc** [comment]
```
src/index.tsx(1,19): error TS2307: Cannot find module 'react'.
src/index.tsx(2,20): error TS2307: Cannot find module './index.css'.
src/index.tsx(8,48): error TS7006: Parameter 'props' implicitly has an 'any' type.
src/index.tsx(10,5): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
src/index.tsx(17,5): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
```

ts 类型报错，和 father 工具无关。

**Comment by chj-damon** [comment]
问题的关键是为什么会说Cannot find module './index.css'。这个是打包的时候才报的错。正常dev的时候是没问题的。

**Comment by xiaohuoni** [comment]
最后怎么处理呢？

**Comment by hnsylitao** [comment]
现在我碰上的是css module 指定为true 了 但是less 还是没有css module

**Comment by guoyang007** [comment]
> ```
> src/index.tsx(1,19): error TS2307: Cannot find module 'react'.
> src/index.tsx(2,20): error TS2307: Cannot find module './index.css'.
> src/index.tsx(8,48): error TS7006: Parameter 'props' implicitly has an 'any' type.
> src/index.tsx(10,5): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
> src/index.tsx(17,5): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
> ```
> 
> ts 类型报错，和 father 工具无关。

@sorrycc   因为father提供了配置支持css modules。所以应该内置这个能力？比如ts+cssModules时使用这个loader： typings-for-css-modules-loader

**Comment by caozihao** [comment]
我用babel也会报这错，这个现在怎么解决的呢

**Comment by Mr-jiangzhiguo** [comment]
解决：
- 我提了 [pr](https://github.com/umijs/father/pull/220) 但没 merge，等 father3 出来吧
- 或者你可以看看我[这里](https://github.com/jsany/lean/blob/master/scripts/hack-depend.js)是怎么处理的

**Comment by shallinta** [comment]
mark

**Comment by QxQstar** [comment]
我也遇到了这个问题

**Comment by QxQstar** [comment]
我是在使用 dumi 的时候遇到这个问题的
