### ISSUE TITLE
[doctor] PHANTOM_DEPS 规则为什么不检测 devDependencies 呢？

### ISSUE THREAD

**Issue by moecasts** [umijs/father#703]
https://github.com/umijs/father/blob/9dbfe0747ae940f9dd72d2f050162af68a6d9726/src/doctor/rules/PHANTOM_DEPS.ts#L14-L22

这些是放在 `devDeps` 里的，应该也够了吧？

<img width="1131" alt="image" src="https://github.com/umijs/father/assets/37169906/8c8328df-528c-4237-a1be-8c18624620a1">

<img width="461" alt="image" src="https://github.com/umijs/father/assets/37169906/3c7c1b35-5357-4a0a-90d6-b2d0aedd5726">

**Comment by PeachScript** [comment]
doctor 检查的是要发布到 NPM 的源码，NPM 包安装的时候是不会安装 `devDependencies` 的，所以源码如果引入 `devDependencies` 声明的依赖，在实际项目中还是会变幽灵依赖

**Comment by moecasts** [comment]
哦哦，懂了，看错文件了，我还以为是扫到了根目录配置文件和测试文件。。。
不好意思😬
