### ISSUE TITLE
react 组件库 打包 umd 产物 后使用 报错，esm 产物正常使用

### ISSUE THREAD

**Issue by xiyangranhongyan** [umijs/father#705]
# demo
这两个 demo 是最新版本的 umi / dumi cli 创建的。
[组件库 demo](https://github.com/xiyangranhongyan/dumi-demo)
[组件使用 demo](https://github.com/xiyangranhongyan/umi-demo)

# 尝试解决

> 具体代码可以参考下demo，这里是为解决问题的一些尝试以及表现。

## 1. `react: 18.2.0` 时，使用组件报错 ` Cannot read properties of null (reading 'useState')`
![image](https://github.com/umijs/father/assets/31724313/bd1acefa-8269-47a0-8496-e1e0066b50db)

![image](https://github.com/umijs/father/assets/31724313/04e14a03-ad6d-4b63-bb6a-1ca0cd1faa66)

## 2. `react: 17.0.0` 时，使用组件报错 `Minified React error#321`

![image](https://github.com/umijs/father/assets/31724313/dad9c919-ace0-4354-abd1-a7cdaa143ae4)

![image](https://github.com/umijs/father/assets/31724313/36b82e16-a66f-40a4-9945-757837a75cb3)

## 3. 配置了externals 后，window.xxx === undefined

这个已经有人提过 [issue](https://github.com/umijs/father/issues/615)

**Comment by xiyangranhongyan** [comment]
这个似乎需要额外配置什么东西，看了下  fusion 的低代码物料系统 发现 react 被直接打包进了组件中，但又 没有使用 externals，更像是 直接把 react 产物 加进去了。

**Comment by daiyang123456** [comment]
请问，最后是怎么解决的呢？

**Comment by x011223** [comment]
> 请问，最后是怎么解决的呢？
使用组件的地方手动将 externals 的库挂到 window 上。比如 window.react = react;
