### ISSUE TITLE
引用Umi临时目录没有被打包进产物内

### ISSUE THREAD

**Issue by PopperLi** [umijs/father#706]
我需要对业务整合封装一个依赖，必然会用到Umi的临时目录，但目前我发现它没有随着father的build打包进去，有什么适用的解决方案吗？

![image](https://github.com/umijs/father/assets/31717528/c8852daa-f366-40b3-a802-9f16b5bb8874)

**Comment by PeachScript** [comment]
框架的临时目录仅在框架提供的编译时内才能正常工作，而组件库作为独立的 NPM 包与开发框架强耦合是不合适的，father 也不会对这类场景提供实践指南，建议设法与框架解耦

如果这个包是为拓展框架能力而存在，那么做成 Umi 插件是更加合适的选择
