### ISSUE TITLE
【rollup插件相关】想问下不支持extraRollupPlugins，那想看一下依赖包体积占比怎么办呢

### ISSUE THREAD

**Issue by TheYuuu** [umijs/father#708]
用通用的分析工具，比如source-map-explorer，分析的结果又有缺失

**Comment by PeachScript** [comment]
Duplicate of #571

**Comment by PeachScript** [comment]
v4 不是基于 rollup 的，参考上面的 issue 做产物分析即可

**Comment by TheYuuu** [comment]
> v4 不是基于 rollup 的，参考上面的 issue 做产物分析即可

感谢
