### ISSUE TITLE
tsx 文件里引用 less, father build 报 `Cannot find module './xxx.less'

### ISSUE THREAD

**Issue by zysuper** [umijs/father#71]
重现步骤：
1. 下载 测试工程
[father-tsx-import-less-issue.zip](https://github.com/umijs/father/files/3409295/father-tsx-import-less-issue.zip)
2. tyarn install
3. tyarn build
4. 终端显示 `semantic error TS2307: Cannot find module './index.less'. `
4. Good luck!

**Comment by zysuper** [comment]
typings.d.ts 文件要加： 
`declare module '*.less';`
我真是太菜了。

**Comment by fengyun2** [comment]
> typings.d.ts

如果我在packages/dialog包，这个文件得写在哪里呢？

**Comment by fengyun2** [comment]
@sorrycc 

father-build读取声明文件typings.d.ts无效

"father-build": "^1.13.2"

![image](https://user-images.githubusercontent.com/8147202/67366636-72264e00-f5a6-11e9-861a-fdf95cc7be00.png)



1. 我的 `tsconfig.json` 配置是这样的：

```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "module": "esnext",
    "target": "esnext",
    "lib": ["dom", "esnext"],
    "moduleResolution": "node",
    "jsx": "react",
    "esModuleInterop": true,
    "declaration": true,
    "noImplicitAny": false
  },
  "include": ["./packages", "./typings/"],
  "typings": "./typings/index.d.ts",
  "exclude": [
    "node_modules",
    "dist",
    "scripts",
    "build",
    "jest",
    "**/*.spec.ts",
    "es",
    "lib",
    "fixtures",
    "examples"
  ]
}

```

2. `./typings/index.d.ts` 配置如下：

```json
declare module '*.css'
declare module '*.less'
declare module '*.scss'
declare module '*.svg'

```

3. 目录结构：

![image](https://user-images.githubusercontent.com/8147202/67366384-fdebaa80-f5a5-11e9-99d0-afa71fcbd005.png)

**Comment by kokoroX** [comment]
> @sorrycc
> 
> father-build读取声明文件typings.d.ts无效
> 
> "father-build": "^1.13.2"
> 
> ![image](https://user-images.githubusercontent.com/8147202/67366636-72264e00-f5a6-11e9-861a-fdf95cc7be00.png)
> 
> 1. 我的 `tsconfig.json` 配置是这样的：
> 
> ```json
> {
>   "compilerOptions": {
>     "allowSyntheticDefaultImports": true,
>     "module": "esnext",
>     "target": "esnext",
>     "lib": ["dom", "esnext"],
>     "moduleResolution": "node",
>     "jsx": "react",
>     "esModuleInterop": true,
>     "declaration": true,
>     "noImplicitAny": false
>   },
>   "include": ["./packages", "./typings/"],
>   "typings": "./typings/index.d.ts",
>   "exclude": [
>     "node_modules",
>     "dist",
>     "scripts",
>     "build",
>     "jest",
>     "**/*.spec.ts",
>     "es",
>     "lib",
>     "fixtures",
>     "examples"
>   ]
> }
> ```
> 
> 1. `./typings/index.d.ts` 配置如下：
> 
> ```json
> declare module '*.css'
> declare module '*.less'
> declare module '*.scss'
> declare module '*.svg'
> ```
> 
> 1. 目录结构：
> 
> ![image](https://user-images.githubusercontent.com/8147202/67366384-fdebaa80-f5a5-11e9-99d0-afa71fcbd005.png)

试试把打包类型换成rollup
```
export default {
  entry: 'src/index.ts',
  esm: {
    type: 'rollup',
    importLibToEs: true,
  },
  cjs: 'rollup',
  extraBabelPlugins: [['import', { libraryName: 'antd', style: true }]],
};
```
我用babel的时候也是报错 改成rollup就好了

**Comment by kokoroX** [comment]
@fengyun2

**Comment by fengyun2** [comment]
@kokoroX 可是我想每个package单独打包，而不是统一打包到一个文件(dist/index.js)中。

**Comment by NexxLuo** [comment]
遇到一样的问题，定义的 typings.d.ts 没生效

**Comment by g4rick** [comment]
@NexxLuo  试试是不是可以把 typings.d.ts 放进src 或者 在 tsconfig.json 中 include 里面加上这个文件就好了

**Comment by DevXiaolan** [comment]
所以为什么关闭了呢，我感觉还没讨论完啊

**Comment by MinL-DN** [comment]
很久以前的问题了，今天偶然碰到，备注一下吧
引用一下掘金上一位大佬的研究
https://juejin.cn/post/7260425349107892283
把 .d.ts 改为 .ts 就可以了
