### ISSUE TITLE
Father build类型生成问题

### ISSUE THREAD

**Issue by liangskyli** [umijs/father#713]
版本 ：
father@4.3.4
react@18.2.0
typescript@5.2.2

编译代码
```ts
type IFoo2Props = {
  /**
   * @description 标题
   * @default "默认值"
   */
  title: string;
};
const Foo2 = (props: IFoo2Props) => <h4>{props.title}</h4>;

export default Foo2;
```

出现编译错误
```
error - src/foo2/index.tsx:8:7 - TS2742: The inferred type of 'Foo2' cannot be named without a reference to 'packages/demo2/node_modules/@types/react/ts5.0/jsx-runtime'. This is likely not portable. A type annotation is necessary.
error - src/foo2/index.tsx:8:7 - TS2742: The inferred type of 'Foo2' cannot be named without a reference to 'packages/demo2/node_modules/@types/react/ts5.0/jsx-runtime'. This is likely not portable. A type annotation is necessary.
error - Error: Declaration generation failed.
```

编译代码改为FC类型，这样就编译正常
```ts
import type { FC } from 'react';

type IFoo2Props = {
  /**
   * @description 标题
   * @default "默认值"
   */
  title: string;
};
const Foo2: FC<IFoo2Props> = (props) => <h4>{props.title}</h4>;

export default Foo2;
```

期待：这两个写法应该都能正常编译成功。

**Comment by PeachScript** [comment]
第二种才是正确写法，第一种直接跑 tsc 应该也会失败的

**Comment by liangskyli** [comment]
> 第二种才是正确写法，第一种直接跑 tsc 应该也会失败的

tsc 编译正常啊！
<img width="1042" alt="image" src="https://github.com/umijs/father/assets/31531283/f5b36772-a92f-4f2c-b50b-a66621aff160">

**Comment by liangskyli** [comment]
@umijs/max 构建也正常的

**Comment by PeachScript** [comment]
@liangskyli 要用第一种声明方式的话，tsconfig.json 里的 jsx 配置需要改成 `react-jsx`；我这里试了下是可以构建成功的，我的步骤：
1. npx create-dumi 选 react 模板
2. src/Foo/index.tsx 换成你的写法
3. tsconfig.json 的 jsx 换成 `react-jsx`
4. npm run build
5. cat dist/Foo/index.d.ts 可以看到用新版 jsx runtime 导出组件类型

如果你试下来仍然不行，可以提供最小可复现仓库看看

**Comment by liangskyli** [comment]
@PeachScript : tsconfig.json 的 jsx 是react-jsx，复现demo:

**Comment by PeachScript** [comment]
复现仓库可以复现，但和 tsc 行为不一致的原因尚未查明，哪怕按照 TypeScript 官方指南创建一个最简 compiler 也会报错：https://github.com/microsoft/TypeScript/wiki/Using-the-Compiler-API#a-minimal-compiler

**Comment by PeachScript** [comment]
原因已找到，下个版本修复，详见 #716 

另外回到复现项目本身，monorepo 下建议子包都各自放独立的 tsconfig.json，可以继承根目录的内容但 include 需要仅包含子包文件，这会使得子包构建时 tsc include 的文件数量大幅减少、提升构建效率，同时也可以避免在现有 father 版本中出现该问题

**Comment by liangskyli** [comment]
好，demo里子包没加独立的 tsconfig.json，正式的库会加，多谢建议

**Comment by PeachScript** [comment]
v4.3.5 已发布
