### ISSUE TITLE
father-test 结果和预期不符

### ISSUE THREAD

**Issue by DiamondYuan** [umijs/father#72]
https://github.com/boilerplate-fe/father-test-demo

复现方法
```
yarn
yarn test
yarn test2
```

**Comment by DiamondYuan** [comment]
```
class Test {
  public name: string;
  constructor(name: string) {
    this.name = name;
  }
}

class Test {
  constructor(public name: string) {}
}
```


上下代码是等价的，上面用了语法糖。
egg-bin test 测试通过
fahter test 测试不通过

**Comment by PeachScript** [comment]
father 4 已发布，可尝试升级到最新版：https://github.com/umijs/father/blob/master/docs/guide/migrate.md

旧版本不再维护，感谢支持
