### ISSUE TITLE
cjs默认不能编译双问号??，要怎么处理呢？

### ISSUE THREAD

**Issue by fangbicheng** [umijs/father#730]
### Version

4.1.0

### OS Version

mac

### Node.js Version

16.14.0

### Link to minimal reproduction

https://github.com/umijs/father/tree/master

### Steps to reproduce

none

### What is expected?

none

### What is actually happening?

none

### Any additional comments? (optional)

none

**Comment by fangbicheng** [comment]
cjs默认不能编译双问号??，要怎么处理呢？

**Comment by PeachScript** [comment]
调低 node 的 targets 即可，默认 14 支持 `??`：https://github.com/umijs/father/blob/master/docs/config.md#targets

后续使用问题请到 [Discussions](https://github.com/umijs/father/discussions)，issue 只处理 bug report 和 feature request
