### ISSUE TITLE
遇到类似问题，使用 dumi@2.0.13 搭建组件库，father@4.1.0 打包，xx组件中将 svg 作为 React 组件引用：

### ISSUE THREAD

**Issue by ynmlqdl** [umijs/father#739]
遇到类似问题，使用 dumi@2.0.13 搭建组件库，father@4.1.0 打包，xx组件中将 svg 作为 React 组件引用：
import { ReactComponent as IconChecked } from '../../assets/checked.svg'

dumi 启动文档，svg 图标正常显示，项目中引用 xx组件，svg 图标报错：（svg 没被导出成组件）
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
 

_最初由 panfei15623 在 https://github.com/umijs/father/issues/509#issuecomment-1571538632 发布_

如果还是想用svgr这种的话，dumi自身是支持svgr的，请问这个问题有办法解决吗？

**Comment by shanyijin2** [comment]
> 遇到类似问题，使用 dumi@2.0.13 搭建组件库，father@4.1.0 打包，xx组件中将 svg 作为 React 组件引用： import { ReactComponent as IconChecked } from '../../assets/checked.svg'
> 
> dumi 启动文档，svg 图标正常显示，项目中引用 xx组件，svg 图标报错：（svg 没被导出成组件） Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
> 
> _最初由 panfei15623 在 [#509 (comment)](https://github.com/umijs/father/issues/509#issuecomment-1571538632) 发布_
> 
> 如果还是想用svgr这种的话，dumi自身是支持svgr的，请问这个问题有办法解决吗？

dumi2（umi4）本身支持svgr，如果引用组件的项目不支持svgr的话，svg图标显示就有问题。可在father构建时处理svg资源
  extraBabelPlugins: [
    [
      'inline-react-svg',
      {
        svgo: {
          plugins: [
            {
              name: 'preset-default',
              params: {
                overrides: {
                  removeViewBox: false,
                },
              },
            },
            'removeDimensions',
            'convertStyleToAttrs',
          ],
        },
      },
    ],
  ]

**Comment by zbn1120** [comment]
> > 遇到类似问题，使用 dumi@2.0.13 搭建组件库，father@4.1.0 打包，xx组件中将 svg 作为 React 组件引用： import { ReactComponent as IconChecked } from '../../assets/checked.svg'
> > dumi 启动文档，svg 图标正常显示，项目中引用 xx组件，svg 图标报错：（svg 没被导出成组件） Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
> > _最初由 panfei15623 在 [#509 (comment)](https://github.com/umijs/father/issues/509#issuecomment-1571538632) 发布_
> > 如果还是想用svgr这种的话，dumi自身是支持svgr的，请问这个问题有办法解决吗？
> 
> dumi2（umi4）本身支持svgr，如果引用组件的项目不支持svgr的话，svg图标显示就有问题。可在father构建时处理svg资源 extraBabelPlugins: [ [ 'inline-react-svg', { svgo: { plugins: [ { name: 'preset-default', params: { overrides: { removeViewBox: false, }, }, }, 'removeDimensions', 'convertStyleToAttrs', ], }, }, ], ]

请问使用这个配置需要添加什么依赖吗，还是说father直接就可以使用
