### ISSUE TITLE
babel方式无法继承其他tsconfig.json

### ISSUE THREAD

**Issue by 662** [umijs/father#74]
babel方式无法继承其他tsconfig.json，配置文件申明了 extends，任然不会处理

**Comment by zen0822** [comment]
希望 father 3.0 能解决

**Comment by PeachScript** [comment]
father 4 已发布，可尝试升级到最新版：https://github.com/umijs/father/blob/master/docs/guide/migrate.md

旧版本不再维护，感谢支持
