### ISSUE TITLE
就想混合使用es和cjs,import一个exports的cjs模块后，在father build时候报错找不到ts文件导致无法生存d.ts, 请大神们指教！

### ISSUE THREAD

**Issue by buquan** [umijs/father#766]
### Version

4.3.0

### OS Version

Macos 14.0.0

### Node.js Version

18.0.0

### Link to minimal reproduction

https://stackblitz.com/edit/stackblitz-starters-momhvv?file=package.json

### Steps to reproduce

1. pnpm build
2. 报错： error - Error: Declaration generation failed.   ts2306 add.ts is not a module

### What is expected?

可以生成d.ts，并不报错，请官方大神指点下怎么配置

### What is actually happening?

<img width="1262" alt="image" src="https://github.com/user-attachments/assets/2c799e2f-9127-489a-b5c1-f5a9a1964673">

### Any additional comments? (optional)

我真的只想知道混用情况下，怎么处理可以彻底编译通过，希望大神不要指点说统一模块写法，我写了rollup的本地demo是可以处理好混用的情况，求指教，困扰好几天了

**Comment by PeachScript** [comment]
这是 TypeScript 的使用问题，请到对应社区寻找解法，比如 typescript issues、StackOverflow；另外 issue 仅受理 bug/feature 类问题，后续 father 使用相关问题请提交到 Discussion

> 我写了rollup的本地demo是可以处理好混用的情况

对于这个问题这里也解释下，father bundless 模式会调用 tsc 来为 ts 文件生成 d.ts，错误也是 tsc 查出来的；rollup 只做 bundle 不生成 d.ts 所以不报错是正常的

**Comment by buquan** [comment]
多谢及时指点
