### ISSUE TITLE
feat: father打包umd，如何保留文件里面的jsDoc类型注释

### ISSUE THREAD

**Issue by letterletter** [umijs/father#788]
### What problem does this feature solve?

希望组件中，下面的/** 开头的组件注释，可以保留
import * as lodash from 'lodash'
import React from 'react'

/**
 * Description placeholder
 * @export
 * @interface RenderComProps
 * @typedef {Object} {RenderComProps}
 * @property {string} label - 标签（文本）
 * @property {*} data - 数据
 */
export interface RenderComProps {
  label: string
  data: any
}

/**
 * RenderCom 组件
 * @param {RenderComProps} props - 组件的 props
 * @returns {JSX.Element}
 */
const RenderCom: React.FC<RenderComProps> = React.memo(props => {
  return (
    <div style={{ ...(props.style ?? {}) }} {...props}>
    </div>
  )
})

export default RenderCom

**Comment by PeachScript** [comment]
Duplicate of #789
