### ISSUE TITLE
bug: 打包umd时，chainWebpack配置comments后，entry里面的注释被清除了

### ISSUE THREAD

**Issue by letterletter** [umijs/father#789]
### Version

4.3.1

### OS Version

14.0.0

### Node.js Version

16.20.0

### Link to minimal reproduction

js

### Steps to reproduce

.fatherrc.ts
import { defineConfig } from 'father'

export default defineConfig({
  umd: {
    chainWebpack: (config, { env, webpack}) => {
      config.optimization.minimizer('js-terser').tap(args => {
        console.log('args', args)
        // 保留注释
        args[0].terserOptions.format = {
          ...args[0].terserOptions.format,
           comments: /^!/, // 或者使用 'all' 保留所有注释
        };
        return args;
      });
    },
    entry: 'src/render-com/index.tsx',
    output: {
      path: 'umd',
      filename: 'index.js',
    },
    externals: {
      react: 'react',
      'react-dom': 'react-dom',
      moment: 'moment',
      lodash: 'lodash',
    }
  },
  plugins: [
    // './father-plugin.ts'
  ],
})

组件src/render-com/index.tsx 中的注释如下
/*!
 * @export
 * @interface RenderComProps
 * @typedef {Object} {RenderComProps}
 * @property {string} label - 标签（文本）
 * @property {*} data - 数据
 */

/*! 
 * 这是一个重要的注释
 * 这个文件的功能是...
 * @license MIT
 */

### What is expected?

打包成umd后，src/render-com/index.tsx中的注释保留

### What is actually happening?

现在src/render-com/index.tsx中的注释被删除了，其他node_modules中的/!开头的注释保留了

**Comment by Jinbao1001** [comment]
未复现, 测试了下, 注释会被保留. 

有需要请提供最小复现仓库.

**Comment by letterletter** [comment]
[git@github.com:letterletter/father-umd-react.git
](https://github.com/letterletter/father-umd-react.git)不好意思大佬，入口文件组件内部的注释在，组件外部的注释被清除了，就下图圈中的部分，是要再加什么配置，去保留组件文件里面非组件内容部分的注释吗
<img width="651" alt="image" src="https://github.com/user-attachments/assets/6803116d-ea1c-460a-a3b5-f0fd3f18cf07">

**Comment by Jinbao1001** [comment]
因为外部注释其实是被 `tsc` 擦除的, 与`js压缩器`行为无关.

你的需求有点矛盾, 你想在`umd`文件中保留`ts`定义相关的注释, 但是`umd`肯定不会生成类似 `.d.ts` 文件相关的内容. 也就是`ts`接口定义 + 注释 肯定会被丢弃.


此`issue`与 `father` 构建流程无关, 需要你自己根据业务情况解决了哦. 比如手写`.d.ts`.
