### ISSUE TITLE
bug: 我在执行father doctor时报错：The JSX syntax extension is not currently enabled

### ISSUE THREAD

**Issue by wangchaoHeart** [umijs/father#791]
### Version

4.4.0

### OS Version

window11

### Node.js Version

20.10.0

### Link to minimal reproduction

1

### Steps to reproduce

1

### What is expected?

能正常通过doctor校验

### What is actually happening?

PS E:\asn-components-web> pnpm run doctor

> @asn-web/components@0.0.1 doctor E:\asn-components-web
> father doctor

error - Error: Build failed with 1 error:
index.js:24:8: ERROR: The JSX syntax extension is not currently enabled
    at failureErrorWithLog (E:\asn-components-web\node_modules\.pnpm\esbuild@0.17.19\node_modules\esbuild\lib\main.js:1636:15)
    at E:\asn-components-web\node_modules\.pnpm\esbuild@0.17.19\node_modules\esbuild\lib\main.js:1048:25
    at runOnEndCallbacks (E:\asn-components-web\node_modules\.pnpm\esbuild@0.17.19\node_modules\esbuild\lib\main.js:1471:45)
    at buildResponseToResult (E:\asn-components-web\node_modules\.pnpm\esbuild@0.17.19\node_modules\esbuild\lib\main.js:1046:7)
    at E:\asn-components-web\node_modules\.pnpm\esbuild@0.17.19\node_modules\esbuild\lib\main.js:1075:16
    at responseCallbacks.<computed> (E:\asn-components-web\node_modules\.pnpm\esbuild@0.17.19\node_modules\esbuild\lib\main.js:697:9)
    at handleIncomingPacket (E:\asn-components-web\node_modules\.pnpm\esbuild@0.17.19\node_modules\esbuild\lib\main.js:752:9)
    at Socket.readFromStdout (E:\asn-components-web\node_modules\.pnpm\esbuild@0.17.19\node_modules\esbuild\lib\main.js:673:7)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:545:12) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [Array],
      pluginName: '',
      text: 'The JSX syntax extension is not currently enabled'
    }
  ],
  warnings: []
}
 ELIFECYCLE  Command failed with exit code 1.
 

### Any additional comments? (optional)

我的配置文件如下：
father:
`export default defineConfig({
  esm: {
    input: 'src',
    output: 'es', // 输出目录
    transformer: 'babel', // 默认使用 babel 以提供更好的兼容性
    platform: 'browser',
  }
});`
jsconfig.json
`{
  "compilerOptions": {
    "strict": true, //启用严格类型检查。
    "skipLibCheck": true, //编译器将跳过库文件的类型检查
    "esModuleInterop": true, //允许以 ES6 模块的方式导入 CommonJS 模块
    "jsx": "react-jsx",
    "baseUrl": "./",
    "paths": {
      "@components": ["src/components"],
      "@utils": ["src/utils"],
      "@locales": ["src/locales"],
      "@hooks": ["src/hooks"]
    }
  },
  "include": ["src/**/*"],
}`
.dumirc.js
`const resolve = (dir) => path.resolve(__dirname, dir);
export default defineConfig({
  outputPath: 'docs-dist',
  resolve: {
    atomDirs: [
      { type: 'component', dir: 'src/components' },
      { type: 'utils', dir: 'src/utils' },
      { type: 'hooks', dir: 'src/hooks' },
    ],
  },
  themeConfig: {
    name: '组件库',
    editLink: false,
    sourceLink: false,
    lastUpdated: true,
    logo: '/logo.svg',
    footer: 'Copyright © 2024 | Powered by ASN',
    showLineNum: true,
  },
  favicons: ['/favicon.ico'],
  chainWebpack(config) {
    config
      .plugin('eslint-webpack-plugin')
      .use(EslintWebpackPlugin, [
        // eslint options
        {
          extensions: ['js', 'jsx', 'ts', 'tsx'],
          exclude: [
            'node_modules',
            'dist',
            '.history',
            '**/.dumi/',
            '**/.umi/',
            '**/.umi-production/',
            '**/docs-dist/',
            'mfsu-virtual-entry/**/*',
          ],
          eslintPath: require.resolve('eslint'),
          fix: true,
          emitWarning: true,
          emitError: true,
        },
      ])
      .end();
    config
      .plugin('stylelint-webpack-plugin')
      .use(StylelintPlugin, [
        {
          exclude: [
            'node_modules',
            'dist',
            '.history',
            '**/.dumi/',
            '**/.umi/',
            '**/.umi-production/',
            '**/docs-dist/',
          ],
          extensions: ['css', 'scss', 'sass', 'less'],
          files: '**/*.(s(c|a)ss|css|less)',
          fix: true,
        },
      ])
      .end();
  },
  alias: {
    '@components': resolve('src/components'),
    '@locales': resolve('src/locales'),
    '@utils': resolve('src/utils'),
    '@hooks': resolve('src/hooks'),
  },
  mfsu: false,
});`

**Comment by Jinbao1001** [comment]
根据提供的信息, 无法进行排查, 请提供最小复现仓库, 然后打开此`issue`
