### ISSUE TITLE
修改配置不会自动刷新

### ISSUE THREAD

**Issue by yutingzhao1991** [umijs/father#8]
修改 `.fatherrc.js` 不会自动刷新。

**Comment by sorrycc** [comment]
怎么复现？`father doc dev`?

**Comment by yutingzhao1991** [comment]
- 执行 `father doc dev`
- 修改  `.fatherrc.js ` 任意内容，没有效果。

**Comment by sorrycc** [comment]
好像不是新引入的问题，之前是不是也不会刷的？

**Comment by yutingzhao1991** [comment]
直接用 umi-library 不知道，但是用 bigfish 或者 umi 插件是好的，可能是因为会走 umi 的配置修改的监听逻辑。

**Comment by Francecil** [comment]
之前 umi-library 不会自动刷
