### ISSUE TITLE
多chunks提示设置output.dir

### ISSUE THREAD

**Issue by playedclass** [umijs/father#84]
动态导入组件时会引发这个问题
const Avatar = () => import('./avatar');
export default Avatar;

默认这样没有问题：export { default as Avatar } from './avatar'; 

修改getRollupConfig.js添加dir可以解决，后续会添加相关的自定义配置吗
![image](https://user-images.githubusercontent.com/3337266/62351258-99392a80-b537-11e9-816b-315406d851dd.png)

**Comment by PeachScript** [comment]
father 4 已发布，可尝试升级到最新版：https://github.com/umijs/father/blob/master/docs/guide/migrate.md

旧版本不再维护，感谢支持
