### ISSUE TITLE
怎么打包图片资源呢

### ISSUE THREAD

**Issue by Symboler** [umijs/father#89]

**Comment by fodurrr** [comment]
请问任何答案吗？Please, any answer? 
May be PR #93 would help?

**Comment by Slngle** [comment]
同问

**Comment by SmartWrh** [comment]
同问

**Comment by gauseen** [comment]
同问，使用 rollup 如何打包图片资源呢？

**Comment by flyween** [comment]
遇到了一样的问题

**Comment by duanliang** [comment]
依然不能添加图片

**Comment by PeachScript** [comment]
father 4 已发布，可尝试升级到最新版：https://github.com/umijs/father/blob/master/docs/guide/migrate.md

旧版本不再维护，感谢支持
