### ISSUE TITLE
father-build rollup & babel build watch error

### ISSUE THREAD

**Issue by ycjcl868** [umijs/father#97]
# 重现仓库
https://github.com/ycjcl868/father-ui-build-lerna-bug

# 描述
`yarn build` 是 ok 的， `yarn build --watch` 有问题。在 `lerna` 下。

![image](https://user-images.githubusercontent.com/13595509/64163930-bf265780-ce74-11e9-8410-98eb5e02b0bb.png)

**Comment by sorrycc** [comment]
```
export default
  {
    cjs: 'babel',
    entry: 'ui/index.tsx',
    typescriptOpts: {
      check: false,
    },
    umd: {
      name: 'plugin-2',
      minFile: false,
    },
  }
;
```

我发现改成这样就好了，满足需求，而且没有报错。

**Comment by ycjcl868** [comment]
https://github.com/umijs/umi/pull/3151/commits/48d0631a224a077cb1655da4130c8aea947e04e3
